### ISSUE TITLE
Question about colorbox and galleriffic- image skipping when closing colorbox

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1014]
Hi Stephen,

Currently I have galleriffic and colorbox activated for my album pages.
When colorbox pops up when clicking on the large galleriffic image in the album page, it opens colorbox. When closing this colorbox pop-up image it skips automatically to the next image.
Do you know how you can deactivate this skipping and have the image stay on the same image when closing in colorbox? I have been searching for a while now on the internet and cannot seem to find the setting. I presume it is a setting in the inc_header.php file.

Your help is much appreciated!

**Comment by sbillard** [comment]
I will have to look into this. Off hand I do no know.


-Stephen

**Comment by sbillard** [comment]
The cause of this slide advance is the galleriffic sideshow. Without 
colorbox, clicking on the image advances to the nest slide. I do not see 
any option in galleriffic to change this behavior.


-Stephen

**Comment by Elinth** [comment]
Hi Stephen,
Too bad the behavior cannot be changed. 
Thanks for looking into this. Much appreciated.

**Comment by Elinth** [comment]
Hi Stephen,

It is not in the options, I have seen that.
Can you maybe help me and have this behavior changed in the galleriffic.js file?
Hope you can help.

**Comment by sbillard** [comment]
You would be better off asking the author of the theme. He will be much more familiar with how to make changes to it.

**Comment by Elinth** [comment]
Will do, thanks
