### ISSUE TITLE
Zenpage news title dissapears after upgrade

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1018]
Upon upgrade the title for news dissapears in the Zenpage plugin. Easy to put again but I suspect this is not normal behavior. Also the plugin Gallery articles is de-activated, while it was activated in the previous build.

**Comment by sbillard** [comment]
Can you be more specific on "the title for news disappears?" Also look to see if you have got any errors reported, specially during setup. If a plugin gets an error during setup it will be disabled. That is the only case I know of where that would happen.

The changes between the 05 and 06 updates were minimal and not at all in the areas where your problems occurred.

**Comment by Elinth** [comment]
I think I had it on the previous build also. After running the upgrade the title for news disappeared. When I went to the Zenpage plugin settings the title field for News was empty in all languages. I have no errors in the setup and debug log. I am sure it was there before the upgrade.

**Comment by sbillard** [comment]
If you enable the devReleases plugin there will be a 2.00.01.06.01 release with the fixes

**Comment by Elinth** [comment]
This is absolutely great!!! This is just what I needed! Thank you Stephen!! Your support is amazing!
