### ISSUE TITLE
Email template editor

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1027]
Hi Stephen,

If you are still up for feature requests.. 
Another nice to have would be a facility were you can edit the email notifications, add a logo or style some text, add html, change colors, edit footer, etc.

Just a thought...

**Comment by sbillard** [comment]
Sounds interesting. So maybe create a fully editable "option" for the e-mails. For things like pictures it would require that the e-mail service support html encoded messages. Some only do text. The stuff would still get sent, but the receiver would not see the formatting, only the html codes.

**Comment by Elinth** [comment]
I have seen some great looking drag & drop scripts of email editors online, just as an example. Something in that drag&drop direction maybe? If you google that you see what I mean.

**Comment by sbillard** [comment]
I doubt these examples would be feasible. The environment is different with netPhotoGraphics. Probably on a shared server where giving file browsing capabilities would be a serious security threat. But the tinyMCE editor comes close--you can cut and paste text. For images you have to select something from the gallery via the pasteObj facility or specify a file location in the image insert dialog.

**Comment by sbillard** [comment]
So, I took a look at where netPhotoGraphics creates e-mails. These are mostly pretty succinct situations. Probably the best approach would be to allow the equivalent of a letterhead. The specific text would then be inserted into the letterhead. Creating a template for each iteration of a mail that could be sent would seem to be excessive.

**Comment by Elinth** [comment]
Indeed creating a template for each iteration of a mail would be much, on the other hand, then you can customize the text from each email though. tinyMCE would be a good solution I think. The letterhead idea sounds like a good option.

**Comment by sbillard** [comment]
This is now released in the 2.00.02 update

There is now a "forms" flyout on the options menu. Currently the only form is the e-mail template. It is editable with tinyMCE. The user customized form is stored in the ..plugins/forms/ folder so you can use whatever other editing tool you like if the simple tinyMCE editing is not sufficient.

**Comment by Elinth** [comment]
This is brilliant Stephen. Such a strong feature and easy to use! Well done

**Comment by sbillard** [comment]
Thanks for the suggestions. Its the ideas users like you have that keep netPhotoGraphics advancing.
