### ISSUE TITLE
Suggestion for slideshow controls

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1036]
I use the slideshow against a black background and the controls, being black do not appear against the black.  So I've created a light version of the controls png.

I'm wondering if it would be useful to add to the slideshow options a choice of control image versions (dark or light) so that users are not obliged to work around the problem by using their own version of the slideshow plugin that has the slideshow controls switched over to the lighter version.

I'll attach my light controls png in case you decide to implement this. (The 
file looks as if it contains only a set of blue controls but that's because the other sets of controls are all white)

Thanks

NK

![slideshow-controls-light](https://user-images.githubusercontent.com/3220548/65188281-e9eedf00-da22-11e9-8bdf-4cb4e012014b.png)

**Comment by sbillard** [comment]
Sounds like a reasonable request.

**Comment by nerdykit** [comment]
Wow! That was fast.  Thanks.  Tested, it works perfectly.

**Comment by sbillard** [comment]
Thanks for testing.
