### ISSUE TITLE
Effervescence+ theme exception 

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1039]
When trying open theme setting:

> UPOZORNĚNÍ: "require_once(/data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/image_effects.php): failed to open stream: Adresář nebo soubor neexistuje" in /data/web/virtuals/172972/virtual/www/themes/effervescence+/themeoptions.php on line 82

> EXCEPTION (64): "require_once(): Failed opening required '/data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/image_effects.php' (include_path='.:/data/web/virtuals/172972/virtual')" in /data/web/virtuals/172972/virtual/www/themes/effervescence+/themeoptions.php on line 82

**Comment by sbillard** [comment]
This is fixed in the current repository. Guess I need to make an install package with the updates.

**Comment by sbillard** [comment]
the .04 package has the fix.
