### ISSUE TITLE
.04 build bugs

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1045]
#1030 is back (alingment is OK, font is broken) and whole gallery is only in english

**Comment by sbillard** [comment]
I found the gallery in english issue. But I do not see the broken font. What theme? Maybe another picture.

**Comment by Mates-K1** [comment]
![Screenshot_2019-09-20 Admin Overview](https://user-images.githubusercontent.com/7648991/65350541-40584b00-dbe6-11e9-9277-cf94a891e8dc.png)
At least missing bolt.


![Screenshot_2019-09-20 Administrace Alba](https://user-images.githubusercontent.com/7648991/65350573-4f3efd80-dbe6-11e9-9e6e-861eb444600f.png)
Standard button font.

Seems only font in administration area is now (.05) broken.

**Comment by sbillard** [comment]
Sorry, I do not understand. I see nothing wrong in these pictures.

**Comment by Mates-K1** [comment]
Only first picture is wrong.

Font is not bold as usual in gallery and as in earlier builds. 

It was ok, .02 broke this, .03 repair and .04 partly broke this again.

20. 9. 2019 22:09, 22:09, Stephen <notifications@github.com> napsal/a:

**Comment by sbillard** [comment]
Ok. I can go with bold characters in the buttons.
