### ISSUE TITLE
Removing wasted space when changing site status (close, test mode,...)

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1048]
![obrazek](https://user-images.githubusercontent.com/7648991/65378973-0f991400-dcc1-11e9-98c1-72369f89dafb.png)
Site closed - OK

![obrazek](https://user-images.githubusercontent.com/7648991/65378987-23447a80-dcc1-11e9-879d-c154e6295a48.png)
Testing mode - OK (but different height)

![obrazek](https://user-images.githubusercontent.com/7648991/65379015-b382bf80-dcc1-11e9-91af-864a6eb4f6b4.png)

Site open - wasted space under text.

Can you please make all site status box the same height?

**Comment by sbillard** [comment]
Could you be more specific?

**Comment by Mates-K1** [comment]
I am sorry, I send post without any text. I edited first post now.

**Comment by Mates-K1** [comment]
If I can choose I prefer first height (site close).

**Comment by Mates-K1** [comment]
The same amount of space under text shows when safe some change and "Apllied" shows.

![obrazek](https://user-images.githubusercontent.com/7648991/65379386-6dc8f580-dcc7-11e9-949a-bbf694559a38.png)

**Comment by Mates-K1** [comment]
Site close, open and test mode works. :) Thanks.

Applied not.
