### ISSUE TITLE
Another minor adjustments to the buttons please

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1050]
![obrazek](https://user-images.githubusercontent.com/7648991/65379222-ebd7cd00-dcc4-11e9-8a0a-3c2d3043982b.png)
First button (restore...) is without mouse, Site close is with mouse.

But buttons without mouse in another part of gallery looks different (Reset to default is without mouse).
![obrazek](https://user-images.githubusercontent.com/7648991/65379254-9819b380-dcc5-11e9-8598-ff7ce6d385ff.png)

I think Reset to default looks better.

PART 2
When there is unsafed change on the page, button changes + his height changes:
![obrazek](https://user-images.githubusercontent.com/7648991/65379273-f3e43c80-dcc5-11e9-89e0-e3aea43b59e7.png)

And his on mouseover look is different:
mouse on Reset
![obrazek](https://user-images.githubusercontent.com/7648991/65379297-39a10500-dcc6-11e9-97ce-f4644d8e2ce3.png)

mouse on Apply
![obrazek](https://user-images.githubusercontent.com/7648991/65379303-4887b780-dcc6-11e9-95be-cb63694a2bc9.png)

**Comment by Mates-K1** [comment]
PART 3:
On the right of the Reset button, there is a quite weight area which change mouse to onmouseover design.

**Comment by sbillard** [comment]
The apply (dirty) button should have color gradient like the other buttons. I have fixed that. But I am not seeing (or do not understand) what you describe for the size change on mouse-over.

Fixes to 1048-1050 (dirty button) are in the DEV release if you wish to try them: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by Mates-K1** [comment]
All works. Size is OK now.

Is possible to make visual look of "Apply" and "Reset" button the same as "Reset to default"?

**Comment by sbillard** [comment]
I will change the Reset to default to be the same visual as the other buttons.

**Comment by Mates-K1** [comment]
Many thanks. 👍

22. 9. 2019 20:58, 20:58, Stephen <notifications@github.com> napsal/a:
