### ISSUE TITLE
Better custom brand in login form

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1051]
Can you please make brand logo in login form more responsive?

![obrazek](https://user-images.githubusercontent.com/7648991/65392158-da98ca00-dd71-11e9-948b-d179a07c7e11.png)

**Comment by Elinth** [comment]
Is it possible to make this logo for the login form optional? While remaining the admin branding logo?  It just looks quite odd when you already have a logo in the header already.

**Comment by sbillard** [comment]
Find the function printPasswordForm() in your theme. This function has 5 
parameters--printPasswordForm($_password_hint, $_password_showuser, 
$_password_showProtected, $_password_redirect, $showLogo)

The last parameter should be FALSE. But all in between parameters must 
be present. For parameters you theme did not originally pass you should 
pass the default as defined below:

$_password_showuser : NULL
$_password_showProtected : true
$_password_redirect: NULL



-Stephen

**Comment by sbillard** [comment]
see https://www.w3schools.com/css/css_display_visibility.asp

This site is a good place to look for answers to questions on CSS>


-Stephen

**Comment by Elinth** [comment]
Is this what you mean? I keep getting errors.
<?php printPasswordForm(isset($hint) ? $hint : NULL, isset($show) ? $show : TRUE, false, isset($hint) ? WEBPATH : NULL, $_password_showuser: NULL,
$_password_showProtected: true, $_password_redirect: NULL, $showLogo :false); ?>

**Comment by Elinth** [comment]
Thanks!
