### ISSUE TITLE
Add tags to image and click Aplly button says "Nothing changed "

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1052]
As title says...

Add tag via plus button, then Apply button indicates unsaved changes. So I click Apply button and then text above button says: "Nothing changed".

Hmm.... It looks like text allways says Nothing changed... :/ ... when I do any changes.

**Comment by sbillard** [comment]
This was fixed by https://github.com/netPhotoGraphics/netPhotoGraphics/commit/7b8611f872efb46aa40e86fcbd86706d1dde595d but the comment mis typed the issue #
