### ISSUE TITLE
Warnings when adding users to group (after Apply)

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1056]
![obrazek](https://user-images.githubusercontent.com/7648991/65957429-18ba7b80-e44d-11e9-898b-b48d493a5c48.png)

**Comment by sbillard** [comment]
I could not reproduce the error, but I believe this change will fix it. Please confirm.

**Comment by Mates-K1** [comment]
No warning after "Apply" 👍 , message says "Saved", but nothing change. User is still not in desired group  (I tried it from Admin-Groups).

From single user page, it works.
