### ISSUE TITLE
Basic theme - image size

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1057]
For 900px it look like this :(

![obrazek](https://user-images.githubusercontent.com/7648991/66021884-6afea980-e4ec-11e9-8a5f-a88bc9ce1b2d.png)

Maximal looks-good width is about 680 px.

Is possible to make it a little bit responsible?

**Comment by sbillard** [comment]
The basic theme was not designed to be responsive. But you can set the image size in the theme options.

**Comment by Mates-K1** [comment]
I know this. But is possible to restrict value larger about 680 px (wide) if theme dont support them?

**Comment by sbillard** [comment]
It is possible. The them could check the value of the option and if it is too large, set it transiently to the max value. However, this is not a simple matter. In your case, I presume the size is for the "longest side" but it might be for the height or width or shortest side, so you would have to figure out what those relationships were.

But I do not understand why you do not simply set the theme option to  680 and be done with it. That is what the option is there for.

**Comment by Mates-K1** [comment]
I know I know...

680 px is mine tried value. Default value is 595 px. 

All I am dealing with are the visible dimensions of the images. I think in year 2019 width 595 px is so small to display in most of monitors. My 15,6" NTB has visible area 1903 x 944 px (Firefox), default value for Basic theme (4:3 ratio) is 595 x 446 px. See full picture please.
![obrazek](https://user-images.githubusercontent.com/7648991/66129898-185ae580-e5f1-11e9-9941-e8707e70e6f2.png)

Thats why I am still looking for responsive theme or theme with larger basic image dimension (my zpArdroise has 700 x XXX px). Propably I will use zpBootstrap, but it need a little bit changes...

**Comment by sbillard** [comment]
Of course the default value can be changed--that is why it is an option.  What can be also done, is to have the image.php script expand the main DIV width if the width of the image would be grater than the 585 default.

But this is not responsive, nor is the theme. That is, after all, why it is named Basic! If you pick a size that looks good on your monitor it may not work so well on a tablet or smaller monitor.
