### ISSUE TITLE
ZenFluid theme - alignment of buttons

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1059]
![zenfluid2](https://user-images.githubusercontent.com/7648991/66128321-ed22c700-e5ed-11e9-8abf-f7313d27d882.jpg)

**Comment by sbillard** [comment]
It would help analysis if you could either show the whole page or at least tell what you are displaying (image page, album page?)

**Comment by Mates-K1** [comment]
Image page...

**Comment by Mates-K1** [comment]
Works 👍
