### ISSUE TITLE
Paradigm - menu overlay

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1061]
![paradigm](https://user-images.githubusercontent.com/7648991/66128588-6b7f6900-e5ee-11e9-88af-dcd35709dd53.jpg)

**Comment by sbillard** [comment]
The visual is by the theme design. It that the issue? 

I did notice  (and fixed) that the links may not be clickable depending on if you mouse over another link.

**Comment by Mates-K1** [comment]
Yes, primary it was problem (not clickable links). 

Hmm.. dropdown visual would be a little bit better. :/ This is not important for me.

Thanks for repair this.
