### ISSUE TITLE
Plugin icons - alingment in columns is a little bit broken

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1064]
![obrazek](https://user-images.githubusercontent.com/7648991/66234436-027f1a80-e6ee-11e9-90c0-8d3f4f6be7d9.png)

**Comment by sbillard** [comment]
I see this from your picture, but do not see it on my tests. What I do notice is that the icon for a class plugin is not the correct size. I do not know if that is a browser issue or an old version of the software.

Please view https://netphotographics.org/openAdmin/npg/admin-tabs/plugins.htm

Does it look correct to you? If not please try Chrome and see it that looks correct.

**Comment by Mates-K1** [comment]
In Firefox your test looks the same as my picrure. In Edge your test looks almost OK. As you wrote, class plugin icon has propably different size.
From Edge:
![obrazek](https://user-images.githubusercontent.com/7648991/66244151-6bbf5780-e707-11e9-819e-9d87b59711d2.png)

Chrome looks OK.

My first screenshot was From Firefox, so I will try look in to plugin page without any browser plugins and themes. But now I am uploading huge amout of images via browser and it takes about eight hour to go. So I cant restart browser without plugins now. :/

So it looks like main problem is in Firefox and/or in some of my plugins.

**Comment by sbillard** [comment]
Each icon is styled to be 18px x 18px wide via a <span> therefore all should line up in spite of the image size. So Firefox must not be honoring that CSS. Not much netPhotoGraphics can do for that.

**Comment by Mates-K1** [comment]
I think it is related to #1063, there is something broken in my NPG instalation. :/

**Comment by Mates-K1** [comment]
Propably not related. #1063 is about social links as I wrote.... :/

**Comment by Mates-K1** [comment]
Class plugin icon - span.font_icon;  - **there is bad semicolon.**

And there is different vertical-align - from -2px (feature icon plugin), 1px (admin plugin) to +2px (class plugin). I think feature plugin icon should have 0px vertical-align for better alignment.

**Comment by Mates-K1** [comment]
It works, thanks!
![obrazek](https://user-images.githubusercontent.com/7648991/66367990-d639f700-e996-11e9-8676-3832880f025d.png)

**Comment by sbillard** [comment]
I guess FireFox is less forgiving than Chrome or Edge.
