### ISSUE TITLE
Suggesting of tags not works for another the same tag

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1065]
On mass-edit-images page start type to tag field, get suggest of tag, click plus icon to confirm tag.

Then go to another image, start type to tag field the same tag... and you won't get help. The same tag does not work, another tags suggesting work.

**Comment by sbillard** [comment]
There are two work-a-rounds for this problem. 

The most prefered, I think, is to use the bulk actions when you are setting the same tag to multiple images.

It also works to enter a backspace as the first character of each additional image. The backspace apparently resets whatever has been left setup.

**Comment by Mates-K1** [comment]
I will prefer second work-a-round. First one seems less usefull for me.

**Comment by sbillard** [comment]
I know what is happening, so maybe I will find a way to fix the problem. The suggest plugin does not distinguish among input fields, so it thinks it has already provided (and you have used) the first suggestion. Now just a matter of figuring how to convince it otherwise.
