### ISSUE TITLE
Another unprotected pages in private gallery

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1066]
I have private gallery.

Is there any way to set some of page (which I created) and all News public?

**Comment by sbillard** [comment]
You can un-protect the index page. I can add the news.php script to the list of scripts that can be unprotected. Any control of what is then displayed would be up to the them scripts.

**Comment by Mates-K1** [comment]
Thanks.

Now my unprotected pages are:

- contact.php
- home.php
- inc_footer.php
- inc_header.php
- inc_print_album_thumb.php
- inc_print_image_thumb.php
- inc_print_news.php
- index.php
- register.php

And what about custom pages (pages which I created)? May be you said it in last sentense, but for me it remained in translation.

**Comment by sbillard** [comment]
You do not need to unprotect the "inc_" pages, only pages that are directly loaded by URLs

**Comment by sbillard** [comment]
Any custom script you make should show up in the list of pages that can be unprotected.

**Comment by Mates-K1** [comment]
Hmmm... I dont know how to make/add custom script to show up those pages unprotected.

Can you direct me how to do it please?

**Comment by sbillard** [comment]
With the current development release your news can be un-protected by simply checking the news.php script in callery options/unprotected pages.

Showing specific CMS pages is a bit more complicated. You would start by making a copy of the theme pages.php script, maybe call it "public_pages.php" and unprotect that script. You will have to decide how you are going to link to these custom pages. Perhaps a custom menu item? Anyway, the link will need to pass the page titleLink in a query parameter. Then public_pages.php will have to instantiate $_CMS_current_page = newPage($titlelink); Where titlelink is the string you passed.

You may well want to make other modifications to public_pages.php. Things like breadcrumbs may not make any sense. Even if they did, they would invoke the protected pages.php script so would not work.

**Comment by Mates-K1** [comment]
Many thanks. I will try it.

If gallery is public and albums are protected - is there only one password or users can have different passwords?

**Comment by sbillard** [comment]
Registered users will be able to view the albums when they are logged in. But I also have another thought that I need to research. There is a filter that might let you decide what to show and not to show.

**Comment by sbillard** [comment]
So, you can do all this with a filter. In your theme's functions.php add the following code.

`npgFilters::register('isUnprotectedPage', 'test_protection');

function test_protection($allow, $page) {
	switch ($page) {
		case 'pages':
			global $_CMS_current_page;
			return in_array($_CMS_current_page->getTitleLink(), array('all-things-npg.htm', 'npg-architecture.htm'));
		case 'news':
			return true;
			break;
	}
	return $allow;
}`

For the array list the titlelinks of the pages you wish to allow to be viewed. This will allow all news articles and the selected list of pages to be publicly viewed. If you wanted to restrict the news, you could do a similar test on the news category of the article.

**Comment by Mates-K1** [comment]
Woooorks!!! Yeah, you are programming God!!!

Many thanks!!! 🥇

**Comment by Mates-K1** [comment]
Is possible to make it as plugin or standard part of nPG so I don't need to edit theme after every update?

**Comment by sbillard** [comment]
Sure. To make it a plugin, just put the code in a separate file in the plugins folder. You will have to add the plugin header stuff: Look at the demoplugin for what you need.

**Comment by Mates-K1** [comment]
👍 
(I cant find demoplugin :( , I looked to another plugins)

I wrote to nPG forum, can you check it please?

**Comment by sbillard** [comment]
https://github.com/netPhotoGraphics/DevTools/blob/master/plugins/demoplugin.php

**Comment by Mates-K1** [comment]
Thanks. For me, you can close this issue.
