### ISSUE TITLE
Can not move subpage

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1068]
I can not move subpage to another group of subpage or make this subpage as "main" page. I can only move this subpage in its own group of subpage.

![obrazek](https://user-images.githubusercontent.com/7648991/66368831-1c448a00-e99a-11e9-91c2-ec5c9aef2f88.png)

**Comment by sbillard** [comment]
I have this working on my DEV build. But there are a lot of changes to this build having to do with consolidating button creation. So far as I know all these changes work, but with any such extensive change there may well be inadvertent errors.

These changes are primarily on the administrative pages, so the front end site should have no problem. Still if you wish to try this you should use care. You can get the install file at: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

(Note: there is a plugin--devReleases--which will detect these packages and offer them for install much like the normal install packages.

**Comment by Mates-K1** [comment]
I tried instal DEV via devReleases plugin.

There is a little bug in moving pages.

![obrazek](https://user-images.githubusercontent.com/7648991/66509706-e0addb00-ead3-11e9-9387-026daa610058.png)

Goal: Move "Pirát" page under "Bondy".

Bug: You can move to global level only last page in nest = you cant move "Pirat" until "Kvakin" was moved away.

**Comment by sbillard** [comment]
It seems that the way to move things in the list is to take them out via the bottom of the list. That is, grab the item, move it to the bottom then to the left and drop it. Once it is at the prime level it can be moved be a page of some other subalbum.

I will look into this, but the sorting is handled by a third party software https://github.com/ilikenwf/nestedSortable.

**Comment by sbillard** [comment]
I have investigated the javaScript support for this feature. It very deliberately says that it will move an item one level up but only if it is the last item in the list. Therefore, I do not think it practical to change the behavior. 

I have documented how do do moves in75917f
