### ISSUE TITLE
zpBootstrap - searching PDF - results formating

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1073]
netPhotoGraphics 2.00.02.08.08

I have PDF files with JPG thumbs in my gallery. When I search them it looks this way:

![obrazek](https://user-images.githubusercontent.com/7648991/67179386-713ec200-f3d6-11e9-9b99-1930a3e8c372.png).

When I search "jpg" or "mp4" it looks fine.

**Comment by sbillard** [comment]
I am not able to reproduce this. But perhaps it is data dependent. can you zip up the album and attach it to this ticket?

**Comment by Mates-K1** [comment]
Yes, I can. But it takes me some time. PDF files are not in one folder but in across whole gallery and have thumbs in JPG.

**Comment by sbillard** [comment]
Ok, whatever you can do so I can reproduce the issue. Unfortunately If I cannot see the failure it is pretty hard to fix.

**Comment by Mates-K1** [comment]
Well, I downloaded all PDF files and thumbs. 

But I think it is about how theme is handling with PDF files.

When there are only jpg files, all is OK.

![obrazek](https://user-images.githubusercontent.com/7648991/67513251-c4489b80-f69a-11e9-8b17-d469814d4d13.png)

![obrazek](https://user-images.githubusercontent.com/7648991/67513269-ce6a9a00-f69a-11e9-8efd-faa6d3f6ca8c.png)

When there are jpg and pdf files mixed, theme is broken.


![obrazek](https://user-images.githubusercontent.com/7648991/67513352-f22de000-f69a-11e9-9d29-0b940edcd870.png)

![obrazek](https://user-images.githubusercontent.com/7648991/67513364-f6f29400-f69a-11e9-9194-60de921dc359.png)

Theme looks the same when there is no PDF thumb, just only PDF file.

**Comment by Mates-K1** [comment]
And,,, on single img page thumb is not align to center for PDF.
![obrazek](https://user-images.githubusercontent.com/7648991/67514958-058e7a80-f69e-11e9-9c95-87198d771bcb.png)

**Comment by sbillard** [comment]
Ok, I can see the problem. The theme is not apparently willing to handle some allowed "images" such as PDF, and also PPS and TIFF. 

Personally, this theme is a real P***** of S*** in the way it manipulates things behind the scenes. You might want to contact the theme author about this problem, But I am not willing to spend the time to figure out what it is doing. I am inclined to remove support for the theme, it has taken too much of my time already.

**Comment by sbillard** [comment]
Well, I did find the issue. the theme still is a P_O_S, probably not tested by its author (since the issue was a missing <div> for these suffixes.

**Comment by Mates-K1** [comment]
I downloaded and instaled zp and latest zpBootstrap theme from author page and it works for PDFs. :/
So I dont know what I should to write to author. :(
