### ISSUE TITLE
Change American translation/flag for Canadian 

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1076]
Is there a way I can change the United States as a language setting (and flag) in locale and substitute it for Canada and its flag? If I change the flag image in locale it still says United States and it get's overwritten after each update.

**Comment by sbillard** [comment]
There are a couple of ticket threads relating to this: https://github.com/netPhotoGraphics/netPhotoGraphics/issues/765 and https://github.com/netPhotoGraphics/netPhotoGraphics/issues/825. You might also contact the author of these tickets to see what he is doing now.

**Comment by Elinth** [comment]
Thanks! As always you are a great help. 
A folder with: _en_CA_ with just a Canadian flag in it did the trick.

**Comment by sbillard** [comment]
but remember that the folder may be removed when you update. Perhaps nerdykit would share his plugin that restores the folder on setup.

**Comment by sbillard** [comment]
I see you have initiated contact to nerdykit for the plugin, so I will now close this ticket.
