### ISSUE TITLE
php 7.3 and nPG

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1086]
How does nPG like php 7.3 ?  I'm considering upgrading my server to raspbian buster which could involve php change up to 7.3 (currently on php 7.0)  I just want to be sure that this won't break nPG.  Thanks

NK

**Comment by sbillard** [comment]
My local install is on 7.3.1 and the netPhotoGraphics site is on 7.3.2

**Comment by nerdykit** [comment]
Thanks.  That's encouraging.
