### ISSUE TITLE
Site stopped working /installation is damaged

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1088]
Hi Stephen,

My site is stuck in the screen: Your installation configuration is damaged. How do I get to setup?

**Comment by Elinth** [comment]
Started working again

**Comment by sbillard** [comment]
From your logs"

>USER ERROR: "MySQLi Error: ( SELECT * FROM `_news_categories` ORDER by sort_order ) failed. MySQLi returned the error 1226: User '279773_testzp' has exceeded the 'max_questions' resource (current value: 150000)" in /srv/disk6/279773/www/linthorsthoman.nl/npgCore/functions-basic.php on line 19

I really do not see how you could exceed 1500000 requests in an hour, so I suspect that your server was having some kind of difficulty. 

You also have:

> EXCEPTION (0): "syntax error, unexpected '}', expecting end of file" in /srv/disk6/279773/www/linthorsthoman.nl/themes/LHkolom/search.php on line 123

So maybe there is a problem with your search.php script or maybe just another server hiccough.

**Comment by sbillard** [comment]
By the way, I have enabled the US english language on your site. If just Canadien is enabled it defaults to Dutch for me even though the Canadian language is selected.

**Comment by Elinth** [comment]
Strange that the Canadian language cannot be selected by itself. It looks a bit strange to have both US and CN languages on there. Is there another way to solve this?

**Comment by sbillard** [comment]
I would have to do some debugging on your site to understand what is happening. If you don't mind I will do that. It will involve setting some debugging options and seeing why Canadien English is not selected when I visit the site.

**Comment by Elinth** [comment]
Fine with me. The only thing is that the plugin for the Canadian flag does not work yet, so after an update it will dissapear. I tested this plugin once and it gave me loads of errors. Still have to respond to Kit about this.

**Comment by nerdykit** [comment]
> On Nov 5, 2019, at 10:44 AM, Elinth <notifications@github.com> wrote:
> 
> Fine with me. The only thing is that the plugin for the Canadian flag does not work yet, so after an update it will dissapear. I tested this plugin once and it gave me loads of errors. Still have to respond to Kit about this.
> 
> 

I  made a somewhat more robust version of the plugin and you can download it from

http://www.kitandjane.ca/files/en_CA%20fixer%20v2.zip

I found that on my last upgrade, that while the plugin was not marked with a red X during setup, that I still had to manually run it after setup by finding it in the list of plugins, clicking the checkbox and hitting the green “apply”.  Then my Canadian Flag re-appeared on Admin pages and my server's default locale is now matched by nPG.  This version uses USER_PLUGIN_SERVERPATH which I believe is a new variable and does not yet appear in the latest release version of nPG but it has been in the DEV versions for a week now.

Stephen says that all plugins are actually run during setup but that didn’t seem to be the case for this one.  I’ll watch during the next run of setup to see how it behaves.

Kit

**Comment by sbillard** [comment]
Well, I just tried your plugin (the modified one) and it put the Canadian flag in my locale folder afte running setup.

**Comment by sbillard** [comment]
@Elinth:

I think the problem with not having the en_US on your site is that my userid there had en_us attached to it. I removed that attachment and things worked. I'm not really sure what should be done if a user had a language assigned that is not allowed. Probably should not happen.

**Comment by nerdykit** [comment]
> On Nov 5, 2019, at 5:35 PM, Stephen <notifications@github.com> wrote:
> 
> Well, I just tried your plugin (the modified one) and it put the Canadian flag in my locale folder afte running setup.
> 
> 

Thanks.  I had other issues (caused by me) the last time I ran setup so it’s entirely possible that the behaviour I noticed was due to that.

Kit

**Comment by Elinth** [comment]
Thanks Kit!! I tried the modified one, that gave me no errors while running setup. Just waiting for the next update so I can check the behavior then. I'll let you know.

**Comment by sbillard** [comment]
I decided to make a more general plugin for handling non-standard language files.
[localePropagate.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3821541/localePropagate.zip)

if enabled, the plugin will copy any language file placed in its plugin folder into the locale folder. If disabled it will remove same files from the locale folder. (I needed that so I did not accidentally add these language files to the release package.)

As a bonus, I have created a "Canadian" English poEdit file so you guys can make a "proper" translation. (Currently the file is simply US English.) If you decide to do that translation, I will make it part of the official package.

**Comment by sbillard** [comment]
Should have mentioned that this requires the .11 DEV release!

**Comment by nerdykit** [comment]
> On Nov 7, 2019, at 12:34 PM, Stephen <notifications@github.com> wrote:
> 
> As a bonus, I have created a "Canadian" English poEdit file so you guys can make a "proper" translation. (Currently the file is simply US English.) If you decide to do that translation, I will make it part of the official package.
> 
> 

I’ll try to do a look through the strings to see if there’s any that require changing.  The biggest difference is that all the US   ‘or’ words are ‘our’ words for us.  i.e.: honour, colour, labour

If I ‘improve’ your en_CA file, I’ll send it to you.

Cheers

Kit

**Comment by nerdykit** [comment]
Where is the Canadian English poEdit file?  I’ll take a look at it and see if I can find anything that should be changed.

Kit

**Comment by sbillard** [comment]
It was SUPPOSED to be part of the zip, but I guess that did not happen.
[localePropagate.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3826762/localePropagate.zip)

**Comment by Elinth** [comment]
Brilliant Stephen! Your support is amazing as usual.

**Comment by Elinth** [comment]
Hi Stephen,

I think your plugin is not working fully yet. the CA flag dissapeared after I updated to the latest version. See my site.

**Comment by sbillard** [comment]
Can you tell me what the file structure of the locale/en_CA folder is? It looks like there is some issue with the flag image file. Also, just be sure you installed the plugin from the most recent localePropegate.zip file--the first version was missing the localePropegate folder and only had the PHP script.

**Comment by sbillard** [comment]
And also, remove the restoreCanadaFlag plugin as it may be interfering.

**Comment by Elinth** [comment]
/site.nl/plugins/localePropagate

**Comment by Elinth** [comment]
I deleted the other plugin, still no flag. This is the flag path
/site.nl/plugins/localePropagate/en_CA/flag.png

**Comment by Elinth** [comment]
That was the plugin, the flag of the en_CA locale folder is: /site.nl/npgCore/locale/en_CA/flag.png

**Comment by Elinth** [comment]
I deleted the en_CA folder and uploaded the old en_CA folder that I always ftp-ed in locale. It has the exact same flag but no LC_MESSAGES folder. This flag works. After this I deleted that en_CA folder and ran setup. It created a en_CA folder (with LC_MESSAGES) but the flag now did not work. The difference between these folders is the MESSAGES folder. When deleting that MESSAGES folder the flag still doesn't show.

**Comment by nerdykit** [comment]
May I please have the second version of the localePropegate plugin so that I can try it out.

Thanks

Kit

**Comment by sbillard** [comment]
@kit:
The link to the zip is in the message 10 above this one.

@Elinth:
There must be a corruption of the flag that was unziped from the file. What you are seeing is a broken image of the flag. I cannot say what is wrong, because I downloaded the zip and extracted the Canadian flag and it was not corrupt.

But anyway, since you have a flag that does work, just put it into the folder in place of the one that does not work.

**Comment by nerdykit** [comment]
I think I’ve made a “Canadianized” version of the core.po file that was essentially just in English.  I manually searched for all occurrences of color in the message string (not the message ID) and where appropriate (i.e.: not colorbox etc) I changed them to colour.  Along the way I found a sentence in german (which I converted back to English) (something about the slideshow and colorbox not being enabled on that page) at 34961and I also found some references to zp-extensions starting at 33725   I converted these to just “extensions” to reflect the current naming of that directory.

So now I’ve compiled it and put both in place in an en_CA directory in locale.

So far I can’t see any changes.  If I select the Canadian flag at the bottom of the admin pages, shouldn’t I see some changes?  A good place to look would be the theme options where color is mentioned.  All I’m seeing is still using color not colour.  When is the locale file read? Do I need to run setup again?

Let me know if you want to see the core.po file.

Kit

**Comment by nerdykit** [comment]
Just realised that the line numbers quoted above will only make sense if you open the core.po file in something like BBEdit because it treats every line of the file as one line,   a po editor will not.

NK

**Comment by sbillard** [comment]
You could try setting the "log language selection" option of the _debug_ plugin and see if the Canadien language is actually being selected. But, yes, you should see your changes if everything has gone correctly. Did you use poEdit to make the updates? Maybe look at the changes in poEdit and see if they "took".

**Comment by nerdykit** [comment]
> On Nov 14, 2019, at 9:15 AM, Stephen <notifications@github.com> wrote:
> 
> You could try setting the "log language selection" option of the debug plugin and see if the Canadien language is actually being selected. But, yes, you should see your changes if everything has gone correctly. Did you use poEdit to make the updates? Maybe look at the changes in poEdit and see if they "took".
> 
> 

I edited using a text editor but compiled with poedit.  Will look at my version of the file with poedit to see how it looks and get back to you.  Will also check log language selection.

NK

**Comment by nerdykit** [comment]
A new en_CA locale file is now at https://www.dropbox.com/s/s6frqtoo7j51d0o/en_CA.zip?dl=0

It probably isn't complete but I did some changes using poedit for Mac.  Very hard to find any places where I can see evidence of the changes.  The most common change was to turn many occurrences of color into colour (but not changing references to Colorbox for example).

NK

**Comment by sbillard** [comment]
Thanks. I'll get this into the next release. If you have future updates you can create a ticket and just attach a zipped version of the .po file. 

The process I suggest is that you use poEdit for making changes (if practical.) First do an "update from source" with the current development build. Then look for the "needs work" strings. Fix any you think need fixing and turn off the "needs work" on ones that are ok.
