### ISSUE TITLE
Removing deprecated "filter:alpha(opacity ="

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1090]
I think `filter:alpha(opacity =` could be deprecated and remove from code. It was for IE 8 and older.

**Comment by sbillard** [comment]
I will remove this from the theme CSS files. But there are multiple instances of it in things like the bootstrap minimized CSS. I will not remove it from any adopted scripts. That I will leave to the authors of the code.
