### ISSUE TITLE
Error message when selecting Development-->ENV

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1094]
Got this error when I selected Development-->ENV

WARNING: "getenv() expects at least 1 parameter, 0 given" in /mnt/usbdrive/webroot/public_html/gallery/npgCore/extensions/debug/admin_tab.php on line 170

**Comment by sbillard** [comment]
That is a strange error since the PHP manual specifies 

> If varname is omitted, all environment variables are returned as associative array

What version of PHP are you running? I have tried this on 7.3.1 (on a Windows system) and 7.3.2 (on a unix system) and do not get errors.

**Comment by nerdykit** [comment]
> On Nov 16, 2019, at 9:42 AM, Stephen <notifications@github.com> wrote:
> 
> That is a strange error since the PHP manual specifies
> 
> If varname is omitted, all environment variables are returned as associative array
> 
> What version of PHP are you running? I have tried this on 7.3.1 (on a Windows system) and 7.3.2 (on a unix system) and do not get errors.
> 
> 

I’m running PHP Version 7.0.33-0+deb9u5  which is the version that works with the Raspian version (Stretch) of Debian which runs my Raspberry Pi Linux Apache2 server.

A quick google shows that this changed to the assoc. array as of php7.1 so that is the issue.  I will have to look into upgrading my version of Raspbian or just the php part.  Something I’ve been loathe to do since it’s working right now and I hate to have to mess with it in case the whole thing falls over.

Cheers

NK

**Comment by sbillard** [comment]
Ok, I switched to 7.0.33 and did indeed get the error. I can't remember when this feature was implemented, but obviously not checked on older PHP versions.

**Comment by nerdykit** [comment]
> On Nov 16, 2019, at 2:11 PM, Stephen <notifications@github.com> wrote:
> 
> Ok, I switched to 7.0.33 and did indeed get the error. I can't remember when this feature was implemented, but obviously not checked on older PHP versions.

According to what I read, it was implemented with the php 7.1 version.  I’m in the process of backing up the server card before attempting to upgrade to Buster and a higher version of php.  Wish me luck!

NK

**Comment by sbillard** [comment]
I guess this was never tried on older PHP versions. I've added a test for this.

**Comment by nerdykit** [comment]
Resolved with an upgrade to php7.3  (took some work but I got there!) Thanks

NK
