### ISSUE TITLE
Link problem after renaming "News"

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1096]
I tried renaming the "News" part of ZenPage to "Blog / Events" the result was a 404 because (so I thought) the forward slash in my new title was upsetting the browser. So I changed the slash to "&" which didn't work either because the link wasn't an unbroken string of characters. My latest attempt was to use HTML entities but, to my surprise, these were _not_ translated into text (&nsbp; was printed on the screen as such, not as a space which I would expect).

I have no idea what the solution is, but it would be nice to be able to use more than one word to re-title the "News" section!

**Comment by sbillard** [comment]
You cannot use URL special characters as part of the name. These will be interpreted by your browser as separators for the URL You can try using html entities, e.g. &amp; for &

**Comment by sbillard** [comment]
I did try to use the htme entity. Seems not support at present. I am not sure how difficult it would be to change that.

**Comment by OldNick** [comment]
In the end I've settled on "Notes" for a title - you can fit all end of categories under that !!

**Comment by sbillard** [comment]
Great that you have a solution. I don't think I will attempt to allow the URL characters. It is really a can-of-worms problem.
