### ISSUE TITLE
Remove formatting in thumb description

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1098]
When I have an album I'd like to put images in the album description.
Say I have an album from a house in my family I'd like to include the images of the inhabitants.
Now, I have the album description also underneath the navigation thumbnails for the albums.
If I put the images of inhabitants in in my album description it is currently also displayed in the description below these thumbnails.
Is it possible to hide or not display the images for only the description below these album navigation thumbnails?

This is my current code:
`
if (getAlbumDesc()!='')
{echo shortenContent(getAlbumDesc(), 800, '....<small><a href="' . getAlbumURL() . '" title="' . gettext('Read more') .'" >' . gettext('Read more') . '</a></small>');}  ?>`

**Comment by Elinth** [comment]
Answer:
`if`` (getAlbumDesc()!='')
{echo shortenContent(getBare(getAlbumDesc()), 800, '....<small><a href="' . getAlbumURL() . '" title="' . gettext('Read more') .'" >' . gettext('Read more') . '</a></small>');}  ?>`

**Comment by Elinth** [comment]
Thanks for the support Stephen! (This answer thread came on a side discussion with Stephen..)

**Comment by Elinth** [comment]
Hi Stephen,

In News, Gallery Articles the images are displayed as well due to GALLERYARTICLEDESC. Can I change this as well in the getBare function?

**Comment by sbillard** [comment]
The getBare() function strips html tags off any string it is passed, so where the description is printed you can add the getBare() to do this. But this would apply to all articles unless you condition the getBare() on the author: uf ($article->getOwner()=='galleryArticles) { do the getbare() part } else { do the standard } 

This will, of course, take all the formatting out of the article. Is that what you really want?

**Comment by Elinth** [comment]
You are right, and I am doubting a bit if I should do this. However I'd like to test it. The reason I ask is because of excerpts on my gallery page. I do not have the need for the images in my album description to show up. I do want the album thumbnail with the hyperlink to the album to show up in the article. This is only for the automatically created gallery articles that are created when an album is new. Where can I change this code to test it?

**Comment by sbillard** [comment]
You can always edit the article that was created.

**Comment by Elinth** [comment]
Ok I will do that
