### ISSUE TITLE
How to use colorbox for images in the Album description?

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1099]
How Can I activate colorbox for images in the album description? (via TinyMCE).

**Comment by sbillard** [comment]
I am not sure exactly what you want to do here, there are several possibilities. But in any case you would have to edit the "source" and insert some styles and perhaps a "display:none" for each picture.

My general impression is that all this is coming from your showing descriptions with your thumbnails? Is that correct? You might want to consider displaying titles with the thumbnails--that is the normal use. The title would then be a condensed version of the description text. When you show the full image (such as in a gallery Article) then the imbedded images and all desired formatting would be shown.

**Comment by Elinth** [comment]
Hi Stephen,
Sorry, maybe my first explanation was a bit vague. 
I would like to use colorbox fo the images that I display in the description of the album, on the page where it is shown above the Gallerriffic gallery. These images can be added in the text via the TinyMCE of the album. The reason for this is that the images of my gallerific gallery are colorbox when you click on the Galleriffic gallery image. It would be consistent if the images in the description of my album are using colorbox as well when clicking on them.

**Comment by sbillard** [comment]
Well, of course you can always edit the html that TinyMCE creates to add the appropriate styles to e\implement colorbox. But there is no direct support, and cannot be--TinyMCE knows nothing go Colorbox.

**Comment by Elinth** [comment]
ok, thanks

**Comment by Elinth** [comment]
I just found out it is really, really simple to add colorbox in this field: 
<a class="colorbox" href='image.png'><img src="image.png"> </a>
That's all I needed to know. Thanks

**Comment by Elinth** [comment]
When using my above example in the description page with <a class="colorbox"....
It messes up the order of the colorbox image of the gallerific gallery. Meaning if I have two images with html in the description box, gallerific counts these as two images in the gallery. When I open the gallerific image with colorbox it is the third one that is displayed. Any ideas on this?

**Comment by sbillard** [comment]
Ardoise uses the class "colorbox" to launch a slideshow, that does not seem what you really want to do. You would want to use a different class. For example see how full images are displayed with colorbox. They use the class "fullimage" and have the following CSS to setup colorbox.
`$(".fullimage").colorbox({
--
  | maxWidth: "98%",
  | maxHeight: "98%",
  | photo: true,
  | close: 'close',
  | onComplete: function () {
  | $(window).resize(resizeColorBoxImage);
  | }
  | });
`

The link to launch the image is

`<a href="/dev/cache/gps/real_mg_0256_sFULL_copyright.jpg" title="Panorama matinal au Crêt de la Perdrix" class="fullimage">`

You would, of course, have to modify this to meet your needs.

**Comment by Elinth** [comment]
Thanks Stephen, 

I couldn't get your code to work but it did give me an understanding how it works. I managed to do this via copying the code from the gallery and altering that.
Many Thanks!!

**Comment by sbillard** [comment]
Glad you got it working. Copying code is a tried and true development technique.
