### ISSUE TITLE
Styling hover over thumbnails in  zpArdoise_printImageStatistic

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1100]
Hi Stephen,

Currently I am struggling a bit with something. Would you be so kind to help out?  I am  trying to style a hover on effect on zpArdoise_printImageStatistic. When I add the div: <div class="view view-first"> in the inc_print_image_statistic.php page when I hover it affects all thumbnails at the same time, while I need the hover for the items individually.  My thought was that I have to add this div in the function in the functions.php page. I just do not know where. Could you help me out?

Many Thanks!

**Comment by sbillard** [comment]
Depending on which options you have set inc_print_image_statistic will call either _zpArdoise_printRandomImages_ or _zpArdoise_printImageStatistic_. Each of these has a loop that prints out each image thumb.

**Comment by Elinth** [comment]
It is  zpArdoise_printImageStatistic. I was looking and trying with that. I am just not sure how I can I put the div in.

**Comment by sbillard** [comment]
What are you adding with the DIV? Just a class name for the hoover? If so you could simply add it as a class on the `<li>` element. Otherwise you can add the DIV after the `<li>` element.

**Comment by Elinth** [comment]
Just a class name I use with album_thumb and image_thumbs too. I tried both your options, Unfortunately they did not do the trick.

**Comment by Elinth** [comment]
I preferred this one: Otherwise you can add the DIV after the <li> element and close the DIV before the </li> element. But it gave me an error.

**Comment by Elinth** [comment]
fixed it... typo I used " instead of '
