### ISSUE TITLE
Setup-initial screen incomplete

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1103]
Not sure if this is an issue or the expected behavior.  When I do an upgrade via the button on the main admin page, all proceeds normally but the page where normally I used to get a long series of ticks that various consistency tests have been passed, now that page is truncated after about two items.  Typically the last report I see is that my mysql version is lower than the recommended version.  The next page of install goes as usual, mod-rewrite check, themes check, and plugins check.  But the middle page is cut short.  If, after upgrade I re-run setup, I get the full middle page list of various consistency checks ie: robots.txt, etc. etc.  but not when I unpack and run an upgrade via the button the main admin page when a new release is detected.

Thanks

NK

**Comment by sbillard** [comment]
This is normal behavior when Setup is run in "autorun"mode which is how it is run from the install script. You should be able to see ".../npgCore/setup/index.php?autorun=admin" in the browser address bar.

**Comment by nerdykit** [comment]
OK, thanks for clarifying.  Will close.
