### ISSUE TITLE
password reset  doesn't work for me

### ISSUE THREAD

**Issue by Jens2014** [netPhotoGraphics/netPhotoGraphics#1108]
After requesting a password request the email will be send with the following link:
https://server.domainl/npgCore/admin-tabs/users.php?ticket=ef&user
(userName starting from 3rd character).
After clicking on the link I will be directed to the regular login form. In any case - the ticket value is 'ef'' and the first two characters of the username are cutted of. As a result, the password reset will not work, and I am only will be redirected to the regular logon screen.
Using PH 7.3 and the latest nPG version.

**Comment by sbillard** [comment]
are there any special characters in the user name?

**Comment by Jens2014** [comment]
no, just letters, capitalized and non-capitalized.

**Comment by sbillard** [comment]
I did find a problem with the ticket code. But not with the missing user name characters. Perhaps the ticket issue did cause that. Can you try the above fix to see it it resolves the issue?

**Comment by Jens2014** [comment]
Tested the fix and it corrected the ticket part. Regarding the username it still keeps the same: first two charackters are missing in the URL and I will be directed to the default logon page.
I tried to manually add the first two characters in the URL - without success.

**Comment by Jens2014** [comment]
Interestingly the correct username is part of the text part in the email body.

**Comment by sbillard** [comment]
Did you click on the link or cut & paste it? What shows up in the browser address bar?

**Comment by Jens2014** [comment]
I did both and the result was the same. I was redirected to
`[...]/npgCore/admin.php?from=/npgCore/admin-tabs/users.php` (HTTP 302).
The same with manually corrected user name in the URL. I was redirected to the login page.

Regarding the missing characters I have some additional information.
Everything seems to be with the message string until it is handed over to npgFilters::apply.
And here I am getting lost with my skills.

The final result in the email looks exactly like this:
`
<div id=eader" style=idth: 600px;background-color: whiteSmoke; margin: auto; padding: 50px;">
	<span id=ogo">
		<a  href=ttps://jekophoto.net" target=blank"><img src=ttps://jekophoto.net/npgCore/images/admin-logo.png" alt=etPhotoGraphics" height=8"></a>
	</span>
	
	<div id=mailbody" style=adding: 10px; margin: 20px;"><p>You are receiving this e-mail because of a password reset request on your gallery from a user who tried to log in as testuser.</p><p>To reset your Admin passwords visit: https://jekophoto.net/npgCore/admin-tabs/users.php?ticket!977cf67a91d57e887d10ff31ba4ea3d7df08de2325e5db095cb5bf4a4e&user=stuser</p><p>If you do not wish to reset your passwords just ignore this message. This ticket will automatically expire in 3 days.</p></div>

	<div id=ooter" style=adding-top: 15px; padding-left: 5em;">
		--The Administrator
	</div>
</div>`

Everytime after the equal sign the first character ist cutted off after handing over to npgFilters::apply. The only exception is the username, here the first two chars get lost.
The coosen username in this example is **testuser**.

**Comment by sbillard** [comment]
Which mail handler do you have enabled? From your description it would seem that the mail handler is doing something wrong.

**Comment by Jens2014** [comment]
It is a default installation without modification to mail handler. Where can I see which mail handler is enabled and used?

**Comment by sbillard** [comment]
Plugins/Mail will have one plugin enabled, but if you have not done any configuring it must be the simple_sendmail plugin.

**Comment by sbillard** [comment]
So, I looked at simple_sendmail. It does not alter the $message parameter, simply passes it on to the PHP mail() function. 

I have just updated my WEB server based test site (which can use simple_sendmail) and tried a password reset. Everything works as expected.

 This is with the latest DEV build which has some cosmetic changes that "should not" make a difference, but you might try it.

**Comment by Jens2014** [comment]
Thanks for pointing it out. 

For my final test I added 3 more lines of code in functions.php directly below line the handover to npgFilters::apply in line 3083:
```
$header[] = 'MIME-Version: 1.0';
$header[] = 'Content-type: text/html; charset=utf-8';
mail('[email address]', gettext("The information you requested"), $msg, implode("\r\n", $header));
```
Here is, what I experience:

The native called mail() function delivers the excact content of $msg - what I can see in the received email. No missing characters.

The mail precessed by npgFilters::apply has the symptom of the missing characters.

I am running PHP version 7.3.11-nmm1

Do you have any ideas?

**Comment by sbillard** [comment]
Did you verify that the mail handler is simple_sendmail? If so please add some code to that plugin to place the message passed into the log. 

After line 28 in `simple_sendmail` insert `debugLog($message);`
Replace your code in `functions.php` with `debugLog($message);`
(I note your post above uses "$msg" not "$message" which is what the `mail()` function code is using. I assume that this is a typo?

This will tell us what the value is before the apply and what the mail handler received.

**Comment by Jens2014** [comment]
Sorry I forgot to give you the answer before...
Yes, I am using simple sendmail. And the code snippet has the typo, as you mentioned.
Both times in the DEBUG log $message contains the right content.

Heading to simple_sendmail.php was the absolut right direction.
`$headers['content'] = "Content-Transfer-Encoding: quoted-printable";` causes the issue in my case.
After commenting it out everything works perfect for my installation :)

**Comment by sbillard** [comment]
Good news. Can you add to simple_sendmail after line 46
`$message = quoted_printable_encode($message);`

Of course, please leave the "content" header coed in place.

This was what I speculated was the issue. I have tried this fix and it works for me, but as we know that does not mean it will work for you.

**Comment by Jens2014** [comment]
Absolutely, changing the "content" headerwas just for debugging.

Your proposed additional line works perfect for me, too.

Thank you so much for your support!

**Comment by sbillard** [comment]
Thanks for the confirmation. This change will be released shortly.
