### ISSUE TITLE
Extract throws error message

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1111]
I'm trying to install 2.00.04.02 locally and getting this message

> Extracting netPhotoGraphics 2.00.04.02 files
> Error:
> reading archive failed: File not found
> #0 {main}

I also tried using source and that gave me an error that the script was trying to follow links that could not be resolved.

Could explain why trying to install a production version online left me with a blank page...

**Comment by sbillard** [comment]
I have just tried installing from the "install" button" for the release with no issues.

Please describe the exact steps you did for the install. The error sounds like a corrupt file.

**Comment by OldNick** [comment]
I did as instructed - unzipped the file and changed the name etc.
With the source files I unzipped, copied them and navigated to /core/setup... 

It's what I did on the remote server too, but there it just said "extracting" and then nothing.

I wonder if it's not something to do with permissions - I run a setup in Linux where my everyday account has no privileges, which can get complicated as linux is tetchy with permissions and I already have the problem that - try as I might - the system won't recognise my ordinary user as being a member of the www-data group - and perhaps why the remote server isn't too happy.

I'll go and look at the logs (on the admin account)

**Comment by OldNick** [comment]
Logs.

> 09/01/9858 01:37	65	[client 127.0.0.1:47474] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /media/Data/webby/webdev/public_html/net-22/extract.php on line 30

> 09/01/9859 01:37	65	[client 127.0.0.1:47474] PHP Warning:  ZipArchive::close(): Invalid or uninitialized Zip object in /media/Data/webby/webdev/public_html/net-22/extract.php on line 87
This for the extract.php method

and this for using the source files

> 09/01/2020 01:26	127.0.0.1	-	-	301 Moved Permanently	566 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /net-2 HTTP/1.1	-
> 09/01/2020 01:26	127.0.0.1	-	-	200 OK	748 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /net-2/ HTTP/1.1	-
> 09/01/2020 01:26	127.0.0.1	-	-	200 OK	509 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /icons/folder.gif HTTP/1.1	http://localhost/net-2/
> 09/01/2020 01:26	127.0.0.1	-	-	200 OK	431 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /icons/blank.gif HTTP/1.1	http://localhost/net-2/
> 09/01/2020 01:26	127.0.0.1	-	-	200 OK	500 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /icons/back.gif HTTP/1.1	http://localhost/net-2/
> 09/01/2020 01:26	127.0.0.1	-	-	404 Not Found	487 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /favicon.ico HTTP/1.1	-
> 09/01/2020 01:26	127.0.0.1	-	-	200 OK	203 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /net-2/npgCore/ HTTP/1.1	http://localhost/net-2/
> 09/01/2020 01:26	127.0.0.1	-	-	404 Not Found	487 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /favicon.ico HTTP/1.1	-
> 09/01/2020 01:27	127.0.0.1	-	-	301 Moved Permanently	594 B	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /net-2/npgCore/setup HTTP/1.1	-
> 09/01/2020 01:27	127.0.0.1	-	-	302 Found	1,3 KiB	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0	GET /net-2/npgCore/setup/ HTTP/1.1	

There may be other info in the gzipped back numbers - I just looked at what was easily available

**Comment by OldNick** [comment]
You'll be relieved to hear that, locally at any rate, the problem _was_ permissions - I changed the folder to 777 and added www-data as an extra user (which is probably overkill but it worked).

What should the permissions be on a remote server - from memory uploading files seems to default to 755
It would be a useful thing to put in the documentation.

**Comment by sbillard** [comment]
From the error message it is definitely a permissions issue. The script is copying the netPhotoGraphics archive from the extract.php code file to a regular ZIP file so it can extract it. The error comes because the script was unable to read the code file.

As to the permissions, that is a difficult question to answer since they may vary. Usually the problem is caused by the file being created under a different user code than the script is being run under. That is most likely the case here given your description. It is often the case that PHP runs under a different user than FTP. Folder permissions of 755 are the desired as they do not allow any one but the owner to write to the folder. But if the user codes are different then 777 would be necessary. 

Is this an existing installation that you are upgrading? If so there should have been an install button. Have you tried that? That would make PHP the owner of the extract file so there would be only one user code involved.

**Comment by OldNick** [comment]
The local one was getting out of the "closing tag" problem - I tried importing a database backup, but it threw a slew of error messages - so I've gone through page by page, checking and copying.

I tried the remote one again - it extracted well enough - and then died without any message even after I'd changed all permissions to 777 and went to .../npgCore/setup/index.php. I suspect the software versions aren't high enough to go any further. I'll try somewhere else.

**Comment by sbillard** [comment]
Unless the script cannot start at all, it should give you an indication of too low a software level.

Also, your server should have PHP and/or Apache error logs that may provide some clues.

**Comment by OldNick** [comment]
I think it's a version thing - it's a non-profit hosting service I signed up to a while ago, and they obviously haven't kept up to date (haven't been able to find logs). If the organisers and their chums all have scripts that work under 5.0, they're not going to make the effort to upgrade.
I don't think it's a problem with Netphotographics - all my development has been using a LAMP stack which comes with PHP 7.2 or something like that - it didn't cross my mind that people didn't update...!

**Comment by sbillard** [comment]
Ok, I'll close this ticket, then. As for the hosting, they really are exposing themselves to security issues if they are still running PHP 5 series.
