### ISSUE TITLE
More installation headaches

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1115]
Sorry - it's me again...
I found a host with PHP 7.3, which is good but I tried uploading extract.php.bin and it was simply wiped from the server as was extract.php (which I renamed and uploaded afterwards) I think they must have a very robust malware screening system in place.
So I had to upload the source files... and the change the permissions etc so far so good _finally_ it installed.
The first problem I have is logging in to admin - I can get to the admin.php and sign in on the login form and then I get a 404 for the link "/npg/admin.htm". The .htaccess file has not been written into during the install - perhaps because one existed already (necessary to turn off the "quotes" module and enable php errors).
Will it work if I copy the one on my local install - I note that there is a line at the bottom

> RewriteBase  /net-22/

which reflects the fact it's in a directory. It's now int the root directory (htdocs) so would the line read "rewrite rule /"... actually I've jusy been looking at rewrite.txt and I don't thing that will be enough.

And now the next problem - after a pause, I went back to the site and found the following message writ large across the home page 

> USER ERROR: "MySQLi Error: ( CREATE TEMPORARY TABLE IF NOT EXISTS taglist ( `tagid` int(11) UNSIGNED NOT NULL, `type` tinytext, `objectid` int(11) UNSIGNED NOT NULL, KEY (tagid), KEY (objectid) ) CHARACTER SET utf8 COLLATE utf8_unicode_ci ) failed. MySQLi returned the error 1044: Access denied for user 'b9_25065117'@'192.168.%' to database 'b9_25065117_netphoto'" in /home/vol2_5/byethost9.com/b9_25065117/htdocs/npgCore/functions-basic.php on line 19 

I dare say this is some sort of permissions issue again. I have no idea what it means, except, for some reason I'm being shut out of my database!

Help please!

**Comment by sbillard** [comment]
The critical part of the .htaccess file is:
`<IfModule mod_rewrite.c>
  RewriteEngine On

  RewriteBase /

  RewriteCond %{REQUEST_FILENAME} -f [OR]
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteRule ^.*$ - [L]

  RewriteRule ^.*/?$                        index.php [L,QSA]

</IfModule>`

What is needed is for it to redirect anything not a file to the root index.php file. But I would contact the provider. Seems pretty draconian to be removing files from your site that you FTP there. Also, it should be possible for the setup script to overwrite the existing .htaccess file. Again, some kind of permissions issue that you should take up with the hosting service.

You should be able to turn off the quotes module and enable PHP errors in the PHP.ini file if your host site allows access to it.

Do you have access to a MySQL control panel? The user you use for the database should have "all privileges". This temporary table is used by "visitors", so you (as administrator) would not get the error.

**Comment by OldNick** [comment]
I just amended the .htaccess with the code above and I get the following message...

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> Please contact the server administrator at root@foo.tld to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log.
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

I am given a truncated version of phpmyadmin which does not seem to allow permission changes.

I'm on an introductory offer to the hosting service so their idea is that I should "upgrade" - mine is that if the site can't work at basic level, then I'll be moving along - I could, curiously, go for an automatic install of Zenphoto, but as it doesn't seem to be regularly maintained, lacks features, and the HTML is from the dark ages, I'm not terribly interested

Now off to prepare a support ticket

**Comment by sbillard** [comment]
I use POWWEB for hosting my sites. Not sure how competitive its pricing is now, but it is good enough that I don't want to go through the process of moving hosts. You could also ask on the nPG forum what hosting sites people are using. 

To be honest, I've never heard of these errors (other than file permissions) before your reports. They cannot be that common.

**Comment by OldNick** [comment]
I'm on a v. small budget for this (ie zero!) and I'm in Europe and I don't want my data in the US.

I did notice in rewrite.txt in setup that there is a more complex version of rewrite rules available - I'm just not sure how to apply it - does setup simply copy the text or parse it and supply variables?

Still writing the support ticket...

**Comment by sbillard** [comment]
Setup copies the text from the "htaccess" file and changes the rewritebase as appropriate.  The "rewrite.txt" file is for nPG processing and you do not need pay any attention to it.  (nPG does the a"actual" rewrite processing internally. All .htaccess needs to do is redirect to the index.php script.) You could manually copy "htaccess", change the "rewritebase"and add the PHP stuff to the result. For a root install the rewrite base should be "/".

**Comment by OldNick** [comment]
I'll have another look
...later

Answer to the SQL question - "temp tables are not allowed in your plan..."

I don't actually use tags, so maybe _if_ I can get into admin, I can turn them off!

**Comment by OldNick** [comment]
I looked at the .htaccess again - I'd made an error, so I copied your extract above. And we're back to 404's.
Does index.php make use of a specific PHP module to be able to redirect? In my PHPmyinfo() there's a slew of modules or commands disabled and it might be among them.
(and, no doubt to enable it means an upgrade...)

**Comment by sbillard** [comment]
Have you checked that the mod_rewrite option is set? I am not aware that the rewrite needs anything more than basic PHP. If a module were missing presumably the functions it provides would also be missing so using them would throw an error. 

You could put some debugging output code into the npgCore`index.php` script to see if it gets executed. Line 45 is  where the internal rewrite processing is invoked. If you are not getting there, there is still a problem with the `.htaccess`.

You can turn off tags using the optionalobjectFields plugin. If you are not using any of the fields it provides simply disable it. If you need some, then you would need to make a custom version of the plugin. look for `'name' => 'tags',` in the arrays in the fields() method. Remove any array which has that entry. 

Also turn off any plugin that provides additional support for tags.

**Comment by OldNick** [comment]
I've been looking at a phpInfo() script I put in the document root and I found this entry

> **Virtual Directory Support** | disabled

All this is way above my paygrade, but could this be at the root of the 404's ? If index.php is the only file that exists in a precise location and /pages, /albums etc. are created by index.php, I would think they're pretty virtual (and disabled)

**Comment by sbillard** [comment]
I had not heard of this option before. But my research tells me that its setting "should" not matter. It is enabled in my localhost test site and disabled on my Web Server sites. I think the key bit of information is whether the index.php script is invoked on a rewrite. 

You should be able to delete the root `.htaccess` file and run `setup`. That should offer to create the file. Let it and then at least the file should be created properly.

**Comment by OldNick** [comment]
Actually, I've given up - I've found a plan with servers in France (at least, so they say - read the small print and all sort of stuff is being kept in the US) and installation went _as it should!_

What the other lot were up to, we'll never know - but I ran out of patience.

**Comment by sbillard** [comment]
Glad your site is up. I'll close this ticket, then, with the resolution "WTF".
