### ISSUE TITLE
LDAP plugin is not loaded

### ISSUE THREAD

**Issue by mazdader** [netPhotoGraphics/netPhotoGraphics#1116]
I'm updating from  ZenPhoto20 v1.4.1.6 to netPhotoGraphics v2.00.04. It seems that in the latest version (I believe, in v1.09.05.00 it still was working) the LDAP plugin is not loaded by PHP code. The section
```php
if (!(function_exists('ldap_connect') || class_exists('_Authority'))) {
	require_once(CORE_SERVERPATH . PLUGIN_FOLDER . '/LDAP_auth/LDAP auth.php');
}
```
will never load _LDAP auth.php_ because __Authority_ already exists.

So in general, in my setup I see that after the upgrade, with enabled LDAP plugin, the site does not make any connections to my LDAP server.

**Comment by sbillard** [comment]
I have created a Development build with what I believe are the fixes to this (and the implementation of the OU option.) I can do only rudimentary testing since I do not have a real LDAP environment. Please verify that things work. You can get the build from https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.04.04.06.zip

**Comment by mazdader** [comment]
Thank you for so quick response!

I tried the latest build and here are a few things that I observed (some are my specific LDAP server schema configuration):

1. Function `ldapUser` still has hardcoded `ou=Users,`.
1. In our setup, groups are located under different OU. So all users are under `ou=addressbook,dc=example,dc=com` and all groups are under `ou=Roles,ou=Groups,dc=example,dc=com`.
1. Membership attribute in our case and in many installations is `member`, not `memberUid`. It would be nice to have it configurable.
1. In our LDAP setup, users are added to groups by CN.
1. In many setups a service account may be used to access LDAP. The account may be in different OU (not along with regular users).
1. Probably a typo in variable name - `LDAP_REAER_PASS`.

So that's what I have done to make it work in my setup:
```php
	static function getNPGGroups($ad, $user, $usercn) {
	    $realdn = "cn=" .  $usercn . ",ou=addressbook," . LDAP_BASEDN;
		global $_LDAPGroupMap;
		$groups = array();
		foreach ($_LDAPGroupMap as $NPGgroup => $LDAPgroup) {
			if (!empty($LDAPgroup)) {
				$group = self::ldapSingle($ad, '(cn=' . $LDAPgroup . ')', 'ou=Roles,ou=Groups,' . LDAP_BASEDN, array('member'));
				if ($group) {
					$group = array_change_key_case($group, CASE_LOWER);
					$members = $group['member'];
					unset($members['count']);
					$isMember = in_array($realdn, $members, true);
					if ($isMember) {
						$groups[] = $NPGgroup;
					}
				}
			}
		}
		return $groups;
	}
```

```php
	static function ldapReader($ad) {
		if (LDAP_READER_USER) {
			if (!@ldap_bind($ad, LDAP_READER_USER, LDAP_REAER_PASS)) {
				debugLog('LDAP reader authorization failed.');
			}
		}
	}
```

**Comment by sbillard** [comment]
I'll take your code. I think you know more about this than I.

**Comment by sbillard** [comment]
So, I have had a chance to understand your changes.  I have (i believe) made the membership attribute configurable. Are there other possible choices than member and memberuid?

for the line `$group = self::ldapSingle($ad, '(cn=' . $LDAPgroup . ')', 'ou=Roles,ou=Groups,' . LDAP_BASEDN, array('LDAP_MEMBERSHIP_ATTRIBUTE'));` should the "ou" parameters also be configurable?

Current state of the changes are at https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.04.04.07.zip 

Again, these are not tested with a real LDAP server.

**Comment by sbillard** [comment]
I have made some more changes. Your code did not work with my LDAP surrogate so I presume it would have been a problem for similarly configured servers.

There now is an option for the OU of the READER user. The plugin does presume you can use the UID for the reader. Is that going to be a problem?

These changer are in https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.04.04.09.zip
