### ISSUE TITLE
Netphotographics.com - Update to latest version of phpbb 3.3

### ISSUE THREAD

**Issue by zorodimanche** [netPhotoGraphics/netPhotoGraphics#1125]
phpBB 3.3 Proteus Feature Release Published : https://www.phpbb.com/community/viewtopic.php?t=2534541

**Comment by sbillard** [comment]
This ticket really belongs on the "Website" repository as it has to do with, well, the website, not the netPhotoGraphics code. I don't think there is an easy way to move the ticket, so I will deal with it here.

**Comment by sbillard** [comment]
Updated, but with some difficulties!
