### ISSUE TITLE
Error in sitemap extended extension

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1127]
Me again I'm afraid
I've activated the plugin and tried to create a sitemap (through the Overview > Sitemap page) and I get the following error :
`EXCEPTION (0): "Call to undefined method sitemap::getLastChangeDate()" in /home/uoblpqeq/public_html/npgCore/extensions/sitemap-extended.php on line 296 `

**Comment by OldNick** [comment]
I'm afraid there's still an error - and it doesn't work automatically. You can use it manually. I can't get the error because I can't access the file (the subject of another issue)

**Comment by sbillard** [comment]
It will work if you select "mtime' as the date options. I have a correction for the other formats in the DEV stream.
