### ISSUE TITLE
Some images populated by galleryArticles are not working in news feed

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1134]
Somehow I have several images in News now show a broken image, you can see this in my news excerpts. These image thumbs somehow seem to have broken, while they were previously there. Unfortunately this is not the first time it happened. I have manually inputted the images a couple of times, but the problem seems to come back. Does this have to do with image caching? A permanent solution seems a better direction, as this issue keeps coming back and I have to go through all the news articles. I think these images that are broken are automatically populated by the galleryArticles plugin.

**Comment by Elinth** [comment]
Also I have one image that is the image for a video. It shows as a broken image in the album.php page. When I ftp this image, it still shows as a broken image.  I will email you the link

**Comment by sbillard** [comment]
I will probably have to review your cache to understand this problem. Can you e-mail me FTP credentials so I can look at it? Just looking at the links does not help. They are to images which should be in the cache, but perhaps are not for some reason. Or they may be broken images. Hard to tell.

**Comment by sbillard** [comment]
Thank you for the access to the site. It was quite helpful in diagnosing this issue. I believe I have a fix. You can try the current development release https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

There are some folders in your cache files that were created by the bug. You can see them as the folder has a name that looks like an image. These can be deleted (but presumably will not cause any issues if left.)

**Comment by Elinth** [comment]
Thanks Stephen, Do I have to redo the images manually?

**Comment by Elinth** [comment]
Thanks, deletiong those folders made them appear again.
