### ISSUE TITLE
Internal server error after update

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1135]
I updated through the admin panel and now the site is inaccessible - it times out, with a blank page.

It's the second time after an update - last time I tried to find the error files and got an internal server error and the info that it had "dropped core files" - this turned out to be the error logs (although maybe others). 
However, last time, having coughed up it's fur ball, things started up again. This time nothing - just "500 internal server error."
What happened in both cases was that after the update and one or two things in Admin, I logged out - to the home page. The trouble starts the moment you try to navigate the site.
The question is, what is the procedure to get it working again?

**Comment by sbillard** [comment]
What version did you update to? What did you do to resolve the issue the prior time?

Server errors are often permissions issues, but I have never seen that with the install through the admin tab. You say there is nothing in the PHP error logs on the server? You can also check your apache access logs to see what was trying to be accessed. Also clear any caches you can find.

**Comment by OldNick** [comment]
The first time it sorted itself (or seemed to) I tried to access the error logs through c-panel - got the 500 error message, together with this `No response from subprocess ( (cpanel)): The subprocess reported error number 72,057,594,037,927,935 when it ended. The process dumped a core file.`
The "core file", it turned out, was the error log...
The first time things suddenly came back to normal.

This is what happened yesterday as well but it hasn't righted itself on its own. So there will be no logs to find out what went wrong.

Starting with the easy bit - permissions. public_html is 750; folders inside are 755 and files are 644. The only thing is that I'd locked down .htaccess to 444

**Comment by sbillard** [comment]
So you cannot access your server cpanel error logs at this point? That would certainly be something you should address with the hosting service as it has nothing to do with netPhotoGraphics. Can you access your site via FTP? you could then look at the netPhotoGraphics debug log (if it exists) to see what it says. It is in the npgData folder.

**Comment by OldNick** [comment]
I don't know why, but there isn't an error log in npgData. 
There won't be any logs on the server either - they got wiped the first time this happened and I presume they've been wiped again. I tried to find out what the error numbers (in quote above) meant but without any luck.
I suppose I'm going to have to start again - or could I just wipe a config file and go to setup?

**Comment by sbillard** [comment]
If there are no mPG logs and there are no server logs, there is not really much that can be done to diagnose the problem. Anyway, server logs have nothing to do with netPhotoGraphics. If they are being wiped it is due to some server issue. Maybe nPG can trigger it, but we have no hope of figuring out how without some data.

Did you manage to protect your setup scripts? If so, you can change their suffix in FTP. If not you can just run setup directly: host/npgCore/setup/index.php. But I do not see how that can fix anything.

**Comment by OldNick** [comment]
I've sent the hosts a support ticket - they changed servers a week ago and I think it could be something to do with that. Apparently this also involved changing the nameservers as well, but as I registered the domain through them, that's their responsibility.
Curiously, I managed to get in using a VPN for a couple of pages, but long enough to discover that the script being used was _not_ the the stuff I'd uploaded.
I wonder if they haven't put my stuff in some sort of cloud solution, which they would get around to sometime, and changing things has upset things.

**Comment by sbillard** [comment]
Well good luck. I will leave this open in case you get enough information to know what went wrong. It might help someone else.

**Comment by OldNick** [comment]
One thing I've just found is the security log from the last time this happened
`2020-02-09 18:59:13	91.174.124.248	Admin login	NickSchwitt	Nick Kai Nielsen	Success	administrators (7)
2020-02-09 19:27:54	91.174.124.248	404			<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-09 19:27:54	91.174.124.248	404			<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-09 19:27:54	91.174.124.248	404			<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-10 00:32:11	212.92.107.85	404			<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:42:17	91.174.124.248	Admin login	NickSchwitt	Nick Kai Nielsen	Success	administrators (7)
2020-02-11 09:47:32	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:47:35	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:01	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:02	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:04	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:31	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:32	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended
2020-02-11 09:48:36	91.174.124.248	404	NickSchwitt	Nick Kai Nielsen	<span class="logwarning">Blocked</span>	ipBlocker	Suspended`

It looks as though th IP blocker went rogue and decided I was an invader...

**Comment by OldNick** [comment]
The interesting thing is that the log seems to have stopped working after the server move...

**Comment by sbillard** [comment]
Given that it happens only after an upgrade I would suspect some kind of server caching. You "request" a new page but get delivered the cached old content or even a failure if the cache reference fails. (Also explains why you don't see the script changes right away.)

My hosted server does this. It makes testing changes impractical there. But it is much more convenient to develop the changes on my local WAMP installation. The changes  then just need final verification on the host based server.

**Comment by OldNick** [comment]
If they are server caching, it's new. I do all my development locally - except mine's a LAMP stack - and upload what's new. Their caching seems to be very long - over 24hrs which seems ludicrous.

From what you say, it suggests that because their caching algorithm doesn't take into account changes in the files, you get repeated 404's (as in the log file) because the script will keep trying, I'll get shut out because the ip blocker interprets it as a denial of service and the page will time out...

**Comment by OldNick** [comment]
A further thought - would it help to turn off ip blocking before an upgrade, wait for the caching algorithm to catch up and then re-enable the blocking?

Or - if one has a strong password and a weird username, as I do - is it unnecessary?

**Comment by sbillard** [comment]
From the security log you showed it does not appear that you are getting much real denial of service attacks, so probably you don't need the ipBlocker at all. But at least is seems like it would be good to turn it off before an  upgrade. 

The security log will show failed login attempts anyway (so long as you have left that option enabled.) So you can see if anyone is trying to hack in.

**Comment by OldNick** [comment]
Small thought : would it be possible to white list admin ips?

Still doing battle with the so-called "support" - whose principle objective seems to be gaslighting me into thinking I'm a complete idiot and my system doesn't work.

**Comment by sbillard** [comment]
Right now the ipBlocker ip list is either a black list or an "inverted" black list--that is only those IPs are allowed. I think the plugin could be extended for it to be a white list. But I really do not think that makes much sense in general. You would basically be saying "allow attacks from these IP ranges."

I think you would be better off just not using the plugin unless you think your site is being attacked. Things to look for that indicate attacks are the repeated failed login attempts in quick succession and repeated 404 errors in quick succession. The security log can show the former and setting the debug plugin's log  404 error processing can show you the latter.

If you have to use ipBlocker, turn it off for your upgrades.

Sorry for your problems with our server support. Seems to me that they should be able to understand that you cannot access their cPanel and that cannot be an issue with your website software. But then, I am probably preaching to the choir.

**Comment by sbillard** [comment]
I forgot about a different plugin you might consider using instead of ipBlocker--accessThereshold. It simply monitors traffic and if there is "excessive" requests from an IP (or subdomain) it blocks the requests. 

You configure its "sensitivity" and you  also specify your IP which is then not subject to the monitoring.

**Comment by OldNick** [comment]
The final upshot was I quit the webhost. It turned out they were resellers (research I should have done before) and had no control over the server - their "support" didn't go further than what anyone else could do in cPanel.
They'd botched the change of servers - I was, in fact loading files onto the _old_ space, they hadn't thought of telling me the ftp address had changed.

Moral : thoroughly research your web host before signing up... check they're in full control of their equipment.
