### ISSUE TITLE
Styling table in TinyMCE not possible

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1140]
Question 1. 
When I write this in the source code of the editor, once I save it the styling dissapears and the text remains. Is this normal behavior?

`<table style="width:100%;background-color:yellow">`
```
  <tr>
  <th>
   
   test content
  </tr></th>

  </tr>
`</table>`
```

Question two: Is there a way you can incorporate tinymce advanced? It incorporates 14 tinyMCE plugins. I probably already know the answer maybe no, as it is a wordpress plugin, but I can always ask as it is the best plugin ever made. This page says also something about integrations.
https://www.tiny.cloud/docs/integrations/wordpress/#tinymceadvanced

**Comment by Elinth** [comment]
Does this table plugin have to do with it? https://www.tiny.cloud/docs/plugins/table/

**Comment by Elinth** [comment]
I just saw this.. https://go.tiny.cloud/advanced-code-editor/

**Comment by sbillard** [comment]
I don't know why the table did not work. I will have to investigate.

Plugins do exist in the tinyMCE we incorporate. I don't know which Wordpress uses and of course how it uses them are unique to it. TinyMCE also has premium plugins. I have not investigated them. But at least there would need to be configuration for them added and some way of keeping setup from removing them. Seems like a good thing to look into.

**Comment by Elinth** [comment]
Thanks for being open to that option and to look into it. It is such a amazing version of TinyMCE.

**Comment by Elinth** [comment]
Thanks!

**Comment by sbillard** [comment]
The "table" plugin is included with nPG. You can get it if you select the "FULL" text editor configuration

**Comment by Elinth** [comment]
Ah, it is on full. then the only issue is the styling thingie..

**Comment by sbillard** [comment]
You could probably put a div style around the table.

**Comment by sbillard** [comment]
I have done just this: I put `<div style="color:red;">...</div>` around the table using the tinyMce source editor. It worked just fine.
