### ISSUE TITLE
Update ZpBootstrap

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/netPhotoGraphics#1143]
Stephen can you update zpBootstrap theme because there are many changes : https://github.com/vincent3569/zpBootstrap/commits/master

**Comment by sbillard** [comment]
I will work on it. If there are a lot of changes it may take a while.

**Comment by sbillard** [comment]
Can you please explain why you think there are "many" changes? The theme version has not been updated and the changes all seem minor. You have wasted my time with this request.
