### ISSUE TITLE
Add Zenji theme to NPG

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/netPhotoGraphics#1144]
Hi Stephen, I juste found this theme can you add this to NPG in the next update.
https://github.com/zenphoto/zenji

Demo theme : https://demo.zenphoto.org/

**Comment by sbillard** [comment]
Are you intending to modify the theme to be nPG compatible?

**Comment by sbillard** [comment]
To quote the repository for this theme 

> This theme was originally written by @gjr-osweb in 2014/2015 already and never released. We had almost forgotten that he had sent it for review. The ZenphotoCMS team has roughly cleaned up some code issues so it should be generally compatible with the current release.

Seems ridiculous to add a theme that has no support from its author and is over 5 years old in the first place.  Even the updates by the zenphoto team are well over a year old!

So unless if you intend to take over and maintain this theme there will be no plans to add it. It can (probably) be used if someone wants by enabling the compatibility pack. But I have no intention of testing that.
