### ISSUE TITLE
site upgrade plugin question

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1148]
Currently, when you activate the plugin "site_upgrade" and close the site, everyone get's redirected to the closed.html page. When you want to work on the site as the main admininstrator it would be nice if you could see the actual site and not being redirected to the closed.html page. This way you can close the site when you are working on content as well. Is it an idea to leave the site open for the main administrator and show a main notification bar on top of the site that the site is closed for other users?
Just an improvement that I thought I'd share with you...

**Comment by Elinth** [comment]
And sometimes it takes a long time for the site to re-open again.

**Comment by sbillard** [comment]
To view the site while keeping others out set the state to "test mode". When in this mode there will be a banner both on the admin pages and the site pages telling you it is in test mode.

As to why it takes a while to open, that is most likely a caching issue with your site. From the nPG point of view the site will no longer redirect as soon as you have opened it. But the browser and or your server may well be remembering the redirection and doing the redirect without asking. Not necessarily nice, but it does improve performance in most cases.

**Comment by Elinth** [comment]
Cool, I did not notice that! Thanks Stephen, as always you are amazingly quick with your response! Great support!
