### ISSUE TITLE
Error when giving comments on an album

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1150]
Hi Stephen,

There is an error when I comment on a album and click send. See below. 

EXCEPTION (0): "Call to undefined function bool()" in /srv/disk6/279773/www/site/npgCore/extensions/PHPMailer.php on line 147 

Cheers

**Comment by sbillard** [comment]
I am not in the position to test the fix for this right now. 

Could you change line 147 in npgCore/extensions/PHPMailer.php to read
 `$mail->SMTPAutoTLS = (bool) $mail->SMTPSecure;`
and verify that it does fix the issue.

**Comment by Elinth** [comment]
Sorry, couldn't respond earlier. Fix did the trick. Many thanks!
