### ISSUE TITLE
Question re jPlayer new skin

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1151]
If I want to create my own skin for jPlayer by modifying one of the existing skins, where do I place the new skin so that it will persist across upgrades to nPg?  My thought would be to put it in plugins/jplayer/skins but not to put the rest of the jplayer components in there too.  Is this right and do I need just the new skin there or do I have to move the entire jPlayer plugin contents from core/extensions into plugins?

Thanks

NK

**Comment by sbillard** [comment]
Your thought is exactly correct. All you need to put in that folder is your custom skin.

**Comment by nerdykit** [comment]
Thanks.
