### ISSUE TITLE
conflict between jplayer and panorama

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1164]
Just noticed this one... I use the jplayer plugin for my videos and panorama.  If panorama is enabled, no video will play and when I select a video I get a series of error messages which I've cleaned up from the page source to show you below.... (and the video does not play, of course)

WARNING: &quot;A non-numeric value encountered&quot; in ...removed path.../npgCore/extensions/panorama.php on line 119
WARNING: &quot;Division by zero&quot; in ...removed path.../npgCore/extensions/panorama.php on line 119
WARNING: &quot;A non-numeric value encountered&quot; in ...removed path.../npgCore/extensions/panorama.php on line 119
WARNING: &quot;Cannot modify header information - headers already sent by (output started at ...removed path.../npgCore/functions.php:2230)&quot; in ...removed path.../npgCore/lib-image.php on line 38
WARNING: &quot;Cannot modify header information - headers already sent by (output started at ...removed path.../npgCore/functions.php:2230)&quot; in ...removed path.../npgCore/lib-image.php on line 39
WARNING: &quot;Cannot modify header information - headers already sent by (output started at ...removed path.../npgCore/functions.php:2230)&quot; in ...removed path.../npgCore/lib-image.php on line 40

...removed path... is just me editing out any site specific information for reasons of security

If I disable panorama, the error messages are not presented and videos play as normal.

Let me know if you want me to enable panorama again, and then send you the link to one of the pages throwing these errors.

Thanks

NK

**Comment by nerdykit** [comment]
Did some further testing...  disabling the jpg that goes with each video file (same name) doesn't change the problem, it still exists.  So the panorama conflict is probably with the player itself or else with the class-video plugin.

Switching video player plugin over to videojs doesn't change the problem.  So at present I've given up on panorama plugin so that videos can be accessed and viewed.

**Comment by nerdykit** [comment]
Oops, didn't mean to close the issue.  It is not resolved

**Comment by sbillard** [comment]
So this happens when the panorama plugin is trying to show a video? The error in panorama.php indicates that the object height or width is zero. The error in lib-image.php is a downstream effect.

**Comment by nerdykit** [comment]
Yes, basically when panorama plugin is enabled, and I go to an album page containing one or more videos, I do see the video thumbs, when I select a thumb in order to choose a video for viewing, I then get a page full of the error messages.  The video itself is a standard size 720 x somethingorother video as is the jpg placeholder that accompanies the video.  The page with the errors seems to be the normal URL for viewing any image except that the admin menu is no longer present (if I have viewed the page while logged in as admin).  Behavior is the same whether in as admin or viewing normally (not logged in).

**Comment by nerdykit** [comment]
Both the jpg and the m4v (same as an mp4) are 720 wide and 540 high.  Maybe panorama isn't able to determine the size of the video.  Does it need to do some sort of image size determination in order to do its panorama magic?

**Comment by sbillard** [comment]
I don't think panorama.js works with anything but an image. I can make the plugin revert to just displaying the image. I suppose it should just show the default sized image?

**Comment by sbillard** [comment]
Probably the theme should decide not to use panorama. 
`if (class_exists('panorama') && isImagePhoto()) {
								panorama::image();
							} else....`

**Comment by nerdykit** [comment]
I think that panorama should only (possibly) kick in when the item to be displayed is an image (and wide enough to trigger panoramic display).  Videos are rarely of panorama dimensions and anyway, if it's a video then the image is already being panorama-ed.  The two are more or less equivalents, the viewport of the video moves or in the case of a still panorama it allows the viewport to be shifted across the image.  So when panorama encounters a file of certain types (mp4, m4v and all the other playable video types) panorama should just get out of the way and let the existing display take over.

**Comment by nerdykit** [comment]
> Probably the theme should decide not to use panorama.
> if (class_exists('panorama') && isImagePhoto()) { panorama::image(); } else....

I think that's the right idea.  Panorama just doesn't activate at all in the case of a video image.  I can try out some code in my theme if I know from you what that code should be.

**Comment by sbillard** [comment]
Dev release with changes https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by nerdykit** [comment]
Looks good.  Thanks Changed from my custom theme to basic (my custom is just a very light re-work of basic with a bit wider image etc).  Videos play, panoramas pan. No error messages.  Were your modifications all to the image.php file in the theme or where there others?   (Just trying to figure out what I'll need to modify for my custom theme)

**Comment by sbillard** [comment]
I also made it so that the panorama plugin would revert to displaying the standard sized image if it was invoked on something that is not a real image. But I think the decision on how to display the image is best left up to the theme since the height of the standard image display might not match up with the panorama.

**Comment by nerdykit** [comment]
I think that's got it.  Modified the line in the image.php file in my customized version of basic theme and now the two plugins both work.  Thanks.  Will close this issue.
