### ISSUE TITLE
Error in placeholder image name causes nasty display of album thumbs

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1183]
If there's an error in the name of a placeholder jpg that accompanies a video, then when the album thumbs are displayed, the display shows the error message etc. and completely messes up the display of that page.  Perhaps the error should caught and the error message not displayed. ie: make the error handling less catastrophic.  In my case using basic theme, simply having accidentaly left an extra period before the extension of the placeholder jpg produces an overwritten error message line that can be extracted from page source (not readable on normal album thumbs display screen because it is overwritten) to be...
Warning:  filemtime(): stat failed for ********/gallery/albums//travel/central-america-2016/best-of-part2/BoS-108a-DSCN2957-ss.jpg in **********/gallery/npgCore/extensions/class-video.php on line225

It's not the error itself; that is easily caught and corrected but rather how the error is handled which is the issue I'm noting here.  A suggestion would be to just show the standard blank thumbnail that appears for a video if no placeholder jpg is present that matches the name of that video or even an icon with a question mark or red X.  Not what happens at present.

**Comment by sbillard** [comment]
Help me understand this better.  How did you create an error in the name? So far as I can see, the the thumbImage  is set based on finding a file of the appropriate name, so the file must exist.

**Comment by nerdykit** [comment]
> On Jul 9, 2020, at 1:15 PM, Stephen <notifications@github.com> wrote:
> 
> Help me understand this better. How did you create an error in the name? So far as I can see, the the thumbImage is set based on finding a file of the appropriate name, so the file must exist.
> 
> 

In creating the image that will bear the same name as the video, I inadvertently included an extra period before the extension as I was typing in the name to match that of the video.  That was then uploaded and the error results.  Will re-create the error and send a screenshot.

**Comment by nerdykit** [comment]
This is how it looks when an error is present in the filename of the matching jpg for the video.  My "issue" is just that this is not a very elegant (or helpful) way of dealing with an error of this type.

![nPG error](https://user-images.githubusercontent.com/3220548/87090886-91751200-c1ed-11ea-92cd-9c8f4218649f.jpg)

**Comment by sbillard** [comment]
Thanks for the full explanation.  Turns out this is a pretty  unique error. The problem was with the function that locates the placeholder image. It would match if (and only if) there was exactly one extra period before the file suffix. Then it eliminated the extra period, so down the line the file was not found.

Fix is in the .08 DEV release. The file with the extra period will no longer trigger a match.

**Comment by nerdykit** [comment]
Thanks for finding an answer and fixing it.  I'll try not to do that again.

NK
