### ISSUE TITLE
How to incorporate a codeblock into the image page

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1189]
I used to have a codeblock appearing on my image.php pages but somehow I clobbered that and I can't figure out from the documentation how to add a codeblock.  Do any of the included themes incorporate a codeblock? Thanks

**Comment by sbillard** [comment]
There are two pieces to the answer to this question. 

First, the theme's image.php script must support codeblocks by invoking the `printCodeBlock()` function at the appropriate place on the page. Of the distributed themes, only Garland, Masonry, and paradigm do that.

Second, the image object must have the codeblock defined. That can be done from the expanded image edit page.

**Comment by nerdykit** [comment]
Thanks, and my assumption is then that I would specify which (if there are several) codeblock I want to appear, inside the parentheses.
Perhaps a blue "i" info pop-up with what you've noted above would be a useful addition to any admin pages where codeblocks can be defined.  Will close.

**Comment by sbillard** [comment]
You are correct in your assumption. Also, the "Info" suggestion is a good one.
