### ISSUE TITLE
Display of EXIF data

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1192]
I'm using theme Basic and if I click on Image Info beneath any image I get a colorbox display of the image EXIF data that I have selected but not the one I want which is the Date Created.  I know that this information is in the image as part of IPTC core but it doesn't appear on the image display page nor on the admin image page for that image.

Actually the date created for an image (the date the image was shot) isn't available anywhere within nPG that can find.  I'd like to be able to see that somewhere even within the Admin pages and I'd also like to be able to call it up for general display of images (assuming that the data is actually embedded in the file). 

Thanks

**Comment by sbillard** [comment]
Take a look at the metadata option on the image option page. There you will find all the metadata and their handling. Only those fields that have "show" selected are displayed.

You can fetch any image metadata field (that is not disabled in the option) by using the "magic" function get<db field>(). That is you can use getIPTCDateCreated() to fetch the IPTCDateCreated field.

However, there may be a bug, in checking this out I seem to not be retrieving the dates correctly.

**Comment by nerdykit** [comment]
Thanks, I'm familiar with the metadata section of the options and have used it to show, hide or disable various items but even with date created clearly selected (and having run setup as requested after any change in the metadate options) I still don't get to see that particular piece of metadata, I can see the others that I've selected just not the date.

**Comment by nerdykit** [comment]
I just tried to use getIPTCDateCreated() and got a call to undefined function.

**Comment by nerdykit** [comment]
Just tried using the default set of exif information from the image admin options page and still no date appears.

**Comment by sbillard** [comment]
I have found the bug in displaying dates. That will be fixed shortly. I think I did not properly describe the magic functions. These are magic methods of objects. You can use `$_current_image->getIPTCDateCreated()` to fetch the date created (for instance.) You can use get... and set... with any database field and it will "magically" get/set the field.

**Comment by nerdykit** [comment]
Thanks, that does allow me to view and display the DateCreated, the time comes up as empty (just zeroes) but that might just be a result of the time not being parsed out of the datetime string.

**Comment by sbillard** [comment]
These values are stored in the database as _datetime_ type. So they will be either a valid date-time, NULL or 00-00-0000 00:00:00

If they are coming up empty for  your then you should check your database to be sure there are values stored. There is no transformation done by the magic methods, they just fetch and return the database value. There are a multitude of possible date created metadata entries, maybe your camera is using a different one. I have images that use EXIFDateTimeOriginal, EXIFDateTimeCreated, IPTCDateTimeCreated, IPTCDigitizedDate, and XMPDateTimeOriginal.

**Comment by nerdykit** [comment]
What I've learned from examining the database is that the EXIF versions of the datetime **do** have the time included and that the IPTC version holds the Date but not the Time (it's set to zeroes).  So a  "magic" call to EXIFDateTimeOriginal() **does** display both date and time for me which is great.  I still think that there's a bug in nPG somewhere since it was nPG that has stored these metadata values in the database in the first place and then retrieved them for the "image info" display below an image in Basic Theme and while many metadata values do show there, the Date (and Time) that the photo was taken doesn't appear in the metadata display area on a standard image display page when using Basic Theme.

**Comment by sbillard** [comment]
Most of my images do not have values stored in EXIFDateTime, but some do, so clearly nPG is able to load these values. If you with to give me an original picture that you think should have the data, I will check things out. The code that loads these fields gets them unchanged from the database. The only reason it might not do so is if the field is "disabled". But if the field is disabled, it should also not be part of the database structure.

**Comment by nerdykit** [comment]
Since I know that you've been to the Galapagos, this one is appropriate....

This image has the following dating fields set (among others) ....
IPTC Date Created
IPTC Digital Creation Date
IPTC Digital Creation Time
EXIF Date Time Digitized
EXIF Date Time Original
(EXIF version is 2.3)

The first two contain only a date, the time is contained in the third one.  So in order to fully display date with time it would be necessary to cobble together the two.  At present, when I click on Image info this is what displays although various date and time fields are selected for display in my admin image options page.

![GAL2w-23-IMG_3892](https://user-images.githubusercontent.com/3220548/88469204-bc28c100-cea3-11ea-8e88-2c8bdc0a2ab4.jpg)
![image-info screenshot](https://user-images.githubusercontent.com/3220548/88469209-c64abf80-cea3-11ea-899f-83d4dcb253ec.png)

**Comment by nerdykit** [comment]
These are the settings in use when above was displayed...  (I had to grab 2 because the field is so long and I'm still only showing relevant sections)

![field1](https://user-images.githubusercontent.com/3220548/88488037-76b9d180-cf3f-11ea-9010-a92ce5d1eda3.png)
![field2](https://user-images.githubusercontent.com/3220548/88488040-7a4d5880-cf3f-11ea-9287-269ac06470e6.png)

**Comment by sbillard** [comment]
the data in your image is as follows:
`  'EXIF' => array (
    'VerboseOutput' => false,
    'Errors' => 0,
    'ValidJpeg' => 1,
    'ValidIPTCData' => 0,
    'ValidJFIFData' => 0,
    'ValidEXIFData' => 1,
    'ValidAPP2Data' => 0,
    'ValidCOMData' => 0,
    'ValidAPP1Data' => 1,
    'APP1' => array (
      'Size' => 538,
    ),
    'Endien' => 'Motorola',
    'IFD0NumTags' => 6,
    'IFD0' => array (
      'Make' => 'Canon',
      'Model' => 'Canon EOS 60D',
      'Software' => 'Adobe Bridge CS5',
      'DateTime' => '2013:03:06 19:10:03',
      'Artist' => 'Kit Doan or Jane White',
      'ExifOffset' => 168,
    ),
    'IFD1Offset' => 0,
    'SubIFDNumTags' => 22,
    'SubIFD' => array (
      'ExposureTime' => '1/320 !sec!',
      'FNumber' => 'f/6.3',
      'ExposureProgram' => '!program!',
      'ISOSpeedRatings' => 100,
      'ExifVersion' => '!version! 2.3',
      'DateTimeOriginal' => '2013:02:13 07:28:15',
      'ShutterSpeedValue' => '1/320 !sec!',
      'ApertureValue' => 'f/6.3',
      'ExposureBiasValue' => '-0.33 EV',
      'MaxApertureValue' => 'f/1',
      'MeteringMode' => '!pattern!',
      'Flash' => '!no flash!',
      'FocalLength' => '180 mm',
      'ColorSpace' => '!srgb!',
      'ExifImageWidth' => '1024 !pixels!',
      'ExifImageHeight' => '682 !pixels!',
      'FocalPlaneXResolution' => 5728.176795580111,
      'FocalPlaneYResolution' => 5808.403361344538,
      'FocalPlaneResolutionUnit' => '!inch!',
      'ExposureMode' => 0,
      'WhiteBalance' => 0,
      'SceneCaptureMode' => 0,
      'FocalLengthIn35mmFilm' => 2611.344106003364,
    ),
  ),

'IPTC' => array (
    '1#090' => array (
      0 => '%G',
    ),
    '2#000' => array (
      0 => '' . "\0" . '',
    ),
    '2#055' => array (
      0 => '20130213',
    ),
    '2#060' => array (
      0 => '072815',
    ),
    '2#080' => array (
      0 => 'Kit Doan or Jane White',
    ),
  ),
`

In the IPTC array, 2#055 is the date created and 2#060 is the time created. The EXIF data comes from the exif.php script and the IPTC data comes from the PHP getImagesize() function.

Currently nPG does not parse the IFD0 (or any other IFCn) elements as I do not know of a standard that relates these to specific metadata tags.

So your image has:

EXIFDateTimeOriginal
IPTCDateCreated
and 
IPTCTimeCreated

according to what is fetchable from the image by PHP and our exif reader. As you note, IPTCDateCreated and IPTCTimeCreated must be combined to give you a fully referenced time shot. Turns out that you can use $image->getDateTime() to get a time-shot value. It will use various date/time fields if present. In your case it will give you the EXIFDateTimeOriginal, but if that were not present it would combine IPTCDateCreated and IPTCTimeCreated.

I am pretty sure that your image does not have `EXIF Date Time Digitized` , `IPTC Digital Creation Date` and `IPTC Digital Creation Time` because I have images that present that data even though yours does not.

**Comment by sbillard** [comment]
I have put some images up on one of my test sites so you can see that they display these disparate time fields. https://testalbum-2.sbillard.org/test_two/metadata%20test/

In checking this out I did discover that the front-end display of these dates depends on what you  have set as the option for "date format". If it does not support showing the time, all you get is the date.

**Comment by nerdykit** [comment]
Now I'm wondering if it's a date configuration issue on my server.  I've attached two images which show what a Macintosh sees as the embedded information (some of it) for that test image.   Your test images (and one of them is mine) show a date, I get no date display at all, also your image info window has the title at the bottom, mine is at the top.  Perhaps I'm using an old version of whatever displays that window.  Fancy box?  Where does that live in nPG?  I'll try to make sure I'm using the latest version.

![Preview 1](https://user-images.githubusercontent.com/3220548/88492577-809ffc80-cf60-11ea-9255-bd546d9583c2.jpg)
![Preview 2](https://user-images.githubusercontent.com/3220548/88492579-839aed00-cf60-11ea-9c2a-0669df048b84.jpg)
 and running mdls on the file in terminal gives me this...  (the real date taken is 2013-02-13 other dates reflect the "processing" of the file by Adobe Bridge etc)  I am not familiar with the prefix kMDItem means.

_kMDItemDisplayNameWithExtensions      = "image.jpg"
kMDItemAcquisitionMake                 = "Canon"
kMDItemAcquisitionModel                = "Canon EOS 60D"
kMDItemAperture                        = 5.310704
kMDItemAuthors                         = (
    "Kit Doan or Jane White"
)
kMDItemBitsPerSample                   = 32
kMDItemColorSpace                      = "RGB"
kMDItemContentCreationDate             = 2013-02-13 15:28:15 +0000
kMDItemContentCreationDate_Ranking     = 2013-02-13 00:00:00 +0000
kMDItemContentModificationDate         = 2013-02-13 15:28:15 +0000
kMDItemContentModificationDate_Ranking = 2013-02-13 00:00:00 +0000
kMDItemContentType                     = "public.jpeg"
kMDItemContentTypeTree                 = (
    "public.jpeg",
    "public.image",
    "public.data",
    "public.item",
    "public.content"
)
kMDItemCreator                         = "Adobe Bridge CS5"
kMDItemDateAdded                       = 2020-07-26 01:07:16 +0000
kMDItemDateAdded_Ranking               = 2020-07-26 00:00:00 +0000
kMDItemDisplayName                     = "image.jpg"
kMDItemDocumentIdentifier              = 0
kMDItemEXIFVersion                     = "2.3"
kMDItemExposureMode                    = 0
kMDItemExposureProgram                 = 2
kMDItemExposureTimeSeconds             = 0.003125
kMDItemFlashOnOff                      = 0
kMDItemFNumber                         = 6.3
kMDItemFocalLength                     = 180
kMDItemFSContentChangeDate             = 2017-12-30 05:08:41 +0000
kMDItemFSCreationDate                  = 2017-12-30 05:08:41 +0000
kMDItemFSCreatorCode                   = ""
kMDItemFSFinderFlags                   = 0
kMDItemFSHasCustomIcon                 = (null)
kMDItemFSInvisible                     = 0
kMDItemFSIsExtensionHidden             = 0
kMDItemFSIsStationery                  = (null)
kMDItemFSLabel                         = 0
kMDItemFSName                          = "image.jpg"
kMDItemFSNodeCount                     = (null)
kMDItemFSOwnerGroupID                  = 20
kMDItemFSOwnerUserID                   = 501
kMDItemFSSize                          = 402509
kMDItemFSTypeCode                      = ""
kMDItemHasAlphaChannel                 = 0
kMDItemInterestingDate_Ranking         = 2020-07-26 00:00:00 +0000
kMDItemISOSpeed                        = 100
kMDItemKind                            = "JPEG image"
kMDItemLastUsedDate                    = 2020-07-26 22:51:04 +0000
kMDItemLastUsedDate_Ranking            = 2020-07-26 00:00:00 +0000
kMDItemLensModel                       = "EF-S18-200mm f/3.5-5.6 IS"
kMDItemLogicalSize                     = 402509
kMDItemMeteringMode                    = 5
kMDItemOrientation                     = 0
kMDItemPhysicalSize                    = 405504
kMDItemPixelCount                      = 698368
kMDItemPixelHeight                     = 682
kMDItemPixelWidth                      = 1024
kMDItemProfileName                     = "sRGB IEC61966-2.1"
kMDItemRedEyeOnOff                     = 0
kMDItemUseCount                        = 10
kMDItemUsedDates                       = (
    "2020-07-25 07:00:00 +0000",
    "2020-07-26 07:00:00 +0000"
)
kMDItemWhiteBalance                    = 0

**Comment by sbillard** [comment]
I did find a bug in storing the into the database the IPTC values which are simple times. That fix will be available shortly. The result of the error is that the IPTC time created was not stored in the database.

**Comment by sbillard** [comment]
The fix is up in the development release. There is one issue, though. The formatting of the time in the metadata comes out strange depending on the data formatting selected. In my case it adds Dec 31, 1969. This is caused by converting the string to a time value and then formatting it based on the date format selected. 

I'm open to suggestions on how to deal with this. My current thought is to not apply the user selected formatting.  If the date/time values are not formatted, but just displayed as in the database the function could just strip off the 0000-00-00 and only the time would be left.

**Comment by sbillard** [comment]
Forgot to mention. Since the time did not get stored in the database you will need to refresh your metadata.

**Comment by nerdykit** [comment]
I can confirm that the Dev release now shows the creation date of photos.  Will close with thanks.
