### ISSUE TITLE
Bootstrap theme image.php image not responsive and off page on mobile view

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1194]
In the bootstrap theme the large image of image.php is not responsive on mobile view. On mobile view it does not scale down.
This image page is accessed by clicking on the image link in albums.

**Comment by Elinth** [comment]
Maybe a side question to this, can you maybe help me with the code change to pull up fancybox via `<?php printBareImageTitle(); ?>` ? This would make all behavior for images (not video's) via fancybox. Now the image thumb is via fancybox and the link is the regular image.php page. Seems more consistent to do both via fancybox.

**Comment by sbillard** [comment]
Sorry, but I am not an expert on the bootstrap theme. Especially if it behaves differently in mobile view. 

As well, I have never used fancybox. The typical pop-up in nPG is done via colorbox. I really do not know the advantages of one vs the other. 

The basic theme uses colorbox to show the full sized image. You can see the code it uses by looking at the image.php script. Look for instances of "fullimage". You will see some javascript to attach colorbox to the class "fullimage" and an assignment of that class to  the href for the full image link.

**Comment by Elinth** [comment]
Thanks Stephen, couldn't get the thumb title to work. On the responsive image: it is really strange, Somehow the following style elements: are not picked up: __remove-attributes img-responsive center-block_  It is working on Vincents website. 
		`<?php printDefaultSizedImage(getBareImageTitle(), 'remove-attributes img-responsive center-block'); ?>`
Any thoughts or Is there another way I can trigger these in the image.php page?

**Comment by sbillard** [comment]
Seems that printDefaultSizedImage() was not setting the class attribute. This is now fixed and will be in the development build shortly

**Comment by Elinth** [comment]
Thanks! That did the trick!
