### ISSUE TITLE
videoJS poster image ?

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1196]
If I enable the option "Poster (Videothumb)" I get this ugly image as the initial load (before I hit play) image.  There IS a suitable poster image in place, I DO get a thumbnail in the album display which uses that thumb so I think that my poster image to support the mp4 movie is OK.  So here's what I get with the Poster box checked.

![Screen Shot 2020-08-01 at 11 59 36 AM](https://user-images.githubusercontent.com/3220548/89109167-9f384480-d3f3-11ea-9058-05bc754c3951.jpg)

If the Poster checkbox is not checked, I get a still of the first frame of the movie which is fine. But what is going on with the ugly display with Poster selected?

It may be that I don't understand what a poster image actually is but what I am assuming is that it is the image to be displayed as the movie loads and before "play" is selected.

**Comment by sbillard** [comment]
That image is the "broken image" thumbnail. So something failed when nPG tried to render the image. There may be an error in the logs. If not you can set the debug plugin option to log image processing debug information. That should tell us what is happening.

**Comment by nerdykit** [comment]
Here's my settings for videoJS
![Screen Shot 2020-08-01 at 2 14 07 PM](https://user-images.githubusercontent.com/3220548/89110714-3e643880-d402-11ea-9a50-066b5ebbf4b3.jpg)

and here's the relevant section of the logfile....

 {19384:Sat, 01 Aug 2020 19:18:19 GMT}	

WARNING: "array_pop() expects parameter 1 to be array, null given" in /mnt/usbdrive/webroot/public_html/gallery/npgCore/functions.php on line 2888

URI:/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&s=100&w=100&h=100&cw=0&ch=0&q=75&c=1&t=1&wmk=watermark-video&limit=30&check=2bafcc7e1c1f3594ab569d35cdfe39e7d97f0f8f&cached=1484258205

IP `108.63.168.69`

user:admin

array_pop called from npgFunctions::tagURLs (functions.php [2888])

from ThemeObject->setTitle (classes.php [584])

from Image->__construct (class-image.php [131])

from newImage (class-image.php [45])

from imageProcessing::cache (lib-image.php [449])

from i.php [162]

{19475:Sat, 01 Aug 2020 21:16:55 GMT}	

WARNING: "array_pop() expects parameter 1 to be array, null given" in /mnt/usbdrive/webroot/public_html/gallery/npgCore/functions.php on line 2888

URI:/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&s=100&w=100&h=100&cw=0&ch=0&q=75&c=1&t=1&wmk=watermark-video&limit=30&check=2bafcc7e1c1f3594ab569d35cdfe39e7d97f0f8f&cached=1617967137

IP `108.63.168.69`

user:admin

array_pop called from npgFunctions::tagURLs (functions.php [2888])

from ThemeObject->setTitle (classes.php [584])

from Image->__construct (class-image.php [131])

from newImage (class-image.php [45])

from imageProcessing::cache (lib-image.php [449])

from i.php [162]

{18639:Sat, 01 Aug 2020 21:18:05 GMT}	

ERROR: "Maximum execution time of 30 seconds exceeded" in /mnt/usbdrive/webroot/public_html/gallery/npgCore/admin-tabs/logs.php on line 212

URI:/gallery/npg/admin-tabs/logs.html?page=logs&tab=debug-1

IP `108.63.168.69`

user:admin

npgShutDownFunction called from unknown 
================

I included the last error because of the execution time error which I'm not sure about either.

NK

**Comment by sbillard** [comment]
I think I have found the initial problem. Not sure why I never saw it, though. Fix will shortly be in the development build .03

The last error is strange, do you have multiple debug logs? If so is there a lot of stuff in them? Maybe it is taking too long to format a full log page. Maybe cut down the size limit on the logs in the general options.

**Comment by nerdykit** [comment]
I've never paid any attention to those log file size settings.  I've removed a zero from each of them and reset the logs to see if the error goes away.  The server engine is a raspberry pi so not the highest-powered server device in the world (but one of the cheapest).  That could explain the timeouts.  Will keep watching the logs.

**Comment by nerdykit** [comment]
Dev 03 did not resolve the problem for me.  If a poster image is requested I get the broken image response.  Will check the logs.  See also settings not preserved across upgrades issue, may be related.

**Comment by nerdykit** [comment]
Log section.... can send whole log if you wish

 {21839:Sun, 02 Aug 2020 00:08:13 GMT}	

i18n::setMainDomain()

URI:/gallery/misc/beaver/beaver-movie1.m4v.html

IP `<<ip address removed>>`

user:admin

i18n::setMainDomain called from require_once (load_objectClasses.php [51])

from require_once (initialize-general.php [73])

from require_once (functions.php [12])

from include (index.php [13])

from index.php [72]

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

self::validateLocale(www,HTTP_HOST)

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

dynamic_locale from HTTP_HOST: www=>

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

self::validateLocale(en_CA,dynamic_locale cookie)

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

locale set from dynamic_locale cookie: en_CA

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

locale from cookie: en_CA;

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

self::getUserLocale Returning locale: en_CA

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

setlocale(en_CA.UTF8,en_CA.UTF-8,en_CA.@euro,en_CA,en,) returned: en_CA.UTF8

{21839:Sun, 02 Aug 2020 00:08:13 GMT}	

self::setupCurrentLocale(en_CA): locale=en_CA, $result=en_CA.UTF8

URI:/gallery/misc/beaver/beaver-movie1.m4v.html

IP `<<ip address removed>>`

user:admin

i18n::setupCurrentLocale called from i18n::setMainDomain (lib-i18n.php [360])

from require_once (load_objectClasses.php [51])

from require_once (initialize-general.php [73])

from require_once (functions.php [12])

from include (index.php [13])

from index.php [72]

**Comment by sbillard** [comment]
Is there any editing of the above other than removing the IP address? I ask, because there are no errors reported. Looks like there is just a trace of the Locale setting. That would come from the debug plugin option "load language selection processing" which you should turn off, specially if you are not having problems with language selection. I don't know it these calls might be also causing the rendering error. 

Also be sure you have cleared your image cache for the beaver-movie.jpg item.

**Comment by nerdykit** [comment]
Have turned off the debug for language selection and re-cached the images for that album.  I AM getting one red X on the cache report and a hover over the X reports "undefined". That might be the source of the problem.  Now I need to educate myself about cached images and how and where they are defined.

**Comment by nerdykit** [comment]
I've just discovered that if I click on the red X in the cache report I get some feedback.  Namely....

Album: [ misc/beaver ], Image: [ beaver-01.jpg ]

Image filesize: 178191

Debug i.php | Arguments:

    size = 100
    width =
    height =
    cw = 100
    ch = 100
    cx =
    cy =
    quality = 75
    thumb = 1
    crop = 1
    thumbStandin = 1
    watermark =
    adminrequest =
    effects =
    return_checkmark = 1

Image Processing Error: Watermark ! not renderable.

OK, now I've got no idea what php page is requesting that cache image or why it's being asked to watermark it.  Where are the requests to cache a particular size file being created?  I have looked over the cache section of admin image options and I don't see any problems in the settings there.  Clicking on any of the successfully checkmarked items does not produce a report similar to the one I get when I click on the red X (just trying to compare success vs failure)

**Comment by nerdykit** [comment]
I've just verified that with the Poster image selected in VideoJS plugin settings, there's no report in the debug log when I try to access the movie and get the 'not found' poster marker.  So is there a settings in the debug that I need to make to be able to see an error of that type?

**Comment by nerdykit** [comment]
I turned on Log Image processing which was not on in the debug plugin and now when I visit the movie I get...

 {31497:Sun, 02 Aug 2020 21:04:16 GMT} netPhotoGraphics v2.00.06.02.03-DEBUG_404_DISPLAY‑ERRORS_IMAGE	

Loading GD

{538:Sun, 02 Aug 2020 21:04:21 GMT}	

Loading GD

{461:Sun, 02 Aug 2020 21:04:26 GMT}	

Loading GD

{27708:Sun, 02 Aug 2020 21:04:29 GMT}	

Loading GD

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

Loading GD

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

i.php(misc/beaver, beaver-movie1.jpg): $size=, $width=960, $height=540, $cw=960, $ch=540, $cx=, $cy=, $quality=75, $thumb=1, $crop=1, $thumbstandin=1, $passedWM=, $adminrequest=, $effects=

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

imageProcessing::cache($imgfile=beaver-movie1.jpg, $newfilename=/misc/beaver/beaver-movie1_w960_h540_cw960_ch540_thumb.jpg, $allow_watermark=1, $theme=basic_for_kit) $size=, $width=960, $height=540, $cw=960, $ch=540, $cx=NULL, $cy=NULL, $quality=75, $thumb=1, $crop=1 $image_use_side=longest; $upscale=0);

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

imageProcessing::propSizes($size=, $width=960, $height=540, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=540):: $wprop=960; $hprop=304; $neww=960; $newh=540

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

self::cache:beaver-movie1.jpg: $size=, $width=960, $height=540, $w=960; $h=540; $cw=960, $ch=540, $cx=, $cy=, $quality=75, $thumb=1, $crop=1, $newh=540, $neww=960, $dim=540, $ratio_in=0.5625, $ratio_out=0.5625 $upscale=0 $rotate=0 $effects=

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

imageProcessing::cache:no upscale beaver-movie1.jpg: $newh=540, $neww=960, $crop=1, $thumb=1, $rotate=0, watermark=!

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

imageProcessing::propSizes($size=, $width=960, $height=540, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=540):: $wprop=960; $hprop=304; $neww=960; $newh=540

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

imageProcessing::cache:crop beaver-movie1.jpg:$size=, $width=960, $height=540, $cw=960, $ch=540, $cx=, $cy=0, $quality=75, $thumb=1, $crop=1, $rotate=0

{29579:Sun, 02 Aug 2020 21:04:30 GMT}	

Image Processing Error: Watermark ! not renderable.

    Request URI: [/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&w=960&h=540&cw=960&ch=540&t=1&limit=30&check=2011dddc4257ccee6f40d02424713e4774bf1a13&cached=82684788]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache//misc/beaver/beaver-movie1_w960_h540_cw960_ch540_thumb.jpg]

    Image: [misc/beaver/beaver-movie1.jpg]

{538:Sun, 02 Aug 2020 21:04:34 GMT}	

Loading GD

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

Loading GD

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

i.php(misc/beaver, beaver-movie1.jpg): $size=, $width=960, $height=540, $cw=960, $ch=540, $cx=, $cy=, $quality=75, $thumb=1, $crop=1, $thumbstandin=1, $passedWM=, $adminrequest=, $effects=

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

imageProcessing::cache($imgfile=beaver-movie1.jpg, $newfilename=/misc/beaver/beaver-movie1_w960_h540_cw960_ch540_thumb.jpg, $allow_watermark=1, $theme=basic_for_kit) $size=, $width=960, $height=540, $cw=960, $ch=540, $cx=NULL, $cy=NULL, $quality=75, $thumb=1, $crop=1 $image_use_side=longest; $upscale=0);

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

imageProcessing::propSizes($size=, $width=960, $height=540, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=540):: $wprop=960; $hprop=304; $neww=960; $newh=540

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

self::cache:beaver-movie1.jpg: $size=, $width=960, $height=540, $w=960; $h=540; $cw=960, $ch=540, $cx=, $cy=, $quality=75, $thumb=1, $crop=1, $newh=540, $neww=960, $dim=540, $ratio_in=0.5625, $ratio_out=0.5625 $upscale=0 $rotate=0 $effects=

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

imageProcessing::cache:no upscale beaver-movie1.jpg: $newh=540, $neww=960, $crop=1, $thumb=1, $rotate=0, watermark=!

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

imageProcessing::propSizes($size=, $width=960, $height=540, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=540):: $wprop=960; $hprop=304; $neww=960; $newh=540

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

imageProcessing::cache:crop beaver-movie1.jpg:$size=, $width=960, $height=540, $cw=960, $ch=540, $cx=, $cy=0, $quality=75, $thumb=1, $crop=1, $rotate=0

{29578:Sun, 02 Aug 2020 21:04:36 GMT}	

Image Processing Error: Watermark ! not renderable.

    Request URI: [/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&w=960&h=540&cw=960&ch=540&t=1&limit=30&check=2011dddc4257ccee6f40d02424713e4774bf1a13&cached=1109225182]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache//misc/beaver/beaver-movie1_w960_h540_cw960_ch540_thumb.jpg]

    Image: [misc/beaver/beaver-movie1.jpg]

{25771:Sun, 02 Aug 2020 21:04:48 GMT}	

Loading GD 

=====================

Looks to me as if there's some sort of error to do with watermark not renderable although the thumbnail IS watermarked for video which is all I want.  Not sure why any other image would be watermarked.  I previously unchecked allow upscale but because the poster image is taken from the movie it's the same dimensions as the movie (960 x 540) so maybe it would require upscale to fit the normal space reserved for conventional images.

**Comment by sbillard** [comment]
The poster image is treated as a thumbnail, so presumably the processing is trying to apply a thumbnail watermark, probably the default one.

**Comment by nerdykit** [comment]
Not yet resolved after Dev .06 upgrade.

**Comment by sbillard** [comment]
I have not been able to reproduce this failure, but from your logs I have a theory of what is wrong. Try the .07 build.

**Comment by nerdykit** [comment]
Looks good.  Cleared the image cache, cached images for that album.  No red X, set the poster image on in VideoJS, poster image displays before video is started.  All looks good.  I think you got it!

Thanks.  Will close.
