### ISSUE TITLE
videoJS can't play m4v files

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1197]
Despite the fact that videojs.php has the line

Gallery::addImageHandler('m4v', 'Video');

Which I assume means that videoJS can display m4v as well as mp4, if a file has the extension m4v then videoJS sees it as not the correct format and reports "no compatible source found"   if a file is generated as m4v and simply renamed to mp4 videoJS is happy.  But the indications are that videoJS can display m4v files, I have not found this to be the case.

**Comment by sbillard** [comment]
I've updated the video-js library to version 7.8.4 which fixes this, at least for me.

**Comment by nerdykit** [comment]
OK, how can I update that library for myself to test to see if the problem is resolved.

Thanks

**Comment by nerdykit** [comment]
I've downloaded the latest videoJS (7.8.4) from their github location.  If it's just a matter of swapping out video.min.js and/or the css file I can easily do that.

**Comment by nerdykit** [comment]
Did what I was asking about above, swapped in the new video.min.js and I can confirm that it now plays both mp4 and m4v versions.  I DID notice that some of the css might need tweaking.  I swapped in only video.min.js     Now the slider for  the volume control appears outside of and below the controls bar.  Everything else seems to be in place OK as far as the controls bar goes.  The video shows as "live" which might be because it needs to fully load the video to decide how long it is, or maybe that's because it was shot on a cheap phone.

![Screen Shot 2020-08-01 at 3 39 25 PM](https://user-images.githubusercontent.com/3220548/89111647-41185b00-d40d-11ea-88ce-489177eb01eb.jpg)

Probably the controls bar just needs a bit more height assigned to it in css to fit in the volume control slider

**Comment by sbillard** [comment]
Try the development release. For me, the volume control is in the proper place. That release should also fix your poster issue.

**Comment by nerdykit** [comment]
Volume control is now after the speaker symbol and within the control bar.  The problem was the "Live" word that took up space.  Once you made that disappear, there was room for the volume slider.  So VideoJS now plays m4v video and things look good for this particular issue.  Will close with thanks.
