### ISSUE TITLE
VideoJS settings not preserved across upgrades

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1198]
I noticed this after upgrading to the regular release, my custom settings in VideoJS reverted to their default values but i thought maybe it was just a quirk or that I hadn't hit "apply" or something but I can now confirm that after installing the .02 dev release the VideoJS settings reverted to default settings and my custom settings were being clobbered by the install.  Probably doesn't have anything to do with the poster image issue so I'm putting it into a new issue.

**Comment by nerdykit** [comment]
Just did the dev 03 upgrade.  Settings clobbered again.

**Comment by sbillard** [comment]
Should be fixed in .06

**Comment by nerdykit** [comment]
Yes, the settings are now preserved after upgrade to Dev 0.6    Will close with thanks
