### ISSUE TITLE
Dev 06 upgrade doesn't allow easy access to albums or sub-albums or change order of albums

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1199]
Just did the Dev 06 upgrade.  When I try to access subalbums under my top-level grouping in my album tree I get the menus on the left and the rest of the screen is blank.  What seems to be lost is the ability to view album structure as icons and to shift the ordering sequence.  There IS an option to mass-edit albums but this feature (if new) is not nearly as user-friendly as the old method of accessing albums or of selecting multiple levels for display so that it is easy to drill in to the desired album for editing.  I think this is a bug not a feature.

**Comment by nerdykit** [comment]
I can still access the sort feature if I view gallery while logged in, the sort feature is there briefly but once I've selected any one album then I go back to the left menu only display with nothing appearing to the right.
![Screen Shot 2020-08-03 at 10 08 46 AM](https://user-images.githubusercontent.com/3220548/89208517-60c89400-d571-11ea-88a8-9fdfc7f41830.jpg)

**Comment by sbillard** [comment]
Fix is in .08 (I missed a place that a change was needed on 636b956494ed18975e4a928155d37672e2c0dcfd

**Comment by nerdykit** [comment]
That resolves this issue.  By the way, the ease of upgrade via the button is just great. Congratulations on implementing that feature (long ago I know but at times like this I sure appreciate it).  Will close.
