### ISSUE TITLE
Question? A way to force display of the upgrade link

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1201]
I've been working with dev releases but I don't seem to have access to the upgrade link for regular release upgrades.  I've disabled both devrelease and debug plugins but my reported version is still a dev release and no button for regular upgrade.  Is there a file I can remove or change that will force the system to think that it is ready for an upgrade?

Thanks

**Comment by sbillard** [comment]
You won't get a button for a regular release when the release version is less than the development version you are running. If you want to fall back you can always download the release from the netPhotoGraphic.org website, but why would you want to do that. It is also the case that the check for updates happens only about once a day, so there could be one that just has not showed up. In any case if you have the devReleases plugin enabled there will be a check for updates button that will force a re-check. There is a limit to the number of requests that GitHub will allow per some period of time. That is why the check that nPG normally does happens only about once a day.

The current regular release is 2.00.06.03. It is showing up on my test builds that are not yet up to that version.

**Comment by nerdykit** [comment]
Thanks.  I won't worry about not running a release version.
