### ISSUE TITLE
Feature improvement forgot password process

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1202]
Hi Stephen,

Is it possible to ask you for another improvement? This time of the "forget password" process to make it much easier? Why not have the the user input their email address and then sent the user an email with a unique link to that email address that brings them to the NPG account where they can change their password. This is how many webshops do it these days. I keep having users who forget their username and get stuck. In any case it would be better if the forget password form asks for a users email address instead of the username when they have to input for their security question. Just a thought, I hope you are open to such a suggestion.

**Comment by sbillard** [comment]
I do not think I understand. This feature already exists.

<img width="595" alt="2020-08-12 09_11_23-Development Admin_ Overview - Personal - Microsoft​ Edge" src="https://user-images.githubusercontent.com/2474007/90039674-d1f7fd80-dc7b-11ea-9caa-89e387f974c7.png">

The form asks for either the user name or the e-mail address.

**Comment by Elinth** [comment]
Oh you are right, I did not notice the link on the bottom. Am I correct that once you completed this email form an email request for password change gets sent to the main admin? It does not sent a link back to the user to change the password directly correct? I think the latter is what I meant with my request.

**Comment by Elinth** [comment]
I would be a nice option or plugin if the reset via email would be displayed first instead of the challenge question. It is more common use, don't you think? Is this feasible?

**Comment by Elinth** [comment]
Or maybe have two links first: reset via challenge question and reset via email.

**Comment by sbillard** [comment]
Do you use challenge phrases? If not you should disable them in the security options. If you do use them, they should come first as they are the quickest way to get onto the site. That is you do not have to wait for an e-mail. It is only if you have a challenge question and the user does not remember his answer that there is any inconvenience.

**Comment by Elinth** [comment]
Brilliant, that setting solved one part of my question. As I do not want to use the challenge question. The other part is why does the email reset not take the user to the admin page so he can reset it himself? Now it only sends an email to the main admin for him to reset the password..

**Comment by sbillard** [comment]
It does send the user the email unless he has no email address (which can't be the case if he used his email address for the reset.) The mail is CCed to the administrators as well, just in case the user does not have an email address or the address of record is not valid. If you are testing this as the admin you are in a degenerate case. 

You should have a copy of a password reset request I created. This email did come to me as well as to the copy list of administrators. (It actually came twice since I am also an administrator!)

I do think that the administrators should be blind copied. That will be in the next update.

**Comment by Elinth** [comment]
Thanks Stephen,

I tested this with a test user but accidentally used the same email as the admin, this created my confusion. 
It works really well. thank you for explaining how this works. Really helpfull. Again, thanks for your support!
