### ISSUE TITLE
Question re: location

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1204]
Looked through the documentation pdf and clicked some blue i markers but can't find the answer.

What is the correct format for location data?  Is it the same format for both albums and individual images?

Thanks

**Comment by sbillard** [comment]
The format is the standard _degrees_ _minutes_ _seconds_ _reference_. They can be separated by either a space of a colon and are case insensitive. Degree(°), minute('), second(") markers are optional. If the reference is omitted it is assumed N for latitude and E for longitude.

E.g,
33:0:55 
118° 2' 8.4" W
4 0 0 s

**Comment by nerdykit** [comment]
Thanks.  Also wasn't sure if one of the decimal versions wasn't required here.  There's many L & L variants for the same location.  Perhaps adding this information into the blue i beside Location on both album and image admin pages would help others. Will close.

**Comment by sbillard** [comment]
Just curious, where do you see a means to store the album GPS data? If you are referring to the "location" field that is a text description field. 

The closest thing to an album location would be the collection of image geolocations from the album.

**Comment by sbillard** [comment]
I've decided against the info icon. None of the other fields have one. Instead I implemented accepting a floating point number as an option. So now anything you can think of that will represent a geocoordinate will work.

**Comment by nerdykit** [comment]
I've just spent a while messing with the google cloud etc.  It's all new now and not nearly as simple as the old get an api and enter it and you're good to go.  Basically, they're now charging for anything more sophisticated than simply embedding a map.  So there's the javascript.map.api (costs $) and the embed.map.api (free).  Supposedly the code for the embed map is just an iframe embed:

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=API_KEY
    &q=Space+Needle,Seattle+WA" allowfullscreen>
</iframe>

although I don't seem to be able to key that to work for my key.  Still tinkering on my test page with map to see why I keep getting rejected.  Using the same key in the plugin and then going to an image with lat and long entered (correctly) the map appears momentarily and then disappears with a javascript error message (ie: see the javascript console), the console just reports rejection.  Is it because the map is being displayed with javascript instead of a simple iframe?  I dunno.

See next comment about entering the latitude and long. as a response to your replies above.

**Comment by nerdykit** [comment]
I use a simple variant of basic theme.  In both, below the image display is a call to simple::map.  I found the following.

This call is present in both album.php and image.php pages.  If location is filled in with correct long and lat format data the album page presents a google maps link and attempts to display map when clicked (attempts--- because of error with javascript noted above).  On album admin page the location field accepted L & L as described in your response.  On image admin page there are two fields side by side and only if you are careful do you realise this (border would be helpful?)  But if long and lat. are entered on image page, it also attempts (and fails) to display a map image (same error).

Is it working for you?  So far I can't even get a non npg page based on their suggested test of the api with iframe to produce anything.

**Comment by sbillard** [comment]
Both googleMap and openStreetMap work just fine for me. This is both with images that have embedded geolocations and ones I have set via the image edit page. 

There may be a bug in saving the geo Coordinates, though. I discovered it when adding the floating point handling. Give the dev release a try and see if the coordinates are stored correctly. Under some circumstances it may have put latitude into longitude or vice versa. That should have shown up after you saved the coordinate. (Also the fields are now labeled.)

I've also tried all the display options and all work. 

Is there anyway you can refine what the error message you are getting is? Then I might find it through a search and know what is happening. The html (iFrame) for the map is setup by the javascript and inserted into the map_canvas DIV that the nPG plugin places on the page.

**Comment by nerdykit** [comment]
Which theme page is being used to display the sheet of album image thumbnails, is it image.php or album.php (mod rewrite obscures so I can't tell what's loading the image thumbs)?  Where would that page attempt to take latitude and longitude information from because that page tries to display a map below the grid of image thumbnails.  Is it the first image in the album that contains any latitude or longitude information?

**Comment by nerdykit** [comment]
If the location field on an album edit page is just a standard text field, then where is that text displayed?  If I remove any latitude and long. info that I had entered there and just type something in I see no sign of that appearing on the album page.  Why should there be a specialised location text field (which doesn't seem to appear anywhere) when a description of the location could simply be entered into the general purpose album description field?

**Comment by nerdykit** [comment]
Which google map api (or multiple apis) have you selected from google cloud services for your working example?  I am just attempting to use the embed version of the api which is the free one (although it requires setting up a paying account in google cloud services).

**Comment by sbillard** [comment]
The album location field display is up to the theme. I really do not know much about it, the field has been there since before my time. Seems there is also an image location, but that is not part of the edit page. The only use I can find is for the album location in the Paradigm theme. I doubt anyone would notice it missing. Maybe I will remove these fields.

I have not updated my key in ages, so it is probably the old key. I will have to do some research on this. Maybe you could try openStreetMap instead, (Just enable it and disable googleMaps.)

**Comment by nerdykit** [comment]
I figured out my problem.  There are so many hoops to jump through for the new v3 api.  It ain't easy.  I had to set up a proper billing account and link it to my "project" so that I could then get a working key.  So my key now works and maps display properly.  Will close this question/issue but it is worth noting that it is no longer a relatively simple process to use the google maps api if it requires the javascript key (which npg does require).  An easier solution would be the embed key and just put an iframe into a code block and display that instead.   Will take a look at openstreetmaps.  I think I messed with it before and I already have whatever they require in terms of a key.  Thanks.

**Comment by sbillard** [comment]
Well, we use all sorts of tools in nPG. In this case it is CodeIgniter's google maps interface. So there would need to be a different support library. Since we already have openStreetMap it does not seem worth it to try to find one.

If there are any words you can suggest we add to the documentation to help people get a proper v3 key I will add them.

**Comment by nerdykit** [comment]
A few words wouldn't cut it.  It needs a whole 'Google Cloud Services for Dummies' book.   Things that remain from this whole business is that the page that displays the thumbnails of images within an album tries to display a map if any one of the images has location info entered.  Is this the best way to display the chart of image thumbs when the location map would only relate to one of the images...I guess the first one it finds with location info entered.

The other would be that in the DMS display, the seconds should be a real number so that decimal can be stored and thus the location is pin-point instead of to the closest whole second.  Of course simply using a full decimal display for just the degree completely bypasses this issue and is probably the easiest to implement.  Otherwise you’re parsing for all sorts of possibilities in the entry.  Google maps displays the decimal degree location within the URL when you seek something.

**Comment by nerdykit** [comment]
Just upgraded to the dev release that allows for decimal input on the latitude and longitude.  The entry area looks much clearer now.  So I tested it and while I can enter an exact location that way, I can see that what happens is that npg converts my decimal entry to DMS and because the seconds are forced to be integer the pin shifts a couple of hundred yards away from where I would like it to be.  If you can allow just the seconds of the DMS value to be a decimal number after conversion then pins would remain exactly where they have been identified.

**Comment by nerdykit** [comment]
Suggestion for the documentation:

In order to obtain a personal Google maps API key, you will need to set up an account and project with Google Cloud Services. You must add the Maps JavaScript API to your project from the API library and set up and link in a payment method (although you will not actually have to pay for moderate usage.)

You can limit the use of this API to a specific web site and should do so and you can also set a quota on the number of calls to the API which should guarantee that you always stay within the "free" limits.  Setting up a Google Cloud Services account is not simple, but once done successfully you can use the API in Google maps plugin.

Another possibility is to use the OpenStreetMap plugin.

**Comment by sbillard** [comment]
No problem letting the seconds be fractional. For the output, there needs to be a precision applied. Is two decimal places adequate? The actual coordinates are stored as floating point and that is what the map software uses. They are converted to DMS format for display only. So unless you save the image again using the integerized seconds, it should not impact the map.

As to the theme displaying a map if any image has a geolocation, it is really something that the theme would have to be involved with the decision. How many images should have locations to warrant the display? 

Thanks for the above text.

**Comment by nerdykit** [comment]
![coordinate_precision](https://user-images.githubusercontent.com/3220548/90704028-37338c00-e244-11ea-96f7-789382292697.png)
I found the above while researching an answer to your question.  It doesn't really answer it because it's about decimal degrees and we're trying to decide about decimal seconds.  But further down the same page I found this...

Explanation

This cartoon gives increasingly precise latitude and longitude coordinates for a location on the planet Earth. However, a given coordinate covers a rectangular region of land, and thus leaves some ambiguity; thus, greater precision requires an increasing count of decimal points in your coordinates. This comic uses this information to roughly identify how precise a given coordinate length might be.

> The increasing precision of coordinates in this cartoon are similar to the increasing magnification in the short documentary "Powers of 10," which can be found here. (Also parodied in #271:Powers of One).
> 
> The coordinates at 28.52345°N, 80.68309°W (in decimal degrees form; in geographic coordinate system form using degrees, minutes, and seconds, 28° 31′ 24.4″N, 80° 40′ 59.1″W) are pointing to the Rocket Garden at the Kennedy Space Center in Merritt Island, Florida —specifically, the tip of the Delta rocket.
> 
 So that statement looks as if only 1 decimal place on the seconds would probably locate just fine.  Can we try one decimal place and I'll report back.  Will take a screen shot of the present map just for reference.

As for your second question, I would prefer NOT to have any display of a map link on a sheet of image thumbs and only to have the map link appearing on an individual image page.  In my version of basic (and this is just via straight configuration settings as provided by nPg) I've got 36 thumbnails per page. Since they could be from very different locations, it's not very meaningful to have a map displayed for the whole group.  So my vote would be that if we're viewing a page of image thumbnails, no map link need appear regardless of whether any of these individual images have location information defined.

**Comment by nerdykit** [comment]
Aha!  If you use DMS entry you CAN'T enter a fractional number of seconds.  It is truncated (not rounded).  None of the three values can be anything but integer if they are entered as DMS.  So decimal degrees entry can produce 1 decimal place precision on the seconds but DMS style entry doesn't permit that.

**Comment by nerdykit** [comment]
I've realised that if the value that is actually being stored is a fractional degree, then that is likely what is being passed out to Google maps for display.  It's certainly the value that is seen within google maps URLs.  So that means most of what I've written above is nonsense, the nPg fields only show a visual representation of DMS but the real value and the one that counts is the one in the database.  So the graphic really does contain the answer.  5 decimal places on a decimal degree entry is accurate to a square about the size of a human, that ought to do and 4 would even be good enough.  The real question is "what is being passed out to Google maps-- DMS or fractional degree"?  That's what determines the number of decimal places needed.  The decimal places on the seconds display is cosmetic only.  Unless the seconds can actually be entered as a fractional number and right now they can't.

**Comment by sbillard** [comment]
If you don't want a map on the album page you should remove the simpleMap::map() function call. Simple as that.

The problem we need to fix is if you re-save the image after the location is formatted. Then you loose whatever precision was not shown in the display. My research on the distance of one second latitude came up with anywhere from 100 to 80 feet. So I think that two decimal points should be adequate.

**Comment by sbillard** [comment]
There is a new DEV release up with these changes.

**Comment by nerdykit** [comment]
Looks good, I just wasn't sure which theme page to change.  I thought that maybe album.php just loaded the albums and their descriptions.  Of course I could have just experimented and quickly found an answer but map display is now edited out for albums and their image thumbs.

The new Dev release looks good.  Precision is just fine and I tested entry in the form similar to 26 23 9.42 and it is accepted and is redisplayed after leaving and returning to that image admin page so I think that this one is well and truly resolved.  Thanks.

**Comment by sbillard** [comment]
Thanks for the confirmation.
