### ISSUE TITLE
.webp files and fall backs for non-compliant browsers

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1208]
Hi
The good news is that, as of version 14 Safari and Mac are going to be able to show .webp images so it means all commonly used browsers will work with them.
The question is, how to configure nPG to fall back to .jpeg's when someone didn't/can't update their browser - there are scripts that exist that can query if .webp is available or not and then load the appropriate image type, so not a problem - the question is more how to manage the images? I would want the the default to be .webp, because some of the images would be better if I can use the alpha layer the format gives me, and the fall back would be .jpeg. I suppose I would have to manually put the jpegs in the folder alongside the webps...
Any ideas?

I hope you and yours are getting through the horrors of COVID OK, not to mention the other things we're seeing happening your way.

**Comment by sbillard** [comment]
There is really not a good way to do what you want. You can configure the caching algorithm to always make webp images no matter the source format, but at the present it will make only one cached version of the image. Both versions would have to be cached. I suppose you could have an on image error javascript that switched the suffix of the image to the alternate if the webp failed to load but there still needs to be the cached fallback image.

You could use the cache manager to create the images so long as the sizes it selects cover all your uses. Just set the "cache as" option and run the cache manager.

Is there some way you can think of that the server could know if the browser supports webp? (Or more specifically what image formats it supports.) If that were known then the fallback could be automated on the back-end. The other possibility would be to make the cache as option a checkbox and generate all formats selected.

We are doing well. The fires are not close to us. Most of the bad ones are in Northern California right now.

**Comment by sbillard** [comment]
After much research I have found a means to implement this. The quick answer is that it involves the `<picture>` tag and alternate sources for loading the image. 

the impact on your site it that all cached images will have two versions, a webp and whatever you have chosen as your "cache as" format. So some increase in disk usage for the site.

The implementation (below) has a new image option for "webp _fallback_ which enables this behavior. Themes that use the standard image rendering functions, e.g. `printImageThumb()`, `printDefaultSizedImage()`, etc. will provide this fallback facility. Ones which produce their own `<img src=...>` html have not been modified, at least not yet. The modifications are straight forward, but tedious and prone to error. You can get the jist of the change by searching for `WEBP_FALLBACK` if you wish to modify some of these themes.

As noted, the needed changes are error prone. I believe that the attached build has found them all, but I would recommend trying it first on a test installation until you gain confidence of its stability. You can report bugs in this ticket should you run into some.

[setup-GIT-2.00.07.01.02.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/5263927/setup-GIT-2.00.07.01.02.zip)

**Comment by sbillard** [comment]
[setup-GIT-2.00.07.01.03.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/5279414/setup-GIT-2.00.07.01.03.zip)

More progress. Fixed an issue that required double cache file generation of the base image and the webp version. This was caused by the browsers not deciding that i.php was a supported image type. For the webp source image i.webp is now redirected to i.php satisfying everyone.

Updated many <img src...> html items to use the picture element and webp fallback. There are still some to go--mostly thumbnails which are not so critical.

**Comment by sbillard** [comment]
[setup-GIT-2.00.07.01.06.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/5287177/setup-GIT-2.00.07.01.06.zip)

This is probably the final version. Could use some testing, but I have it up on my test site server and am not seeing any issues.
