### ISSUE TITLE
Idea for enhancement: Automatic "non-breaking space" for pages and post

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1213]
I dont know if it is possible or it should be rather handle by TinyMCE...

It would be fine if there will be any plugin (or another solution) which add non-breaking spaces `&nbsp;` to user specific places in text. Typical in dates, large numbers, before one-letter conjunctions and prepositions etc. at the end of the row. So they are not divided in half.

In my language we have many of these cases. With this spaces the text looks much better typographically.

**Comment by sbillard** [comment]
Do you mean like this:

<img width="576" alt="2020-09-12 09_11_59-Development Admin_ News-Articles" src="https://user-images.githubusercontent.com/2474007/92999761-5b4b5b80-f4d8-11ea-993d-57478a0eca5d.png">

**Comment by Mates-K1** [comment]
In your picture you can insert only one nonbreaking space.

I think about any solution which add nonbreaking spaces automatically. For example there is wordpress plugin https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwordpress.org%2Fplugins%2Fzalomeni%2F%23description . It is primary focused to czech languages but you can use it for another languages.

**Comment by sbillard** [comment]
I did take a look at the wordpress plugin you indicate. Unfortunately it is quite specific to wordpress and to a lessor degree, Czech. Besides which it seems to have been abandoned.

I did not find anything useful in searching the web. But it is clear from the search that there are specific language differences, so such a plugin would either be too specific to be of general use or to complex to be developed from scratch.

**Comment by Mates-K1** [comment]
There is a random screenshot from Wikipedia.
![scr](https://user-images.githubusercontent.com/7648991/93108153-c5b7f380-f6b2-11ea-8907-e42a0d835106.png)

So in english there are many cases too (dates, phone numbers, paragraphs etc.).

Of course, it's a job rather for text editor, not for the gallery.

............................
How often do you update TinyMCE please?

I found that there can be button for inserting NBSP in TinyMCE menu. 

![nbsp](https://user-images.githubusercontent.com/7648991/93112574-75dc2b00-f6b8-11ea-8600-1f6f8664ee14.jpg)

Just add `| nonbreaking` to CMS-full.php etc.

https://www.tiny.cloud/docs/plugins/nonbreaking/

If this will be default value it will be fine 👍 
And it will solve my requirement/wish a little bit.

**Comment by sbillard** [comment]
The nonbreaking plugin is active in all the "full" and "ribbon" tinyMCE configurations. At the moment, the button  is just available from the "insert" menu as in the screen shot above. The button can be added to the buttons for the "full" configurations as you note.

As to the automatic insertion, that really requires a complex grammatical artificial intelligence. If such an algorithm exists I have not discovered it. (It would have to be either PHP code or JavaScript to incorporate it in nPG.)

**Comment by Mates-K1** [comment]
When I replace spaces with nonbreaking spaces in my ebooks, that logic is simplier:

search `(space)A(space)` and replace it with `(space)A&nbsp;`
search `(space)a(space)` and replace it with `(space)a&nbsp;`
search `(space)K(space)` and replace it with `(space)K&nbsp;`
...

Yes, there is about 100 combinations and it doesnt cover numbers, dates etc.

**Comment by sbillard** [comment]
And, of course, that particular algorithm is simply arbitrary. The non breaking space could go before the character. How that would appear in the actual displayed text would depend upon where the line breaks would occur. 

Anyway, you could build a plugin that does whatever you think appropriate. The filter `save_object` would catch any updates and you could apply your algorithm to whatever fields you choose. It is really the more complex cases like dates that make a difference.
