### ISSUE TITLE
2x small visual buttons change - Backup & Restore and New album

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1219]
**Part 1**

On Backup & Restore page, each of the buttons has a different width. Can you please do the same?

![obrazek](https://user-images.githubusercontent.com/7648991/94483339-fe8bb880-01da-11eb-821f-35c7e50e3924.png)

**Part 2**

Albums page - buttons for New album and New dymamic album havent got space between icons and texts.

![obrazek](https://user-images.githubusercontent.com/7648991/94483829-c769d700-01db-11eb-973c-b3ff4dc990c4.png)

Another buttons have space:
![obrazek](https://user-images.githubusercontent.com/7648991/94483951-f718df00-01db-11eb-97c5-734ea381749e.png)

**Comment by sbillard** [comment]
Interesting problems. The backup buttons were supposed to be the same, but a typo broke that. For the album page buttons, there is a space between the icon and the text, but apparently the size of the icon obscured it. Making the icon smaller adds the visual space.

**Comment by Mates-K1** [comment]
Thanks. :)
