### ISSUE TITLE
"Clear album image cache" button - missing TITLE tag

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1220]
Mentioned button hasnt `title` tag, another buttons from the group have it.
(edit album page)

![obrazek](https://user-images.githubusercontent.com/7648991/94614353-5511f900-02a6-11eb-9ca0-f3eb0cdb7bd6.png)

**Comment by sbillard** [comment]
Another typo. Thanks for pointing it out.
