### ISSUE TITLE
Caching issue?

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1228]
I've just updated to 2.00.08.00 and I'm now seeing some weird things when I try to view full size images.

After a new directory of images is uploaded, I first see the blank nPg! error image for all of their thumbs.  A revisit to the page forces cache to create thumbnails and the thumbs populate.  Click on a thumb and I get metadata display but no full size image display.  Go forward one image using Next, go backward (Previous), full size image is now present.  On the initial display of the full size image (the one that doesn't appear), careful inspection of the page shows a microscopic version of the image, must be about 1 px by 1 px or thereabouts located where the full-size image should appear.

Have turned on debug and checked a few boxes that seem to relate to image display.  Nothing appearing in the debug log (because I think nPg thinks all is OK, it HAS displayed an image, just a microsopic one).

Older directories of images all display OK, just new uploads are having this problem.  Maybe my cache specifications for the theme are at fault and somehow the new version of nPg is more sensitive to this issue.

Just changed from my custom version of Basic theme (just bigger 1000px full-size image really) problem persists so I don't think it's my customization of Basic theme CSS that is at fault.  That CSS hasn't been modified for many months.

**Comment by sbillard** [comment]
Can you give me a link to the site?

**Comment by nerdykit** [comment]
[http://www.kitandjane.ca/gallery/travel/scandinavia-2019/copenhagen/christiania2/](url)

Try any image well down the page of thumbs and you should see the problem.  I've already viewed the first few so they are now showing full-size after the next-previous shuffle.  You can also go elsewhere on the site to see that older images are displaying OK, it's only those that have been recently ftp-ed to a new folder on the server that are displaying the problem which leads me to believe that it's either an image configuration error on my end or a problem with the image caching code.  Uploaded images are typically at 300 dpi and 1024 x 768 size (overkill on the dpi, I know).

**Comment by sbillard** [comment]
Your link is no good, but I think The problem is with the panorama plugin and its handling of uncached image links. (That is something new, before uncached links did not work at all, so the plugin forced the caching.  The plugin is somewhere setting a size for the image that is ridiculous. But works properly once the image is cached.

**Comment by nerdykit** [comment]
Let me know if you want panorama plugin disabled.

**Comment by sbillard** [comment]
I probably need to see this with panorama plugin disabled. But initial looking at your site makes me think there is a problem doing the caching. The "image" being loaded is the err-imagegeneral.png image. That image is sent if nPG thinks it is processing a video but cannot match the extension with a handled extension or if the i.php script gets an error. In the latter case if the DEBUG_IMAGE define is set there will be details in the error log. DEBUG_IMAGE can be set via the debug plugin. Note you also have to have the site in testing mode (the Mark Release button on the overview page.)

If I were to make a guess, I suspect there is also an overly active caching going on with your server. All my testing shows that the issue stems from the panorama plugin deciding to make the image size miniscule if the image was not already cached. On my site the image gets cached and the next refresh of the page shows it. On your site refreshing the page shows the i.php style link which is why I think there is some caching getting in the way. That would make it appear that the loading did not work even with panorama disabled.

The quick fix would be to put panorama back to pre-caching the images. Line 125 reads:
`if (!MOD_REWRITE && strpos($img_link, '/' . CORE_FOLDER . '/i.') !== FALSE) {`

change it to:
`if (strpos($img_link, '/' . CORE_FOLDER . '/i.') !== FALSE) {`

and things will be back the way they were. I suspect that this will be the final fix. I have no idea how paver computes the image size nor why it would be wrong only if the caching happened in real time. Maybe there are some anomalies having to do with the handling of background images--some parameters stripped off?  Might also be something specific to your images/display sizes. The DEBUG_IMAGE information would help with this.

**Comment by nerdykit** [comment]
OK.  With panorama plugin enabled, I'm seeing this...

 {29756:Fri, 09 Oct 2020 22:01:58 GMT} netPhotoGraphics v2.00.08.00-DEBUG_404_DISPLAY‑ERRORS_IMAGE_TESTING	

Loading GD

{29756:Fri, 09 Oct 2020 22:01:59 GMT}	

Loading GD

{29023:Fri, 09 Oct 2020 22:02:02 GMT}	

Loading GD

{29248:Fri, 09 Oct 2020 22:02:02 GMT}	

Loading GD

{30396:Fri, 09 Oct 2020 22:02:08 GMT}	

Loading GD

{30397:Fri, 09 Oct 2020 22:02:08 GMT}	

Loading GD

{29023:Fri, 09 Oct 2020 22:02:14 GMT}	

Loading GD 

in the debug log.

and if I try to access an image I get this....

 {30396:Fri, 09 Oct 2020 22:05:31 GMT}	

Loading GD

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

i.php(travel/scandinavia-2019/copenhagen/christiania2, CHR-24-DSCN9000-w.jpg): $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

imageProcessing::cache($imgfile=CHR-24-DSCN9000-w.jpg, $newfilename=/travel/scandinavia-2019/copenhagen/christiania2/CHR-24-DSCN9000-w_w889_h667.jpg, $allow_watermark=1, $theme=basic_for_kit) $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=NULL, $cy=NULL, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=, $image_use_side=longest; $upscale=0);

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

imageProcessing::propSizes($size=, $width=889, $height=667, $w=1024, $h=768, $thumb=, $image_use_side=longest, $dim=667):: $wprop=889; $hprop=500; $neww=889; $newh=667

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

self::cache:CHR-24-DSCN9000-w.jpg: $size=, $width=889, $height=667, $w=1024; $h=768; $cw=889, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $newh=667, $neww=889, $dim=667, $ratio_in=0.75, $ratio_out=0.75028121484814 $upscale=0 $rotate=0 $effects=

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

imageProcessing::propSizes($size=, $width=889, $height=667, $w=1024, $h=768, $thumb=, $image_use_side=longest, $dim=667):: $wprop=889; $hprop=500; $neww=889; $newh=667

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

self::cache:no crop CHR-24-DSCN9000-w.jpg:$size=, $width=889, $height=667, $dim=667, $neww=889; $newh=667; $quality=95, $thumb=, $crop=, $rotate=0; $allowscale=1;

{30396:Fri, 09 Oct 2020 22:05:32 GMT}	

Finished:CHR-24-DSCN9000-w.jpg

{30435:Fri, 09 Oct 2020 22:05:32 GMT}	

Loading GD

{30436:Fri, 09 Oct 2020 22:05:32 GMT}	

Loading GD

{29205:Fri, 09 Oct 2020 22:05:38 GMT}	

Loading GD

{30403:Fri, 09 Oct 2020 22:05:38 GMT}	

Loading GD

{30435:Fri, 09 Oct 2020 22:05:42 GMT}	

Loading GD

**Comment by nerdykit** [comment]
I haven't made your suggested change to panorama.php yet because I don't want to make multiple changes at once (bad science).

**Comment by nerdykit** [comment]
Another weird behaviour.  It looks as if, when I'm just viewing the site with admin account logged out, it can't create thumbs (and probably other cache sizes) but if I AM viewing an album thumbs page while logged in as admin in DOES update the thumb images.  Just did this with trento-bressanone directory of images and now everything is happy happy.  Got thumbs, got full-size images.  ie: it looks as if caching can only happen when viewing as an admin but thereafter the cache is fine (ie looks OK after admin is logged out).

**Comment by sbillard** [comment]
So, no errors in that debug log. Can you do another load that fails and check in your cache to see if the image actually got cached.? The name should be the $newname value in the imageProcessing::cache entry.

Caching happens only once, so if you got things cached as an admin then they stay cached. Maybe the admin thing is a clue. But SO far I cannot reproduce anything but the strange image size parameters in panorama.

**Comment by nerdykit** [comment]
Below is the log file entry when I try to view a full size image.....   Will check now to see if cache holds that image.... the only item in the cache for that file is the 100 x100 thumb. (CHR-39-DSCN9021-w_s100_cw100_ch100_thumb.jpg). 

Then just out of curiosity I did the previous-next shuffle, now I've got a full-size image to view and yes, now there's a full-size version in the cache along with the thumb version.  So it looks as if cacheing only seems to happen at the point where the full image is requested, returning to the page after attempting to view the full-image (and refreshing the page load), displays the cached image.

The log file entry below is for this image BEFORE I did the shuffle which seems to then generate a cache image.

 i.php(travel/scandinavia-2019/copenhagen/christiania2, CHR-39-DSCN9021-w.jpg): $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=

{30437:Fri, 09 Oct 2020 23:39:05 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/scandinavia-2019/copenhagen/christiania2&i=CHR-39-DSCN9021-w.jpg&w=889&h=667&cw=0&ch=0&q=95&wmk=!&limit=30&check=aeca42947da5bec484935525d5af2f81abcde8e0&cached=1175619770]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/scandinavia-2019/copenhagen/christiania2/CHR-39-DSCN9021-w_w889_h667.jpg]

    Image: [travel/scandinavia-2019/copenhagen/christiania2/CHR-39-DSCN9021-w.jpg]

{

**Comment by nerdykit** [comment]
Also just tested and if I'm not logged in as admin.  The shuffle doesn't work.  A image that will not display remains that way despite multiple shuffles and page reloads.

and here's me trying three times to view that image while not logged in as admin...

 {30403:Fri, 09 Oct 2020 23:54:44 GMT}	

i.php(travel/scandinavia-2019/copenhagen/christiania2, CHR-37-DSCN9013-w.jpg): $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=

{30403:Fri, 09 Oct 2020 23:54:44 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/scandinavia-2019/copenhagen/christiania2&i=CHR-37-DSCN9013-w.jpg&w=889&h=667&cw=0&ch=0&q=95&wmk=!&limit=30&check=5f00ab13a77c8d4e81fb79f87f7a3293b6b71c39&cached=834321886]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w_w889_h667.jpg]

    Image: [travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w.jpg]

{31412:Fri, 09 Oct 2020 23:54:46 GMT}	

Loading GD

{30403:Fri, 09 Oct 2020 23:54:47 GMT}	

Loading GD

{31347:Fri, 09 Oct 2020 23:54:47 GMT}	

Loading GD

{31347:Fri, 09 Oct 2020 23:54:47 GMT}	

i.php(travel/scandinavia-2019/copenhagen/christiania2, CHR-37-DSCN9013-w.jpg): $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=

{31347:Fri, 09 Oct 2020 23:54:47 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/scandinavia-2019/copenhagen/christiania2&i=CHR-37-DSCN9013-w.jpg&w=889&h=667&cw=0&ch=0&q=95&wmk=!&limit=30&check=5f00ab13a77c8d4e81fb79f87f7a3293b6b71c39&cached=677759568]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w_w889_h667.jpg]

    Image: [travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w.jpg]

{31347:Fri, 09 Oct 2020 23:54:49 GMT}	

Loading GD

{30403:Fri, 09 Oct 2020 23:54:50 GMT}	

Loading GD

{30546:Fri, 09 Oct 2020 23:54:50 GMT}	

Loading GD

{30546:Fri, 09 Oct 2020 23:54:50 GMT}	

i.php(travel/scandinavia-2019/copenhagen/christiania2, CHR-37-DSCN9013-w.jpg): $size=, $width=889, $height=667, $cw=0, $ch=0, $cx=, $cy=, $quality=95, $thumb=, $crop=, $WM=!, $adminrequest=, $effects=

{30546:Fri, 09 Oct 2020 23:54:50 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/scandinavia-2019/copenhagen/christiania2&i=CHR-37-DSCN9013-w.jpg&w=889&h=667&cw=0&ch=0&q=95&wmk=!&limit=30&check=5f00ab13a77c8d4e81fb79f87f7a3293b6b71c39&cached=2044492491]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w_w889_h667.jpg]

    Image: [travel/scandinavia-2019/copenhagen/christiania2/CHR-37-DSCN9013-w.jpg]

{31347:Fri, 09 Oct 2020 23:56:23 GMT}	

Loading GD

{3

**Comment by sbillard** [comment]
The "forbidden" was the key. Panorama still screws up under some circumstances, so I will apply the change I suggested. I think I know how to fix the "forbidden" error. Still some issues, though.

**Comment by sbillard** [comment]
please try this release https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by sbillard** [comment]
I really do not know why it works locally for me. It did fail on my server based test site.

**Comment by nerdykit** [comment]
Looks pretty good to me.  I went in to one of the pages of thumbs that had previously refused to cache and they cached and all full images displayed normally.  I did this while NOT logged in as admin.

**Comment by sbillard** [comment]
Sorry for the link confusion. It is easiest just to link to the DEV release tag. Then I do not have to worry about replacing a setup zip before someone has tried to download it. 

I have solved the rest of the problem (at least for my site.) At present, there is an option to limit the size of an image that i.php will create. The default is 3000. Your panorama--hurtigruten-south-pano3-KD1_4672-KD1_4680-wb--scales to be 3940 pixels wide for the standard basic theme. So, the image that was cached did not match the image that was requested.

This size limit seems obsolete. It was initially made to keep i.php from running out of memory or processor cycles, but it really did not do that since the dimensions of an image are only loosely tied to the "size" or processing requirements. The next update will remove this option. In the meantime I recommend you increase the define to something hugh so it is effectively none existant.

**Comment by nerdykit** [comment]
Thanks.  I've set it higher.

**Comment by Elinth** [comment]
Hi Stephen,

There is one part of this not working yet I believe. For my html5 videos I use jpg images with the same name as the video for displaying the thumbnail in the album. These images are currently not loaded.

**Comment by nerdykit** [comment]
I found this too but when I cleared the image cache for that album, then re-cached the images for that album the problem resolved itself.

**Comment by Elinth** [comment]
Thanks! That worked like a charm!

**Comment by sbillard** [comment]
Glad it is resolved. Should you see this happen again, what the `img src` was before the cache was cleared and then after when it works. There may be an issue where the cache name is being generated differently or something. Also does just refreshing the page make the image appear? Is it only on videos that you have seen this?

**Comment by Elinth** [comment]
It's only with the images for videos that you use a seperate image for. (For the thumbnail purpose). Embedded youtube videos are not affected. When you refresh the page the image was not loaded.

**Comment by sbillard** [comment]
Did you recache the album from the administrative pages or just allow the normal on demand recaching?

**Comment by Elinth** [comment]
I deleted the cashed images via ftp, and then I let the page load the cache itself

**Comment by nerdykit** [comment]
And for what it's worth, I used the admin pages to delete and then refresh the image cache for the album when I did my "fix" for the missing image.

**Comment by sbillard** [comment]
When there was a failure, what did get displayed? A browser missing image?

**Comment by nerdykit** [comment]
I got the large nPg red exclamation mark icon enlarged and in place of where my poster image appears after I've done the cache thing.  I think you identified it earlier as the err-imggeneral.png icon

**Comment by sbillard** [comment]
I've changed the image processor error reporting to always log the error. (It used to do that only if DEBUG_IMAGE was set.) This is in the 2.00.08.01.02 DEV release. If you get any more of these (or even if not) it would help to have this release running. There are other not related errors fixed therein as well.

**Comment by nerdykit** [comment]
I've installed the 08.01.02 DEV release and then rummaged around through old groups of images containing a video amid the group.
After a page of thumbs is clearly caching itself, if I go to a video within that group I still get the large err-imggeneral icon displayed as a "poster" for the video (a thumb for the video was generated though when the thumbs were cached).  Is there any way to make a missing video poster less ugly?  Maybe a fall back to "no poster" so the video plugin just displays the start frame of the video the way it does if "poster" is not selected in VideoJS or something less alarming to viewers who might move on instead of clicking the 'start video' arrow and at least watching the video.  For some reason, when images are cached, it doesn't seem to cache the video poster image that accompanies the video. I dunno.

**Comment by sbillard** [comment]
Do you have a debug log entry for the failed image? We really need to understand why the image generation is failing. There is really no means of predicting the failure, so no means of suppressing the poster.

I presume from your description you are using the videoJS plugin. Does the problem occur with that plugin disabled?

**Comment by nerdykit** [comment]
I can report that while all the other conventional images in the cache have full-size cache images present, the one for the video is only two thumb versions one could be the thumb of the poster and the second is a thumb with video watermark based on the name.

you ask for the link to the poster.  The poster is the same name as the video of course except a jpg instead of mp4.  The video doesn't "fail" as such.  If I click the video start arrow it plays

I can pull up just the poster with this link sequence at www.kitandjane.ca/gallery/travel/spain-portugal-2018/leon/LEO25-DSCN0662-w.jpg

although if you were cycling your way through that directory, item by item you'd hit the video really, not the poster.

Ah Ha!  The poster in question is deemed to be a panorama by that plugin and displays with the panorama slider.  But the actual poster image only has dimensions 960 x 540 (same as my video area).  Why would the poster display as a panorama ?  And now after accessing the poster image directly in trying to get the above image link for you, I've now got a nice poster image appearing for that video and yes, there's now an image of the poster in the cache but it's sizing is weird compared to all the others.    LEO25-DSCN0662-w_w1185_h667.jpg.    667 is the height of all the other standard images in the cache so in attempting to cache the image based on height it's had to upscale the 960 by the same factor, thus creating a panorama because the image is just over the 1000 px that I've got set for image display?  But I do not have image upscale allowed for image options.  I don't understand.

Now here's the log entry for that video....

 {31402:Mon, 12 Oct 2020 17:53:21 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/spain-portugal-2018/leon&i=LEO25-DSCN0662-w.jpg&w=960&h=540&cw=960&ch=540&t=1&limit=30&check=770b924410e5d0235de6de5fcecc0a2798732068&cached=1959554979]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/spain-portugal-2018/leon/LEO25-DSCN0662-w_w960_h540_cw960_ch540_thumb.jpg]

    Image: [travel/spain-portugal-2018/leon/LEO25-DSCN0662-w.jpg]

{2558:Mon, 12 Oct 2020 17:53:31 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/spain-portugal-2018/leon&i=LEO25-DSCN0662-w.jpg&w=960&h=540&cw=960&ch=540&t=1&limit=30&check=770b924410e5d0235de6de5fcecc0a2798732068&cached=908415758]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/spain-portugal-2018/leon/LEO25-DSCN0662-w_w960_h540_cw960_ch540_thumb.jpg]

    Image: [travel/spain-portugal-2018/leon/LEO25-DSCN0662-w.jpg]

{2558:Mon, 12 Oct 2020 17:53:35 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=travel/spain-portugal-2018/leon&i=LEO25-DSCN0662-w.jpg&w=960&h=540&cw=960&ch=540&t=1&limit=30&check=770b924410e5d0235de6de5fcecc0a2798732068&cached=645200750]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/travel/spain-portugal-2018/leon/LEO25-DSCN0662-w_w960_h540_cw960_ch540_thumb.jpg]

    Image: [travel/spain-portugal-2018/leon/LEO25-DSCN0662-w.jpg]

**Comment by nerdykit** [comment]
If I disable videoJS, I get a display of the first frame of the movie and the start arrow etc. and the movie will play correctly when started.  Only videoJS has the poster image feature which I like because most of my movies begin from a black screen and thus there is no "built in" starting frame with an image, just black screen.  I wonder if the html5 command for displaying a video has a 'poster frame' feature.  Will have to look into this.  Otherwise I think I'll stop making videos with a fadein from black.

**Comment by nerdykit** [comment]
I've examined a page containing a video and I can see that it is just using relatively basic form of the video tag.  Where would I make a change to try to add a poster attribute to see if we can make use of a poster with the basic html5 video plugin.

**Comment by sbillard** [comment]
2.00.08.01.03 DEV release is now available. It "might" be a fix.

Your link above does not seem to point to a video. There is none of the video html tags. Plus, I see no way that panorama can be involved with a video unless there is an error in the theme. The theme code should look something like:
`if (class_exists('panorama') && isImagePhoto()) {
   panorama::image();
} else {
  printDefaultSizedImage(getImageTitle());
}`

So it would only be invoked for photographic images.

**Comment by nerdykit** [comment]
I've just conducted a pretty definitive test.  Using only class-video and with poster image selected and present alongside the m4v video file.  I used ftp to remove just the full size image file for a movie from the cache.  Then while logged in as an admin, I visited the page for that movie, the effect was that the page created a cache file for the poster image and all was well (and there's a new entry in the cache file).  Then I repeated the same exercise while logged out and get the error image.  So clearly it can only create a cache image on the fly for a video if the viewer is logged in as an admin.  Just got your message about a new DEV version to try but will finish this anyway.

Log file for these two accesses is below.  The difference between the two entries for the beaver movie is that for the first I was logged in, then for the second, a short while later I was not logged in.



    {15932:Tue, 13 Oct 2020 20:55:40 GMT} netPhotoGraphics v2.00.08.01.02-DEBUG_DISPLAY‑ERRORS_IMAGE	

    Loading GD

    {15935:Tue, 13 Oct 2020 20:56:40 GMT}	

    Loading GD

    {15825:Tue, 13 Oct 2020 20:56:41 GMT}	

    Loading GD

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    Loading GD

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    i.php(misc/beaver, beaver-movie1.jpg): $size=, $width=960, $height=750, $cw=960, $ch=750, $cx=, $cy=, $quality=95, $thumb=1, $crop=1, $WM=, $adminrequest=, $effects=

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    imageProcessing::cache($imgfile=beaver-movie1.jpg, $newfilename=/misc/beaver/beaver-movie1_w960_h750_cw960_ch750_thumb.jpg, $allow_watermark=1, $theme=basic_for_kit) $size=, $width=960, $height=750, $cw=960, $ch=750, $cx=NULL, $cy=NULL, $quality=95, $thumb=1, $crop=1, $WM=, $adminrequest=, $effects=, $image_use_side=longest; $upscale=0);

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    imageProcessing::propSizes($size=, $width=960, $height=750, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=750):: $wprop=1333; $hprop=422; $neww=960; $newh=750

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    self::cache:beaver-movie1.jpg: $size=, $width=960, $height=750, $w=960; $h=540; $cw=960, $ch=750, $cx=, $cy=, $quality=95, $thumb=1, $crop=1, $newh=750, $neww=960, $dim=750, $ratio_in=0.5625, $ratio_out=0.78125 $upscale=0 $rotate=0 $effects=

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    imageProcessing::cache:no upscale beaver-movie1.jpg: $newh=540, $neww=960, $crop=1, $thumb=1, $rotate=0, watermark=

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    imageProcessing::propSizes($size=, $width=960, $height=540, $w=960, $h=540, $thumb=1, $image_use_side=longest, $dim=750):: $wprop=1333; $hprop=422; $neww=960; $newh=540

    {15828:Tue, 13 Oct 2020 20:56:41 GMT}	

    imageProcessing::cache:crop beaver-movie1.jpg:$size=, $width=960, $height=540, $cw=691, $ch=540, $cx=135, $cy=, $quality=95, $thumb=1, $crop=1, $rotate=0

    {15828:Tue, 13 Oct 2020 20:56:42 GMT}	

    Finished:beaver-movie1.jpg

    {15932:Tue, 13 Oct 2020 20:56:49 GMT}	

    Loading GD

    {15935:Tue, 13 Oct 2020 20:57:25 GMT}	

    Loading GD

    {15935:Tue, 13 Oct 2020 20:57:26 GMT}	

    Loading GD

    {16033:Tue, 13 Oct 2020 20:57:31 GMT}	

    Loading GD

    {15828:Tue, 13 Oct 2020 20:57:37 GMT}	

    Loading GD

    {16033:Tue, 13 Oct 2020 20:58:12 GMT}	

    Loading GD

    {17738:Tue, 13 Oct 2020 20:58:13 GMT}	

    Loading GD

    {15832:Tue, 13 Oct 2020 20:58:13 GMT}	

    Loading GD

    {15832:Tue, 13 Oct 2020 20:58:13 GMT}	

    i.php(misc/beaver, beaver-movie1.jpg): $size=, $width=960, $height=750, $cw=960, $ch=750, $cx=, $cy=, $quality=95, $thumb=1, $crop=1, $WM=, $adminrequest=, $effects=

    {15832:Tue, 13 Oct 2020 20:58:13 GMT}	

    Image Processing Error: Forbidden(2)

        Request URI: [/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&w=960&h=750&cw=960&ch=750&t=1&limit=30&check=d067050d0578b6ca95175a41be3809f3d5f805d8&cached=1166847960]

        PHP_SELF: [/gallery/npgCore/i.php]

        Cache: [/cache/misc/beaver/beaver-movie1_w960_h750_cw960_ch750_thumb.jpg]

        Image: [misc/beaver/beaver-movie1.jpg]

    {17779:Tue, 13 Oct 2020 20:58:55 GMT}	

    Loading GD

    {16032:Tue, 13 Oct 2020 20:59:02 GMT}	

    Loading GD

    {16032:Tue, 13 Oct 2020 20:59:03 GMT}	

    Loading GD

    {15825:Tue, 13 Oct 2020 20:59:16 GMT}	

    Loading GD

    English (Canada) English (United States) 

NETPH◎TOGRAPHICS version 2.00.08.01.02 | License | Forum | Support | Change log | Server date: 2020-10-13 13:59:16

**Comment by nerdykit** [comment]
I thought you wanted a link to the poster image not the video file so that's what I concocted even though the poster image is not normally displayed by nPg except in its role as support for the display of the video.

**Comment by nerdykit** [comment]
Just tried the new release and tested.  Logged out, visited movie.  Get a different error image with large red circle instead of exclamation mark.

Movie is at http://www.kitandjane.ca/gallery/misc/beaver/beaver-movie1.m4v.html

**Comment by nerdykit** [comment]
re: Panorama

Code in my version of image.php looks like this...

							if (class_exists('panorama') && isImagePhoto()) {
								panorama::image();
							} else if (function_exists('printUserSizeImage') && isImagePhoto()) {
								printUserSizeImage(getImageTitle());
							} else {
								printDefaultSizedImage(getImageTitle());
							}

**Comment by nerdykit** [comment]
The only clue that I'm seeing is that somehow, a user logged in can do something (have a video poster image cache itself on the fly) that a normal (not logged in user) can't do.  Conventional images DO cache OK, only video poster images refuse to cache (some sort of forbidden error).  Would php error log reveal anything?

**Comment by nerdykit** [comment]
Is there any debugging code that I could add to try to get some more information about the image processing "forbidden" problem that arises when an attempt is made to cache on the fly, the full-size version of the poster image for a video?  As noted previously this is not a problem when the viewer of the page accesses the video page as a logged in admin user, only when the user is not actually logged in (as is normal for all regular users of this site).

596:Sat, 17 Oct 2020 19:49:04 GMT}	

i.php(misc/beaver, beaver-movie1.jpg): $size=, $width=960, $height=750, $cw=960, $ch=750, $cx=, $cy=, $quality=95, $thumb=1, $crop=1, $WM=!, $adminrequest=, $effects=

{596:Sat, 17 Oct 2020 19:49:04 GMT}	

Image Processing Error: Forbidden(2)

    Request URI: [/gallery/npgCore/i.php?a=misc/beaver&i=beaver-movie1.jpg&w=960&h=750&cw=960&ch=750&t=1&wmk=!&limit=30&check=4c03e4f85fd27b42973b054a854c7d88a52a76d4&cached=52373697]

    PHP_SELF: [/gallery/npgCore/i.php]

    Cache: [/cache/misc/beaver/beaver-movie1_w960_h750_cw960_ch750_thumb.jpg]

    Image: [misc/beaver/beaver-movie1.jpg]

**Comment by sbillard** [comment]
Thit was finally enough information for me to recreate the issue. Will be fixed shortly in 2.00.08.03

**Comment by nerdykit** [comment]
Woo hoo!  You got it.  Poster now loads and....(goes and checks), yes, there is now a new cache item for the poster image.  Thanks.
NK
