### ISSUE TITLE
Video player typo

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1242]
Sorry, I dont know where, but I saw this while I upgraded my translation from source.

![obrazek](https://user-images.githubusercontent.com/7648991/96921390-b779a600-14ae-11eb-987d-061e59d4d6df.png)

**Comment by nerdykit** [comment]
My guess would be somewhere in the classVideo plugin setup or another video player.

**Comment by Mates-K1** [comment]
Oh.. yes, class-video plugin, line 496.
