### ISSUE TITLE
Show checkbox beside password in User admin

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1255]
Just taking a look at configuration of my test site.  What is the function of the "show" checkbox beside the admin user login info?  If I check it, the password as bullets entry in the box Password (Bcrypt) disappears and the "Repeat Password" box appears.  Checking and unchecking the show box toggles the Repeat Password entry box as if I were going to change the password but it doesn't make the password as bullets change to password in plain text so I'm not sure what it "shows".

**Comment by sbillard** [comment]
The behavior should be as follows. (And it does work this way for me.)

with show un-checked there are two password boxes, the second being the repeat password. If you type in the boxes you get bullets for the characters.  The repeat password box will be disabled until the password you type in the first box meets the password strength criteria. You must type the same password in each box for success.

With show checked, the repeat password box is removed (and a repeat of the password not required.) The characters you type into the first box are visible as typed.

In both cases, the strength of the password is indicated by the background color of the first box.

When you first display the page there are password bullets in both boxes. However these are "dummy" entries and will go away if you place your cursor in the box.

**Comment by nerdykit** [comment]
That all makes sense.  I was taking the meaning of show too literally and expected that it would just show what was being typed but of course the second password box for confirmation is not necessary if show is checked.  I didn't think it all through.
I don't think any change is required, it works the way it ought to.  Thanks.
