### ISSUE TITLE
change to info pop ups for elements to be included into themes

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1257]
I've set up a non-admin user on my test site and in order for them to be able to login from a normal album page the information pop up box told me that I should add printUserLogin_out() to my theme.   When I went to edit my theme album page I noticed that most of the other calls were of the form @call_user_func(   ), so I did it that way instead and it worked so I imagine that many of the information pop ups for plugins that require a specific element to be present on an album or image or whatever page, need to be modified to the form @call_user_func instead of how it is presented in the info pop up.

Perhaps both code styles are currently functional so this doesn't matter now but maybe it will matter down the road.

**Comment by sbillard** [comment]
The @call_user_func( )allows you to do the call without worrying if the plugin is enabled. Otherwise they do the same thing.

**Comment by nerdykit** [comment]
OK will close.  This isn't an issue.  I thought that somehow the use of the @call_user_function call was an improvement that was being phased in.  I can see now that it's really just a more compact replacement for the if's that are being used for other calls.
