### ISSUE TITLE
Bootstrap mentions infinite scroll for images but does not seem to have.

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1258]
Hi Stephen,

I don't understand something, maybe I am doing something wrong. In the theme options of the Bootstrap theme it mentions that it has infinite scroll for images (in the (i) information it says: albums, images or news), but it does not have this functionality. I only have the tick boxes for gallery, albums and news. When I select albums and go to the images in an album, at the bottom of the first page of images it mentions: "View more albums", but does not extend the additonal pages with images. I would expect it would say: "View more images" and then load the additional images from the other pages in the album that are in existence. Is this maybe an improvement? To add a tick box with images? 

Many Thanks!

**Comment by sbillard** [comment]
You would have to take this up with the theme author:https://github.com/vincent3569/zpBootstrap

But note that the information does state "This album layout does not manage albums with images and sub-albums (in that case, standard album layout is automatically used)."

**Comment by Elinth** [comment]
Will do thanks

**Comment by Elinth** [comment]
I changed the first lines of code in inc_print_infinite_scroll.php into: 
	`<?php`
		`if(isAlbumPage()) {` 
			`$containerClass= '.image-wrap';` 
			`$itemClass = '.image-thumb';`
			`$viewMoreText = gettext('View more images');`
			`$noMoreText = gettext('No more images to display');`
			`}`
		
`?>`

That did the trick, as I do not need it for albums, just images.
