### ISSUE TITLE
Minor typo in daily-summary plugin

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1259]
Lines 9 and 61 of plugin daily-summary.php   containg --> containing

**Comment by sbillard** [comment]
Thanks. I will get these corrected.

I do have a curiosity question. The line numbers you have been quoting on these typos do not match up with the ones I see. For instance, I have these typos on lines 5 and 31. Any idea why there would be such a discrepancy?

**Comment by nerdykit** [comment]
Yes, I can see that the whole file is double-spaced when I view it in my editor (BBEdit).  As I'm sure you know, there's an issue with Mac vs Windows line spacing.  BBEdit lets me declare which line end character combo to use when I save but I haven't actually done a save of the file, only a read to find the offending lines.  If I am referencing any other lines, I'll make note of the spacing in the file as I view it on a Mac and if it's double-spaced I'll at least let you know to look in the vicinity of half the value of the line number I'm seeing.
