### ISSUE TITLE
Add placeholder to the function printSearchForm 

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1261]
Hi Stephen,

Is there a way that the printSearchForm can have an option for a placeholder? I would like to have the text "search.."in the search field and once you click in the field to enter your search word it dissapears. I might be missing something but I noticed there is no option "placeholder" in the function. Is this possible to add? (See the search at the top of the Github header "Search or jump to..". as an example of what I mean.)

Many Thanks,

**Comment by sbillard** [comment]
This is fairly simple to add, so it is now in the development release: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by Elinth** [comment]
Awesome! Thanks for your kind support on this. One more question, can you make the text "search" instead of "search target"? This is translated, thats why.

**Comment by Elinth** [comment]
No bother, I changed it in the function. gettext('Search'). Thanks for your amazing support as always!

**Comment by sbillard** [comment]
You can make the text whatever you want, It is a new 9th parameter to the function.

**Comment by Elinth** [comment]
Did exactly that when I mentioned I changed it in the function! Works like a charm! Thanks for your awesome support!
