### ISSUE TITLE
Bootstrap PdfViewer window is not full page height

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1264]
Hi Stephen,

The pdfviewer in Bootstrap has a really narrow window for pdf documents to be read in the pdf reader. It is almost unreadible.  The height seems to be not sufficient. Is there a simple setting for this?

Many Thanks!

**Comment by sbillard** [comment]
Can you provide me a link? when I try this I get the full PDF document. Try https://testalbum-2.sbillard.org/test_two/sounds/?themeSwitcher=bootstrap#images-13

**Comment by Elinth** [comment]
I meant full height in the title, sorry I wrote that wrong in the title saying width. The width is ok. The window is has a very limited height on your build too. I sent you a link via gmail.

**Comment by sbillard** [comment]
It looks like the problem is with the fancybox script. The them uses fancybox when you check "Use isotope" and its album code sets the height of the image to 150 pixels. My guess it that fancybox does not know what to do when it is not displaying a real image with height and width attributes, so it just defaults to the 150 pixels. You can try changing that. I am not sure what the impact will be on image display, though.

**Comment by Elinth** [comment]
But I do not use isotope? Does it set it to 150px anyways? I do use the infinite scroll

**Comment by Elinth** [comment]
Where do I change the 150px to try it? Where is it located?

**Comment by Elinth** [comment]
There is a setting in zpbbootstrap.css for 150px height in Isotope line 196. When I change that it has no impact.

**Comment by Elinth** [comment]
And in album_isotope.php if I change the 150 in printCustomSizedImage it has no impact

**Comment by sbillard** [comment]
If you changed the 150 in all three of the choices in album_isotope.php, then we can presume that fancybox just ignores that and does whatever it does if the display is not a real image. That then would be a fancybox limitation that I cannot do anything about.

**Comment by Elinth** [comment]
I noticed that you cannot scroll down a long pdf document on mobile view as well, is that the same culprit?

**Comment by sbillard** [comment]
PDFs are displayed by the browser's native viewer. It should provide for scrolling if the PDF does not fit within the I-Frame window.

**Comment by Elinth** [comment]
Thanks Stephen, too bad the viewing window size for pdf's cannot be changed but as you mentioned it seems to be a theming issue for Bootstrap.

**Comment by sbillard** [comment]
One thing you could do is have an "album theme" for the PDF album that enable Isotope just for that album.

**Comment by Elinth** [comment]
But what I do not get is that I have the option isotope turned off in the theme. Does that matter?

**Comment by Elinth** [comment]
And I use an album theme already for my desktop theme (based on Ardoise) for document albums. I use bootstrap for mobile only. Are there any tricks for that? Bit stuck..

**Comment by sbillard** [comment]
Which exact theme (on your site) are you using for mobile? The standard bootstrap theme has a "Use isotope" option.

**Comment by Elinth** [comment]
I use a child theme of bootstrap for my mobile  view. Called LHBoot. And I have isotope turned off in this theme. When I use the regular Bootstrap theme, it has the exact same scrolling problem and narrow view pane issue with isotope turned off.

**Comment by sbillard** [comment]
I am not sure how you get to the image page. I can't get there from the front end of the standard bootstrap. But no matter. There is a fix you can make to the image.php script. Where the script prints the image change the code to read:
`<?php
if (isImagePhoto() || isImageVideo()) {
	printDefaultSizedImage(getBareImageTitle(), 'remove-attributes img-responsive center-block');
} else {
	printDefaultSizedImage(getBareImageTitle(), 'remove-attributes hundered_percent center-block');
}
?>`

Add to the zpBootstrap.css the following:

`.hundered_percent {
	max-width: 100%;
}`

So far as I can tell, this does not adversely impact standard images.

**Comment by Elinth** [comment]
Perfect! Thanks so much. The one thing I do not get is why the pdf is not scrollable in IOS. It only shows the first page. Does it work with iframe?

**Comment by Elinth** [comment]
It only scrolls the as the limit of the page scroll. It seems that the outside scroll should be deactivated so it only scrolls the document in IOS.

**Comment by sbillard** [comment]
That would be an IOS issue. On my Android I get a button to open the file. Then the whole file is viewable.
