### ISSUE TITLE
Function display news content per category

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1270]
Hi Stephen,

Is there a function that you can display news content excerpts for a specific category? I have specific family albums and wish to use an album codeblock to display news excerpts per specific family.

**Comment by sbillard** [comment]
I am not exactly sure what you need here. You can display the whole category. It is not a function, but you can look at the news.php scripts to see the `while (next_news()) {`. You will have to set the news category to the one you want listed first.

`			$_CMS_current_category = new Category($titlelink);
			add_context(ZENPAGE_NEWS_CATEGORY);
`

Where $titlelink is the titlelink of the category.

**Comment by Elinth** [comment]
Sorry I was not very clear. I would like to display the content of one specific news category in a codeblock in the album page.

**Comment by sbillard** [comment]
The answer is the same. The code to display a single category is as described above. You just have to put it into a codeblock. But is that really what  you want. Unless it is a small list of articles it will dominate the page. A better thought might be to place a link to the category.

**Comment by Elinth** [comment]
Thanks Stephen,
I tried this yesterday for a long time, couldn't get it to work. It displayed nothing. To not dominate the page, it is possible to add paginization with this?

**Comment by Elinth** [comment]
Decided not to go through with this. Thanks for your support

**Comment by Elinth** [comment]
Been thinking of this again.. Is this possible to do this via a function such as commonNewsLoop? What I am trying to achieve is to display all news on the gallery page as excerpts in my right sidebar (which is working now with the correct pagination). When clicking on a family album it opens that album and I'd like to have the news excerpts from that specific family (news category) in the right sidebar instead of all news (what is displayed in the gallery or regular pages). Each family has its own news category. I was thinking of using a codeblock in the album of the family.

**Comment by sbillard** [comment]
You can certainly call a function from a codeblock. You will have all the pagination issues as you did with the index page, so the function will need to deal with that. Codeblocks of course are script page related, so you will have to test which album page you are on to display the right content. Maybe it would be easier just to modify your album.php script.

**Comment by Elinth** [comment]
Is it possible to do something in the album page like: If the title of the news category is the same as the title of the album, then display the category news, otherwise display all news? Is something like this possible in php and would you be able to help me with this?

**Comment by sbillard** [comment]
Sure:

but you will have to do some heavy lifting.

The album title is `$_current_album->getTitle()`. You will have to look for a news category that might have the same title. `getAllCategories()` will return you an array of categories. You would loop through that array to see if any element['titl;e'] matches the album category. If you find one, then you can create a category object from the element['titlelink'].

An observation: if you managed to set the category titlelink to the album name then you could just create a new category with that titlelink. If that succeeds then you have the category, if not then there is no match.

if there is a match you would need to setv `$_CMS_current_category` to the category object you created and add the context: `add_context(ZENPAGE_NEWS_CATEGORY);` after you are done with the next_news loop you would need to remove the context: `rem_context(ZENPAGE_NEWS_CATEGORY);`

Of course, the pagination would be handled like you do with the site index page.

**Comment by Elinth** [comment]
Too much out of my php skills league. I'll drop it for good now.

**Comment by Elinth** [comment]
Thanks for the thorough response though Stephen!
