### ISSUE TITLE
Error after editing an album and clicking apply

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1281]
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/npgCore/admin-functions.php:3117)" in /srv/disk6/279773/www/site/npgCore/admin-tabs/edit.php on line 413

**Comment by sbillard** [comment]
Sorry, a bit of debugging code got left in the build.  The fix will be in the .13 build coming shortly.

**Comment by Elinth** [comment]
It works, thanks!
