### ISSUE TITLE
News Excepts in sidebar with pagination stay on the same page

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1286]
Hi Stephen,

On my site I currently use news excerpts in my sidebar.
This is what I have in my functions.php
				`<?php
				if (!empty($cat) && !in_context(ZENPAGE_NEWS_CATEGORY)) {
					echo '  ';
					printNewsCategories(', ', ' | ', 'hor-list');
				}
				?>
			 </div> 
			<br class="clearall">
		 
			<?php if (getNewsContent()!='') 
										{echo shortenContent(getNewsContent(), 200, '....<small><a href="' . getNewsURL() . '" title="' . gettext('Read more') .'" >' . gettext('Read more') . '</a></small>');}
										else 
										{echo shortenContent(getNewsContent(), 200, '....<small><a href="' . getNewsURL() . '" title="' . gettext('Read more') .'" >' . gettext('Read more') . '</a></small>');} 
									?>
			 
			<br class="clearall"></div>
		</div>`
		`<?php
	}
	if ($paged) {
		printNewsPageListWithNav(gettext('next »'), gettext('« prev'), true, 'pagelist', true);
	}
}
?>`
`
And in my sidebar I have: 

`<?php commonNewsLoop(false); ?><div class="pagination-news clearfix"> <?php printNewsPageListWithNav(' » ', ' « ', true,  clearfix'); ?> </div>`

This works really well. I just have one question. When I click on page 2 in pagination in my excerpt, it takes me to the page 2 in the news.php page. Is it possible to have this stay on the same page and load the page 2 items in the same page where the excerpts are?

**Comment by sbillard** [comment]
Ewoud:

Of course what you want is possible, just not with the standard news 
pagination function.

You could model your pagination function after the 
printNewsPageListWithNav() function.

the link you want is to your index page with a query parameter to say 
which "news page" to show. E.g. echo 
getGalleryIndexURL().'?newspage=".$page_selected;

When you load your index page you will need to set $_current_page 
=$_GET['newspage]; (if it is set) so the news loop knows what to show.


-Stephen

**Comment by Elinth** [comment]
Just wish I had more php coding knowledge... This is too difficult for my coding skills. Can I ask for your help?

**Comment by sbillard** [comment]
It really is not so hard. For the first part, make a copy of printNewsPageListWithNav() and put it into your theme functions.php script. Obviously change the name to something different.

In that function you will see a  number of instances of html_encode(getNewsPathNav($?)). The $? represents the various parameters passed to getNewsPathNav(). Replace each of those with html_encode(getGalleryIndexURL()).'?newspage='.$? Again $? should be the original parameter to getNewsPathNav() as it is the page number.

Then at the beginning of your index.php script (or whatever script shows your home page) place this code:

if(isset($_GET['newspage']) (
  $_current_page=$_GET['newspage]; 
}

**Comment by Elinth** [comment]
Hi Stephen,

I tried this and the pages are displaying in the url, however the news items stay on the first page after clicking the page numbers.
This is what I currently have in functions.php
`function printLoopNav($next, $prev, $nextprev = true, $class = 'pagelist', $firstlast = true, $navlen = 9) {
	global $_CMS, $_current_page;
	$total = ceil($_CMS->getTotalArticles() / ARTICLES_PER_PAGE);
	if ($total > 1) {
		if ($navlen == 0)
			$navlen = $total;
		$extralinks = 2;
		if ($firstlast)
			$extralinks = $extralinks + 2;
		$len = floor(($navlen - $extralinks) / 2);
		$j = max(round($extralinks / 2), min($_current_page - $len - (2 - round($extralinks / 2)), $total - $navlen + $extralinks - 1));
		$ilim = min($total, max($navlen - round($extralinks / 2), $_current_page + floor($len)));
		$k1 = round(($j - 2) / 2) + 1;
		$k2 = $total - round(($total - $ilim) / 2);
		echo "<ul class=\"$class\">\n";
		if ($nextprev) {
			echo "<li class=\"prev\">";
			printPrevNewsPageLink($prev);
			echo "</li>\n";
		}
		if ($firstlast) {
			echo '<li class = "' . ($_current_page == 1 ? 'current' : 'first') . '">';
			if ($_current_page == 1) {
				echo "1";
			} else {
				echo '<a href = "' . html_encode(getNewsPathNav(1)) . '" title = "' . gettext("Page") . ' 1">1</a>';
			}
			echo "</li>\n";
			if ($j > 2) {
				echo "<li>";
				$linktext = ($j - 1 > 2) ? '...' : $k1;
				echo '<a href = "' . html_encode(getNewsPathNav($k1)) . '" title = "' . sprintf(ngettext('Page %u', 'Page %u', $k1), $k1) . '">' . $linktext . '</a>';
				echo "</li>\n";
			}
		}
		for ($i = $j; $i <= $ilim; $i++) {
			echo "<li" . (($i == $_current_page) ? " class=\"current\"" : "") . ">";
			if ($i == $_current_page) {
				echo $i;
			} else {
				echo '<a href = "' . html_encode(getGalleryIndexURL()).'?newspage='.$i . '" title = "' . sprintf(ngettext('Page %1$u', 'Page %1$u', $i), $i) . '">' . $i . '</a>';
			} 
			echo "</li>\n";
		}
		if ($i < $total) {
			echo "<li>";
			$linktext = ($total - $i > 1) ? '...' : $k2;
			echo '<a href = "' . html_encode(getGalleryIndexURL()).'?newspage='.$k2 . '" title = "' . sprintf(ngettext('Page %u', 'Page %u', $k2), $k2) . '">' . $linktext . '</a>';
			echo "</li>\n";
		}
		if ($firstlast && $i <= $total) {
			echo "\n  <li class=\"last\">";
			if ($_current_page == $total) {
				echo $total;
			} else {
				echo '<a href = "' . html_encode(getGalleryIndexURL()).'?newspage='.$total . '" title = "' . sprintf(ngettext('Page {%u}', 'Page {%u}', $total), $total) . '">' . $total . '</a>';
			}
			echo "</li>\n";
		}
		if ($nextprev) {
			echo '<li class = "next">';
			printNextNewsPageLink($next);
			echo "</li>\n";
		}
		echo "</ul>\n";
	}
}
`

**Comment by sbillard** [comment]
Do I understand correctly? You are getting links to the index page with the ?newspage= parameter properly set but the news you show is not the correct page? what page does the nav list think you are on?

It kind of sounds like the $_current_page variable is not being set. Maybe put the code:

`if(isset($_GET['newspage']) (
 $_current_page=$_GET['newspage];
}`

Right after the globals line in the function instead of in your index.php script.

**Comment by Elinth** [comment]
Hi Stephen,

I think that the index is correctly set, the news items do not change to the correct page. The hyperlink changes correctly but the news items stay on page 1. So if I click on pagelink 2, the hyperlink changes to _site.nl/?newspage=2_ but the news items stay the same on page 1. See my gallery page for the example. The excerpts are in the right column.

**Comment by Elinth** [comment]
The only thing I see is the sticky news items

**Comment by sbillard** [comment]
I see an awful lot of debuglog entries on your site saying that an include failed. Have you corrected that issue? If so you should clean up the logs.

There is a function in zenpage/classes.php named getOffset(). Find that function and add some debugging code to see what it thinks is happening.

Before the return add:
`var_dump($_GET, $articles_per_page, $ignorepagination, $_current_page, $page, $offset);`

**Comment by Elinth** [comment]
I think I fixed that yesterday, I was attempting to input infinite scroll, this gave these errors I think

**Comment by Elinth** [comment]
Did you see the behavior of my excerpts nav. Any ideas?

**Comment by sbillard** [comment]
See my debugging suggestion above.

**Comment by Elinth** [comment]
Sorry, got distracted by the logs. This is what returns:
array(2) { ["newspage"]=> string(1) "2" ["p"]=> string(10) "PAGES:none" } string(1) "7" bool(false) int(1) int(1) int(0)

**Comment by sbillard** [comment]
This is telling us that $_current_page is not being set. Where did you put the code to set it? Check that it is correct. Also be sure that if it is being set in a function that you have declared it as global.

**Comment by Elinth** [comment]
in the functions.php, after I tried index.php. See below

function printLoopNav($next, $prev, $nextprev = true, $class = 'pagelist', $firstlast = true, $navlen = 9) {
	global $_CMS, $_current_page;
	if(isset($_GET['newspage'])) {
$_current_page=$_GET['newspage'];
}	
$total = ceil($_CMS->getTotalArticles() / ARTICLES_PER_PAGE);

**Comment by sbillard** [comment]
Presumably it should be in commonNewsLoop() as that is where the articles are printed (I think.)

`global  $_current_page;
if(isset($_GET['newspage'])) {
$_current_page=$_GET['newspage'];
}`

**Comment by Elinth** [comment]
That worked!!! Thank you so much!!!

**Comment by Elinth** [comment]
Is it hard to change the next previous links as well?

**Comment by sbillard** [comment]
You just have to make your own printPrevNewsPageLink and printNextNewsPageLink functions with the same changes you did for the other links and call your functions instead of the standard ones.

**Comment by Elinth** [comment]
function printPrevNewsExcerptPageLink($prev = '« prev', $class = 'disabledlink') {
	global $_CMS, $_current_page;
	if ($link = getPrevNewsPageURL()) {
		echo "<a href='" . html_encode(getGalleryIndexURL($link)).'?newspage=' . "' title='" . gettext("Prev page") . " " . ($_current_page - 1) . "' >" . html_encode($prev) . "</a>\n";
	} else {
		echo "<span class=\"$class\">" . html_encode($prev) . "</span>\n";
	}
}

This is what I tried. A bit stuck, can you please help me with this one?

**Comment by Elinth** [comment]
Hi Stephen, sorry to bug you with these questions (Ihope you can help me with above too). I noticed that on an album page it takes you back to the gallery. Is it possible also to have it stay on the album page. The news excerpts are in both the gallery and the album pages.

**Comment by Elinth** [comment]
I found a solution for the album pages. I just did not manage to find a way to make the prev and next links yet

**Comment by sbillard** [comment]
The function is using the getPrevNewsPageURL() function. Presumably the printNext... function uses the getNext... function. You will need to replace those as well with ones that give you the correct URL

So, instead of the changes  you made inserting getGalleryIndexURL, use your new getNext/PrevNewsPageURL() functions.

**Comment by Elinth** [comment]
Thanks Stephen!

**Comment by sbillard** [comment]
You are welcome. 

> I found a solution for the album pages (new function with getAlbumURL). I just did not manage to find a way to make the prev and next links yet

Sounds like you have increased your PHP knowledge and skills. Congratulations.

**Comment by Elinth** [comment]
Ha ha, Thanks!
Gradually getting better, but struggling now with getNewsExcerptPathNav though. Might just disable the next and prev links
