### ISSUE TITLE
Line displayed in gallery options & crop thumbnail not working 

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1289]
This line is is the top of the gallery options in admin:
// catch and discard browser auto filling of user/password so they do not go where they are not wanted! 

When editing an image and clicking the crop thumbnail button it allows me to change the crop, but after saving the newly set thumbnail it stays the same as the original.

**Comment by sbillard** [comment]
Fixed in https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.08.06.02.zip

Note for the future. It is best to make separate tickets for different problems as the ticket cannot be closed until all problems noted are corrected.
