### ISSUE TITLE
Error with FTP new images in album

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1292]
Hi Stephen, I am getting this error when I ftp new images in an album. 
The error is displayed with eacht thumbnail.

NOTICE: "Trying to access array offset on value of type bool" in /srv/disk6/279773/www/site.nl/npgCore/class-image.php on line 714

**Comment by Elinth** [comment]
sorry, images were not good.

**Comment by sbillard** [comment]
Do you still have that image? We really should handle bad images more gracefully. But I need the examples to figure out how.

**Comment by sbillard** [comment]
Well, I did not have any problems with the image you sent. If you get any more of these, let me know and save the image.
