### ISSUE TITLE
Cache image that is in the upload folder?

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1294]
Hi Stephen,

I am currently using two header images, one in my gallery and one in my album.php. These are bothe derived from the uploads folder. They are high quality images. Is there a way to cache these somehow?

Many Thanks!

**Comment by sbillard** [comment]
Your best approach is to upload the images in the size/resolution you wish to display. That is, after all, what caching does.

It is also possible to create an unpublished album that is not visible to your users, place the images there and use the image functions to show them.

**Comment by Elinth** [comment]
Thanks, I'll try the first option
