### ISSUE TITLE
Search problem with database

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1299]
With the debug plugin enabled, I'm getting a lot of debug logs with errors that seem to have some relationship to the search function or maybe my MySQLi database has become corrupted.  Things such as this appear...

MySQLi returned the error 1062: Duplicate entry 'def2a83b7a5b6b726d777041759766cc' for key 'cachetag'" in /mnt/usbdrive/webroot/public_html/gallery/npgCore/functions-basic.php on line 19

 URI:/gallery/page/archive/2018-10/5
 IP `163.172.153.229`
 theme:basic_for_kit
  trigger_error called from dbErrorReport (functions-basic.php [19])
    from db_query (functions-db-MySQLi.php [107])
      from query (functions-basic.php [407])
        from SearchEngine->cacheSearch (class-search.php [2062])
          from SearchEngine->getSearchImages (class-search.php [1737])
            from SearchEngine->getImages (class-search.php [1759])
              from SearchEngine->getNumImages (class-search.php [1675])
                from getNumImages (template-functions.php [2059])
                  from checkPageValidity (template-functions.php [4752])
                    from include (index.php [120])
                      from index.php [78]

Any ideas of where I should be looking or how to make the problem disappear (delete the cache?)

Thanks

**Comment by sbillard** [comment]
It looks like you got "lucky." There is a key to the search cache named `cachetag` that is computed as an MD5 of the search criteria. By "lucky" I mean you got two different search criteria that MD5ed to the same value. `cachetag` is currently set as a unique key, but that is an error. It should simply be an index; (All the code presumes there could be duplicates.) 

The quick fix is to go to your database administrator and change `cachetag` from "unique" to "index." The real fix needs to be done in the database handling in Setup. Until that change is released, running Setup will revert the key to "unique."

**Comment by nerdykit** [comment]
Thanks. I'll take a look into the database and see if I can make the relevant change and will avoid any updates until setup has been modified.  For now, I can also just turn off debug which should stop errors from accumulating.

**Comment by nerdykit** [comment]
If I upgrade to 2.00.09.03 will I stomp on the change of cachetag from unique to index or has Setup in that upgrade been modified to deal with that?

Thanks

NK

**Comment by sbillard** [comment]
The database fix is in 2.00.09.03 so you are good to go.
