### ISSUE TITLE
Error in debug log

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1303]
Hi Stephen,

I am getting the following error in my debug log.
I cannot seem to reset it.

 {6809:Tue, 09 Mar 2021 10:17:23 GMT} netPhotoGraphics v2.00.09.02	

WARNING: "Use of undefined constant LOGS_MOD - assumed 'LOGS_MOD' (this will throw an Error in a future version of PHP)" in /srv/disk6/279773/www/site.nl/npgCore/admin-tabs/logs.php on line 47 URI:/npg/admin-tabs/logs?action=clear_log&page=logs&tab=debug&filename=debug&XSRFToken=7cfc43d394d47193a1bdeaaed205daa9b6ae4d07 IP `86.87.111.234` gebruiker: User include called from index.php [39]

WARNING: "chmod() expects parameter 2 to be int, string given" in /srv/disk6/279773/www/site.nl/npgCore/admin-tabs/logs.php on line 47 URI:/npg/admin-tabs/logs?action=clear_log&page=logs&tab=debug&filename=debug&XSRFToken=7cfc43d394d47193a1bdeaaed205daa9b6ae4d07 IP `86.87.111.234` gebruiker:User chmod called from include (logs.php [47]) from index.php [39]

WARNING: "chmod() expects parameter 2 to be int, string given" in /srv/disk6/279773/www/site.nl/npgCore/admin-tabs/logs.php on line 47 URI:/npg/admin-tabs/logs?action=clear_log&page=logs&tab=debug&filename=debug&XSRFToken=7cfc43d394d47193a1bdeaaed205daa9b6ae4d07 IP `86.87.111.234` gebruiker:User chmod called from include (logs.php [47]) from index.php [39]

**Comment by sbillard** [comment]
It is a typo. the line should read LOG_MOD not LOG_S__MOD
