### ISSUE TITLE
Setup progress enhancement - icon label/help

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1307]
When setup runs, on this page there are four types of icons - yes, "framed" yes, no, triangle:

![obrazek](https://user-images.githubusercontent.com/7648991/110850623-49444d00-82b0-11eb-93dd-25a68609e33d.png)

But thehe isnt help for meaning. I think It would be usefull to have help there - similar to elsewhere in the gallery,

![obrazek](https://user-images.githubusercontent.com/7648991/110851878-ec499680-82b1-11eb-9b12-13870359a240.png)

**Comment by sbillard** [comment]
Ok
