### ISSUE TITLE
Setup - clicking on plugin with "Error initializing (click to debug)" state get black screen and icon

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1312]
Latest stable.

![obrazek](https://user-images.githubusercontent.com/7648991/111270967-d8df5800-8630-11eb-9ed7-f5aa3ef4617a.png)

![obrazek](https://user-images.githubusercontent.com/7648991/111270792-96b61680-8630-11eb-8099-b7583c3971d0.png)

The address is (for example) "npgCore/setup/setup_pluginOptions.php?plugin=print_album_menu&class=0&from=2.00.09.06.03&unique=1615878918"

**Comment by sbillard** [comment]
The red Xes occur when the image for the checkmark does not load. But when you clicked the red X you got the proper checkmark. This indicates that the problem is one of image load speed. (Your browser timed out before the image was loaded.) You can confirm this. If there were really an error it would show up in the Debug Log.

You can try changing the value of `Caching concurrency` in the image options. I run with a value of 15. I am not sure which direction you should move the slider. Maybe trial and error.

The only changes from the .03 Dev release that you tried and confirmed the fix for the Geo Locations is your Czech update. That should have nothing to do with this issue. Have you tried running setup again. Are the failures consistent?

**Comment by Mates-K1** [comment]
To explain - these errors have been occurring for a long time to me.

Well, today I tried run setup many times with many settings and in two different browsers (to be sure) - from 5 to 60.

I think there is no consistenci. There are two screenshots with same setting but different result:

![obrazek](https://user-images.githubusercontent.com/7648991/111379968-0addd200-86a4-11eb-96ff-16af8cff7fb8.png)

![obrazek](https://user-images.githubusercontent.com/7648991/111379562-930fa780-86a3-11eb-94e1-e709d71b6d1e.png)


If it's just an "aesthetic problem", then let it be...

**Comment by sbillard** [comment]
If there are no errors in the debug log or your PHP error log and clicking on the X gives a checkmark, then it is just ascetic. Your browser may be giving up on the images being loaded too early. 

The red X comes when the image does not load successfully. Maybe there are browser settings to tell it how long to wait. It may also be that the server side processes are getting aborted from too much processing--that is why I suggested changing the `Caching concurrency` setting. If the processes are being aborted probably a lower number would be in order. I just tried on my local install with a setting of 1 and had no red Xes.

**Comment by sbillard** [comment]
Have you tried reducing the `caching concurrency` setting?

**Comment by Mates-K1** [comment]
Yes, but I haven't seen any regular improvements.

**Comment by sbillard** [comment]
how about increasing the setting? There may also be browser settings as to how long it will wait for the image to be served.

**Comment by Mates-K1** [comment]
Latest Firefox and nPG.

Setting set to:
**1**
![obrazek](https://user-images.githubusercontent.com/7648991/133617160-cf4d14cc-9b1b-4160-9524-9c326a57729e.png)

**6**
![obrazek](https://user-images.githubusercontent.com/7648991/133617753-fe3ba53b-0b8d-423a-ba88-51762a2f5a2d.png)

**13**
![obrazek](https://user-images.githubusercontent.com/7648991/133618192-d18e55fa-def4-4ce8-b580-f860b15cb9e4.png)

**26**
![obrazek](https://user-images.githubusercontent.com/7648991/133618682-6a2846f2-9b27-444d-94fe-b32b170c98e3.png)

**45**
![obrazek](https://user-images.githubusercontent.com/7648991/133619984-5bf96574-63f4-4309-8e5c-c349e8070f65.png)

**60**
![obrazek](https://user-images.githubusercontent.com/7648991/133619416-cfa93f39-cc3a-4bb9-9309-885d99b1e337.png)

**Comment by Mates-K1** [comment]
But.... MS Edge with 30:
![obrazek](https://user-images.githubusercontent.com/7648991/133622198-742f4650-8154-4585-a699-a905224ed3e5.png)

**Comment by sbillard** [comment]
That would indicate that the browser is not waiting long enough for the images to load. Maybe this will help: https://kidsgardening.org/fix-browser-time-problem/

**Comment by Mates-K1** [comment]
Thansk for the link.
After I set timeout to 600 and Caching concurrency to 60, I get (best result in Firefox):
![obrazek](https://user-images.githubusercontent.com/7648991/133827584-4184a29b-a15c-4e2d-a68e-7a81a220031f.png)

**Comment by sbillard** [comment]
Thanks for the update. I shall close this ticket now since I don't think it is a netPhotoGraphic issue.

**Comment by sbillard** [comment]
I've done some work on pre-loading these images. You can see if it makes any difference for your installation: https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.12.05.01.zip

**Comment by sbillard** [comment]
Thanks for trying.

**Comment by sbillard** [comment]
Here is another try: https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.12.05.05.zip

This does require that your PHP has CURL enabled. That should be the case, but be sure by looking at the installation tab. There will be a notice of desired PHP modules that are not present (if any are missing.)

**Comment by Mates-K1** [comment]
```
netPhotoGraphics Setup v2.00.13.02: Sat, 06 Nov 2021 22:55:38 +0100

Warn: PHP extensions [missing]
To improve netPhotoGraphics performance and functionality you should enable the following PHP extensions: tidy

Note: File Permissions [are strict (0644)]
If file permissions are not set to strict or tighter there could be a security risk. However, on some servers the software does not function correctly with tight file permissions. If permission errors occur, run setup again and select a more relaxed permission.

Warn: MySQLi version 5.5.5
MySQLi Version 5.0.0 or greater is required. Version 5.6.0 or greater is preferred. Use a lower version at your own risk.

Note: robots.txt file [Not created]
Setup did not create a robots.txt file because one already exists.

Completed system check

Database update is not required.

Set default options

Vzhled: zenFluid instalace začala

Theme:zenFluid option interface instantiated

Theme:zenFluid setup completed in 0,2191 seconds

Completed 
```
