### ISSUE TITLE
Album that defaults to opening as a slide show?

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1313]
Is there any way to make the default for a specific album to be "open as a slide show" instead of the normal panel of thumbnails.  I only want to do this for one or two albums, not all.  If this isn't possible at present, would it be a worthwhile "feature"?  Thanks

NK

**Comment by sbillard** [comment]
You can set an "album theme" for an album. That theme could use slideshows for the album display. I don't know of a theme that defaults to slideshows, though, so you would have to code it. Effervescence/image gallery personality comes close.

It might be just as easy to modify your normal theme to test the album and display the slideshow if it is one of the albums you want that way.

**Comment by nerdykit** [comment]
Thanks. Those are both good and useful suggestions.  I might just clone my theme and see if I can tweak it for default to slideshow and then enable that theme for my special albums.  Will close for now unless I have problems with this plan.
