### ISSUE TITLE
Not able to create a new user group

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1329]
Hi Stephen,

When attempting to create a new user group - I fill in the tick boxes - when saving it does not create the new user group. It says nothing is changed. 

You can try it on my build if necessary.

Cheers

**Comment by sbillard** [comment]
The fix is in the version 2.00.11.00.04 development release. I am still testing some other things, and will update the master release with the fix in a day or so.

**Comment by Elinth** [comment]
cool thanks!
