### ISSUE TITLE
Call to undefined function putenv()

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1331]
I don't know since when (may be after nPG update?) I have following exception instead of the homepage:

> EXCEPTION (0): "Call to undefined function putenv()" in /data/web/virtuals/172972/virtual/www/npgCore/lib-i18n.php on line 116

Log says:
```
<span class="lognotice">{2220045:Tue, 29 Jun 2021 19:01:09 GMT} netPhotoGraphics v2.00.10.03.01</span>
 WARNING: "putenv() has been disabled for security reasons" in /data/web/virtuals/172972/virtual/www/npgCore/lib-i18n.php on line 118

 URI:/
 IP `31.31.74.226`
  putenv called from i18n::setLocale (lib-i18n.php [118])
    from i18n::setupCurrentLocale (lib-i18n.php [192])
      from i18n::setMainDomain (lib-i18n.php [385])
        from require_once (load_objectClasses.php [51])
          from require_once (initialize-general.php [73])
            from require_once (functions.php [12])
              from include (index.php [13])
                from index.php [78]
```

Stephen, do you have any solutions, please?

**Comment by sbillard** [comment]
Probably your host has reconfigured your PHP service. The error says that `putenv()` has been disabled for security reasons. (I am not sure why they would do that, these environment variables may be necessary for language selection to work!)

Anyway, most likely the solution is to change the three lines that around line 116 of lib-i18n to use `@putenv` in place of just `putenv`. There are other places `putenv()` is used that may need to be changed as well.

Please let me know if this works and I will make the change official.

**Comment by sbillard** [comment]
This website may also be of use: https://stackoverflow.com/questions/51812996/putenv-has-been-disabled-for-security-reasons-when-executing-composer-commands/51813262

I looked and did not find any other uses of `putenv()` besides the three in lib-i18n.

**Comment by sbillard** [comment]
I found a way to disable putenv() in my local test environment. The proper fix is:
`if (function_exists('putenv')) {
			putenv("LC_ALL=$locale");
			putenv("LANG=$locale");
			putenv("LANGUAGE=$locale");
		}`

**Comment by Mates-K1** [comment]
I already remembered... it was probably caused by switching from PHP 7.3 or 7.4 to PHP 8. The provider probably has different settings for this version. I can easily revert to the previous version.

Thank you very much, your fix works. :) So I can use PHP 8.0.
