### ISSUE TITLE
New Installation problems

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1335]
I'm trying to set up  nPG for a friend.  The server storage is a USB thumbdrive attached to a raspberry pi running the latest Raspberry pi os (buster).

When I browse to extract.php I get the screen confirming extraction of the files and then nothing further (no setup).  Checking the directory shows that a zip file with a name beginning with a long string of numbers has been created but that's it.

I figure that the problem is in the linux and not nPG but I'm having problems trying to figure out what's wrong with my server setup.  I imagine that extract.php begins by extracting the nPG files as a zip archive and then unpacks from there but the process seems to stop at that point.

My web server works, php and mysql work.  extract.php (which has been set to owner www-data and permissions 775 is in place, the whole server path is set up more or less identical to my own working version of nPG but something isn't right.

Any ideas what is going wrong with my setup?  Will see if I can find the php error log and see if I can learn anything from it.

Thanks

NK

**Comment by sbillard** [comment]
From this description I would guess that the PHP ZipArchive class is either not present or is failing for some reason. The file you see is the zip archive extracted from the extract.php file. It normally gets removed after a successful unzip. Anyway, check the Apache error log as well.

Not sure exactly what you are seeing. The sequence of events should be:

Start extract.php. You get the message that it is extracting the files.
extract.php redirects to extract.php?process and does the actual work.
Once the files are extracted, it displays the setup link and attempts to redirect to it.

So, if you aren't getting the setup link displayed something went wrong in the extract process. If ZipArchive threw an error or returned one the error should have been displayed. So my best guess it that ZipArchive does not exist. The extract program does not check for that. (It is code derived from createziparchive (c) 2008 iljitsch@mail.com cookiepattern.blogspot.com) Maybe it should make that check.

let me know what you learn.

**Comment by nerdykit** [comment]
I made the following test.  Created a simple zip file and then attempted to unzip with ZipArchive using instructions found online.  My test phpunzip.php file included instructions to display all errors and I got this error message.

  Fatal error: Uncaught Error: Class 'ZipArchive' not found in /mnt/usbdrive/webroot/public_html/gallery/phpunzip.php:13 Stack trace: #0 {main} thrown in /mnt/usbdrive/webroot/public_html/gallery/phpunzip.php on line 13

Now my php installation was just standard, done with apt install and it SHOULD be there but it looks like it's not.

I've no idea what to do next.  Try re-install of php (it was 7.3)?  I just followed standard instructions for building a basic LAMP machine and got no errors as i was doing it.

**Comment by nerdykit** [comment]
Further...

I wonder if php not thinking it has ZipArchive Class is a path thing.  The php installation is on the internal memory of the raspberry pi (the microSD card) while the php program calling it resides on the mounted removable usbdrive.  I don't have any problem like this with updates to my usual nPG installation which is fairly similar (raspberry pi server and removable USB hard drive).

**Comment by nerdykit** [comment]
php -i | grep -i zip

reports    ZIP-based phar archives => enabled

and a lot of other stuff so it looks as if ZipArchive is installed

**Comment by sbillard** [comment]
Your error message says it all--there is no ZipArchive class present in the installation. Can't help you with that, I am not a PHP/Apache expert. ZipArchive should be an internal part of PHP, so if PHP is there and configured correctly ZipArchive should be there as well. But obviously it is not! Maybe this will help https://www.php.net/manual/en/zip.installation.php

I would try to install PHP version 7.4.x or maybe better 8.0.x. PHP 7.3 ended active support 4 months ago and will loose security support in 3 months.

**Comment by nerdykit** [comment]
I just ran apt install php-zip and my tester now works and successfully unzipped my test archive.  I hope that there aren't other missing classes out there waiting to bite.  Will close for now and try the installation again.  Thanks

**Comment by nerdykit** [comment]
Just a final bit of feedback. In setting up a new server I did a more or less "standard" installation of php as outlined in several web sites with instructions for a LAMP server. That initial installation of php was lacking about eight components necessary for nPG. Among them ZipArchive, GD support, cURL, XML, mbstring, tidy, bz2, intl and probably a couple of others that I've forgotten.  ZipArchive missing meant that the new installation could not get beyond the first level and setup was never reached to report on the other missing classes. Also mod-rewrite had to be enabled for Apache2 despite the fact that setup reported it as being available. Setup caught all of the others once it could run after the initial unpacking of the zip archive.

**Comment by sbillard** [comment]
I have updated the install extractor to check for ZipArchive. It will now die with a message if it is not present. (This is the first time ever that someone has reported it missing. Presumably setup will report the other items as missing. They are not really critical. Of course if you do not have GD support you better have Imagic! 

I do not understand how Setup could have reported mod rewrite available if it was not working. I will check into that.

**Comment by sbillard** [comment]
I found the problem with the mod_rewrite check. Seems that nPG was too smart for its own good. Setup reset the mod_rewrite option as it should in case the redirect did not work. Then it called the generic admin link function which dutifully noted that mod_rewrite was reset and generated a query parameter link to the script that sets mod_rewrite if it gets executed. Naturally that link worked!
