### ISSUE TITLE
Problems with blue "i" pop-ups on wide screen layout

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1337]
Not sure if this is a bug or not... when I'm in a Theme options page if the browser window is fairly wide, the available options display in two columns, left and right.  As I move my cursor over the blue information "i" for help about an option in the left-hand grouping, an information pop-up appears but for all of the options in the right-hand grouping, the "i" is completely inactive.  No hover pop-up, no click. Nada

But, if I drag to reshape my browser window into a narrower configuration so that the options re-distribute into a single long group scrolling down off the screen, all of the blue i icons are correctly active although some of the options are not initially visible of course until I scroll down to get to them.

Behavior seems the same for Firefox and Safari.

**Comment by sbillard** [comment]
Can you try this with Chrome?  I do not have Firefox nor Safari browsers. I have tried in Chrome and MS Edge and all is working. I can stretch my browser window so I get two or three columns. everything works for me for all number of columns. 

Anyway, the display/hidden are controlled by CSS:

`.option_info:hover > div {
	visibility: visible;
	height: auto;
	overflow-x: visible;
	overflow-y: visible;
	min-height: 40px;
}`

So about the only thing I can think of is that somehow the browser does not consider you hovering over the "i".

**Comment by sbillard** [comment]
Should have asked also if this is only on the theme option page.

**Comment by nerdykit** [comment]
OK, all OK with Chrome no problems.  non-issue on an iPad since the screen isn't wide enough to force two column display of the theme options.  Weird, now Firefox is just fine.  So the only browser showing problems is Safari and I now can see that it's some sort of css issue that doesn't arise with Chrome or Firefox but does with Safari because in actual fact the pop-ups DO appear, just not beside their relevant i but instead at the bottom of the screen and furthermore, when I hover over a right hand column i from an item near the top of the column the mis-placed pop-up is higher up than pop-ups for i's further down the list.  ie: they've got vertical right except that they're all appearing way down at the bottom of the screen.  Since it's only Safari, I don't think it's worth wasting any of your time on this.  I'll close this "issue".

**Comment by sbillard** [comment]
Safari is probably not handling the columns properly. Thanks for the update.
