### ISSUE TITLE
WEBP exif exception

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1338]
When I convert JPG with some exifs to WEBP, I get:

`EXCEPTION (0): "Division by zero" in /data/web/virtuals/172972/virtual/www/npgCore/exif/exif.php on line 1444 `

[jpg_and_webp_images.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/7173424/jpg_and_webp_images.zip)

**Comment by sbillard** [comment]
Are you getting this error on the WEBp image or the jeg? I loaded up the WEBp image and got no errors.

**Comment by Mates-K1** [comment]
Only webp.

I get this error after upload webp image via FTP - just reload album page (with img thumbs). After another page reload I get image thumb but without title. 

![obrazek](https://user-images.githubusercontent.com/7648991/133616192-e3f5d281-f51d-4126-a581-ae081259cc0c.png)

**Comment by sbillard** [comment]
The error will prevent further processing of image metadata. So the missing title is not surprising.

This is one of those "impossible" errors given reading the code. Maybe you can modify the code to get us some more information.

`function convertToFraction($v) {
	if ($v == 0) {
		return "0";
	} else if ($v > 1) {
		for ($n = 0; $n < 5; $n++) {
			$x = round($v, $n);
			if (abs($v - $x) < 0.005) {
				break;
			}
		}
		return $x;
	} else {
		for ($n = 1; $n < 100; $n++) {
		
		       debugLogVar($v);
		

			**$d = round(1 / $v * $n, 0);**
			if (abs($n / $d - $v) < 0.00005) {
				break;
			}
		}
		return "$n/$d";
	}
}`

For the "Division by zero error on line 1444 either $v or $n would havae to be zero. The first is prohibited by the initial if statement. The second should not happen as $n starts ata 1 and increments. The DebugLogVar() call will tell us what the values are.

**Comment by Mates-K1** [comment]
```
 {14265:Fri, 17 Sep 2021 12:35:53 GMT} netPhotoGraphics v2.00.12.00	

  'var' => '0,008', 
```

**Comment by sbillard** [comment]
Ah, the dreaded European number representation.  Can you try adding `$v =floatval($v);` at the beginning of the function? If that does not work try `$v = str_replace(',', '.', $v);` instead.

**Comment by Mates-K1** [comment]
Yeah, first solution works!! 👍 Many thanks.

**Comment by sbillard** [comment]
Turns out that the first code only masked the error. I have updated the repositories with the correct fix. The floatval() change resulted in improper exposure exif.
