### ISSUE TITLE
How to password protect an album

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1343]
I'm attempting to advise a friend who wants to have one of his albums of photos password protected.  I know that it can be done via .htaccess but I think that nPG can do it too.  I've read the documentation which states that an album can be protected by setting a password for it (without naming a specific user) but when I do this by clicking the lock symbol immediately under the text entry area for the album description and entering a new password, I'm getting a locked symbol on the album alright but when I attempt to test and view that album, the login entry box asks for both a name and password and nothing entered works.  I'm probably not doing it the right way, I dunno.  I'm trying this on my test version of nPG and using basic theme.  Thanks

NK

**Comment by sbillard** [comment]
The presence of the user field _**should**_ be controlled by the security option _user name_. (You might want your registered users to be able to log on to the site from that screen. In that case there needs to be a user field. Guests can just ignore the field, but of course they may need to be told that, presumably when you give them the album password.

Unfortunately there are a couple of bugs that make this not happen. I have fixed those and will get them released shortly.
