### ISSUE TITLE
GPS display error again

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1361]
Lets have image with GPS and english (US) and czech language in gallery.
![jazyky](https://user-images.githubusercontent.com/7648991/140624487-2aca17e6-3783-441a-8e53-9e81015d42c5.png)

GPS informations in image are:

![Screenshot 2021-11-06 at 22-24-36 Admin Albums-Images](https://user-images.githubusercontent.com/7648991/140624502-c74b98f7-e7ec-47d2-a460-8f5e51b5aede.png)

Change language to czech.

Click "Použít" (Apply).

GPS informations are:

![Screenshot 2021-11-06 at 22-32-53 Administrace Alba-Fotografie](https://user-images.githubusercontent.com/7648991/140624574-b8c79d1f-c853-4a6d-b8f4-5bc6bba9d6a6.png)

And location on the map is wrong.

**Comment by sbillard** [comment]
Can you please add the line
`
		varDebug(['$dec' => $dec, '$d' => $d, '$tempma' => $tempma, '$min' => $min, '$sec' => $sec]);

`
just before the return statement in class-image:toDMS() and post the output form the above pages? Is the location on the map correct if the language is English?

**Comment by sbillard** [comment]
Do any other images exhibit this behavior? I have looked at some images I think you have provided me in the past and do not see the issue on my sites. See https://netphotographics.org/openAdmin/npg/admin-tabs/edit.htm?page=edit&tab=imageinfo&album=gps

**Comment by Mates-K1** [comment]
![obrazek](https://user-images.githubusercontent.com/7648991/140659301-04a14353-e1b9-45e9-b932-1821c0b1dd76.png)

**Comment by Mates-K1** [comment]
When the gps coordinates are changed, they are displayed incorrectly even in English. The correct display can be corrected by refreshing the metadata. So changing to czech language (may be another language too) and pressing Apply cause it.

**Comment by Mates-K1** [comment]
And yes, in your gallery I cant reproduce it.

**Comment by sbillard** [comment]
Yes, if you save the image when the GPS coords are wrong they will be saved that way. If it is only this image that has the problem we can put it into my gallery and see if it has the issue there.

But first, lets explore the situation in a bit more detail. Refresh the metadata so that the English has the correct display. Save the image. Then produce the debug output for both English and Czech. Do not save the image in between changing the languages.

**Comment by Mates-K1** [comment]
I can reproduce it on my images uploaded in 2016 too... propably on any image with GPS in gallery.

Result is the same (see image)...
![obrazek](https://user-images.githubusercontent.com/7648991/140824487-6ff4bcea-6b25-4348-95d0-6633b4007ea1.png)

... until I save image:
![obrazek](https://user-images.githubusercontent.com/7648991/140825005-ecffbca9-4dea-435b-a439-8458b9304069.png)

**Comment by Mates-K1** [comment]
Language:

- Dutch - bug,
- Danish - bug,
- **Japanese - OK,**
- Spanisch - bug,
- French - bug,
- German - bug, 
- Italian - bug,
- Slovak - bug.

**Comment by sbillard** [comment]
I think I may know what the problem is. According to my research, the PHP function `is_numeric()` does not properly deal with European number formats where the decimal point is a comma. If that is really the cause, then this build should fix the problem. https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.13.02.01.zip

**Comment by Mates-K1** [comment]
I don't know if it's related, but if the longitude has three digits, it doesn't convert and the field is blank.
And in some cases just two digits and it won't show up.

![obrazek](https://user-images.githubusercontent.com/7648991/140829360-78c19b09-229a-430d-a1ec-9a215e086fbf.png)

![obrazek](https://user-images.githubusercontent.com/7648991/140829248-e646c368-2b79-46da-a084-c3894d0fcc44.png)


and

![obrazek](https://user-images.githubusercontent.com/7648991/140829915-eb8d0527-6eb3-462b-bb8c-eb9c40803f90.png)


![obrazek](https://user-images.githubusercontent.com/7648991/140829866-677e6945-f52f-46e3-816e-36c2a6506754.png)

**Comment by Mates-K1** [comment]
YES, it works for my images! Many thanks.

I found one location that does not work after fix and hasnt three digites:
![obrazek](https://user-images.githubusercontent.com/7648991/140834906-8f914654-fa47-4f55-b95c-e3dd09cf6b61.png)

**Comment by sbillard** [comment]
Related, but the fix needed a bit more work: https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.13.02.02.zip

**Comment by Mates-K1** [comment]
Works! :) Thank you.

**Comment by sbillard** [comment]
You probably will need to refresh the metadata on all your images to be sure they are set correctly.

**Comment by Mates-K1** [comment]
Yeah, I was thinking... it's running now. 

Once again, thank you very much... and good night (1 AM here :) ).
