### ISSUE TITLE
Files missing? 

### ISSUE THREAD

**Issue by Anniedee** [netPhotoGraphics/netPhotoGraphics#1370]
I'm trying to do a clean install but having problems with redirect error and can't get setup to run. 
I asked my server people to look into it and they couldn't find any server issues, they think it's an application problem. They did notice these errors... the note is from my tech support people:

Also we noticed from the error log as when we load the install link you provided its looking for files like below from npgData folder but those files doesn't exists. Give the details to your application provider.

/npgData/debug.log
/npgData/npg.cfg.php

So my question is, do I need to change the properties on the npgData folder? Maybe the files couldn't be written to it. 

I also see that the error log has nearly 7500 lines of entries from today.

**Comment by Anniedee** [comment]
So I changed the permissions on the npgData folder and a little bit happened but not much. I got this error next:

USER ERROR: "MySQLi Error: ( SHOW GLOBAL VARIABLES LIKE "max_user_connections"; ) failed. MySQLi returned the error 1045: Access denied for user ''@'localhost' (using password: NO)" in /home/game/public_html/npgCore/functions-basic.php on line 19

**Comment by Anniedee** [comment]
I downloaded an older version of NetPhotoGraphics (setup-master-2.00.04.00.zip) and that version is running the setup very well so I'll stick with that for the time being.

**Comment by sbillard** [comment]
That error is indeed a bug in the current version of netPhotoGraphics. It will only happen when the database credentials are not setup or are incorrect. I will have to test clean installs more often!

You should be able to do upgrades once you have a working install.
