### ISSUE TITLE
Broken demo link

### ISSUE THREAD

**Issue by SubJunk** [netPhotoGraphics/netPhotoGraphics#1381]
Somehow when I went to the website I ended up on https://netphotographics.org/pages/privacy-policy.htm which I accepted, but the "Demo" link on the right links to `demo/` which is broken as it takes me to https://netphotographics.org/pages/demo/
It should be `/demo/` instead

**Comment by sbillard** [comment]
Thanks, I have fixed this now.

**Comment by sbillard** [comment]
For your information on Zenphoto #1312 and #1313:

netPhotographics has neither problem. They were fixed ages ago. (Among other things, setup should not be doing any database updates if the database is already in the correct condition. netPhotoGraphics does check if anything needs to be done.)

I have a fix in process for #1311 as well which should be available soon. The user will see a checkbox list of the possible fields if he selects "custom" ordering. This change should be up in the development build by tomorrow.

Also there are some significant improvements in the administrator table handling and other SELECT * queries in the current development build.
