### ISSUE TITLE
Dates not displaying properly

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1397]
After upgrade to 2.00.14.05 dates on album "title pages" now show % entities instead of actual dates.  This is new.

See image....
![Screen Shot 2022-05-01 at 10 02 24 AM](https://user-images.githubusercontent.com/3220548/166156639-ee1c2998-5955-480d-bc5b-3f95a2d412a6.jpg)

Thanks

NK

**Comment by sbillard** [comment]
PHP 8.0 has deprecated the strftime() function that nPG used. So the code was replaced to use the date() function. Unfortunately the "formats" used by these two functions are not the same. That was the cause of the problem. I have fixed the formats but at present your saved format will become "custom" and still will not work. I can provide a build that will let you fix the issue by re-assigning the date format.

In the mean time I am working on the translation table to "fix" the old style format strings so that old options continue to work.

**Comment by sbillard** [comment]
The development build https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.14.05.02.zip contains the complete fix

**Comment by nerdykit** [comment]
OK, as  I understand it, my date entries are now "corrupted" (sort of) and will require fixing or will simply installing the new .05.02 dev version fix things automatically.

Also, if my database holds bad values, will updating to php8.0 make things work OK?  I might consider that option if I can find a clear indication that upgrade of php version is possible for my version of linux.

**Comment by sbillard** [comment]
Hard to say. WIth https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.14.05.04.zip setup will "try" to fix the old strings. But custom formats will certainly have to be re-done with the new formatting patterns. There is a link to them in the info on the option. PHP 8 is not needed. The change was needed in order not to get errors if you upgraded to PHP 8.0. (BTW, don't bother with PHP 8.1. I am having some really strange issues with it. things fail with no repeatability nor error indicators.)

If you have a problem with one of the standard strings, changing, savinging the option, and changing it back will fix things.

**Comment by nerdykit** [comment]
Your version 2.00.14.05.04 solved the problem.  No further fixes required.  Thanks

**Comment by sbillard** [comment]
Thanks for the confirmation.

**Comment by Mates-K1** [comment]
IDK, may be it is related - archive page:
![search](https://user-images.githubusercontent.com/7648991/167098530-77ef18b1-a32c-4496-9844-d9a832f3b551.jpg)

nPG 2.00.14.06, propably all themes archive page

**Comment by sbillard** [comment]
Definitely related. I'll have a fix soon.

**Comment by sbillard** [comment]
I believe that the development build fixes all these cases. https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.14.06.02.zip
