### ISSUE TITLE
PHP 8.1 Errors

### ISSUE THREAD

**Issue by Ipstenu** [netPhotoGraphics/netPhotoGraphics#1406]
I switched to PHP 8.1 for some tests and right away ran into issues:

```
EXCEPTION (8192): "substr(): Passing null to parameter #1 ($string) of type string is deprecated" in /home/DOMAIN/gallery/npgCore/lib-encryption.php on line 56
URI:[doesn't matter, happens on all]
IP REDACTED
substr called from rc4 (lib-encryption.php [56])
from encodeNPGCookie (functions-basic.php [816])
from getNPGCookie (functions-basic.php [801])
from i18n::setMainDomain (lib-i18n.php [328])
from require_once (load_objectClasses.php [51])
from require_once (initialize-general.php [73])
from require_once (functions.php [12])
from full-image.php [13]
```

Looking into it, it appears that in npgCore/lib-encryption.php in function rc4, there are cases where $message is null, which results in the errors. If I put in an "If null..." check, it got around it, but no idea what else that may make barf.

As soon as I did that, I got new errors for /npgCore/extensions/common/gitHubAPI/Github/Paginator.php

That's when I rolled back :)

**Comment by sbillard** [comment]
Thanks for this information. First, I do not think PHP 8.1 is ready yet for prime time. I haven't seen this error, but then I do not tie my cookies to the IP. You can avoid this by turning off cookie security. The fix will be to the encodeNPGCookie function.

`function encodeNPGCookie($value) {
	if ($value && defined('IP_TIED_COOKIES') && IP_TIED_COOKIES) {
		return rc4(getUserIP() . HASH_SEED, $value);
	} else {
		return $value;
	}
}`

What were the Github/Paginator.php errors? I have not seen these either.

But I do have an inconsistent problem running setup. Sometimes it runs sometimes it does not. When it does not the place it stops is not consistent. There are no errors in any log I can find, either. I am trying PHP 8.1.6 on apache 2.4.53 on a local Wamp installation.

PHP 8.0 runs fine in the same circumstances.

**Comment by sbillard** [comment]
I have now installed PHP 8.1.7 and  updated my apache installation. I no longer have the setup issue, so I think PHP 8.1 can now be "blessed."

There seem to be a bunch of places where "NULL" is no longer allowed as a parameter to in-built PHP functions. Unfortunately there is no good way to find these other than exercising the code. If you are game, it would help find these if you could run a test site on PHP 8.1. I run into one of these issues a couple of times a week, so I am not sure that I would put PHP 8.1 into production just yet.

**Comment by sbillard** [comment]
Please note that the nature of the problems introduced by PHP 8.1 deprecating use passing of a NULL value to various functions means there is no simple way to find all the possible instances. To the best of my testing ability all the main-stream issues have been fixed. But there likely will be edge conditions that are not fixed. Those will be fixed as they are found.
