### ISSUE TITLE
elFinder version

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1407]
Just read this on the elFinder GitHub site...

WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.60 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER.

It looks to me as if the installed version of elFinder in nPG is 2.1.59 so just shy of the mark but nonetheless....

(actually the word  "PUBLIC" in the above may mean that no update is actually necessary since elFinder runs only in the Admin mode of nPG)

Thanks

NK

**Comment by sbillard** [comment]
Thanks for noticing this. The older version is probably safe in the nPG environment (unless you have registered users who want to hack their site and have upload permissions.) But there is also no good reason not to update elFinder to 2.1.61. I need to do some regression testing and then will release that change to the development builds.
