### ISSUE TITLE
Cannot get a new installation to get started

### ISSUE THREAD

**Issue by Anniedee** [netPhotoGraphics/netPhotoGraphics#1408]
I downloaded the latest zip file. and extracted all the files. 
to start setup, you go to  /npgCore/setup.php  -- isn't that right? 

Error message is:
This page isn’t working right now
(http://mywebsite.com/) redirected you too many times.
To fix this issue, try [clearing your cookies]
ERR_TOO_MANY_REDIRECTS

======================

Originally I tried using the installation file with the extract.php file in it and that didn't start either. 
I'm not a newbie. This is just not going according to plan. 
I'm using PHP 7.4 on this website. And doing an all-new install because my version of netphotographics is really old. In fact, it's still zenphoto20  so it's past time to upgrade them all. I hate to do it because they've been working great all these years. 

Cyndy

**Comment by Anniedee** [comment]
My server people said the error log was looking for the zp-core folder. That's when I was using the setup-master-2.00.14.08.zip file.  Since I wasn't getting anywhere with that, I switched to the netPhotoGraphics-master.zip but the zp-core error might be in both of them?

**Comment by Anniedee** [comment]
Yes, the server people have told me that the error, again, is looking for something in the zp-core folder. 

++++
[14-Jun-2022 03:09:49 UTC] PHP Warning: include(/home/MYWEBSITE/public_html/zp-core/index.php): failed to open stream: No such file or directory in /home/MYWEBSITE/public_html/index.php on line 33
[14-Jun-2022 03:09:49 UTC] PHP Warning: include(/home/MYWEBSITE/public_html/zp-core/index.php): failed to open stream: No such file or directory in /home/MYWEBSITE/public_html/index.php on line 33
[14-Jun-2022 03:09:49 UTC] PHP Warning: include(): Failed opening '/home/MYWEBSITE/public_html/zp-core/index.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/MYWEBSITE/public_html/index.php on line 33
++++

**Comment by sbillard** [comment]
Did you get your install done? The extract file is the best way to install upgrades. 

From the error messages you show, sounds like the root index.php file did not get replaced by the new install. The netPhotoGraphics-master.zip file will almost always be the same as the most recent setup-master.zip file. Sometimes it may be a few commits ahead, when the updates don't warrant making a new setup-master.zip.

If you are still having troubles I would suggest removing the root index.php file and the zp-core folder if it exists. then run the extract.php file.
