### ISSUE TITLE
Permissions issue with new install on *nix host

### ISSUE THREAD

**Issue by JimBrown** [netPhotoGraphics/netPhotoGraphics#1429]
There appears to be a permissions issue with a brand new install on a *nix system using extract.php. The extraction process creates the folder npgData with permissions 645 (if I recall correctly). This appears to cause setup to go into a redirect loop because it can't write to that folder. After changing the permissions on npgData to 744, setup will then run and do its thing.

However, either setup or admin will then complain about the security of the debug.log file. Manually changing the permissions on debug.log file from 644 to 600 will fix that.

**Comment by sbillard** [comment]
Did you check any other empty folders for what their permissions were? Albums folder? Upload folder? It is the zip file extract that creates these folders. Not sure why the *nix system would assign those permissions--folders should always have the execute permission.

**Comment by sbillard** [comment]
This was a really obscure problem. Please try the [DEV ](https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.15.01.01.zip)release to verify it fixes things on your host.
