### ISSUE TITLE
Officiel website bug

### ISSUE THREAD

**Issue by youssefelmourabit** [netPhotoGraphics/netPhotoGraphics#1453]
the site https://netphotographics.org/ does not work

**Comment by sbillard** [comment]
It is working at present. The site has been experiencing some issues with max connections recently. I do not know the cause, but it is likely a problem with the hosting site. (I have seen it on some of my other sites as well.) It is possible it is a denial of service attack, but there is no evidence of that in the logs.

**Comment by sbillard** [comment]
As there is no further on this, it is closed.;
