### ISSUE TITLE
Upload here works the same as upload

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1459]
When you are in an (image) album and you select the menu item "Upload here". It doesn't really show that it is uploading in the specific album that you were in. In "Upload here" you have to select from a full list of albums to what album you wish to upload, which seems illogical. Therefore the "Upload here" functions the same as the "Upload" menu item, which seems like the "Upload here" functionality is not working as it should.

**Comment by sbillard** [comment]
I have a fix for the uploaders other than elFinder. That is a bit more complicated fix.

**Comment by Elinth** [comment]
Awesome, let me know if I need to test something.

**Comment by Elinth** [comment]
Thanks! That works well
