### ISSUE TITLE
Sorting sub-albums not working

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1460]
The sorting of sub-albums, by dragging and dropping them to re-order them is not working. I have tried this in Firefox and Edge. Both not working.

**Comment by sbillard** [comment]
This is fixed in the development builds. The problem was that jquery  nestedSortable needed to be updated. You could copy that file to your installation or try the development build.

**Comment by Elinth** [comment]
Thanks! That worked!
