### ISSUE TITLE
Newly uploaded WEBPs are without GPSs and EXIFs

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1469]
WEBP images uploaded on 29. 12. 2022 have GPS coordinates, images uploaded today do not show them.

Have there been any related changes in 17.03 and 17.04?

There is one of them (just rename to WEBP).
[001.pdf](https://github.com/netPhotoGraphics/netPhotoGraphics/files/10460813/001.pdf)

Plus the gallery won't process my exif information from this format.

**Comment by sbillard** [comment]
I do not know of any changes that might impact this. Mostly the changes were PHP deprecation fixes.

But, more interesting is that I can make copies of WEBP images I have that have GPS data and the data is imported from them. (If I remember correctly, I got the image from you: pokus.webp.) So there is something different about the new image you sent. I can look at it with Adobe Bridge and it shows GPS data. So probably something is different about how it is stored that the nPG software does not properly handle.)

What can you tell me about the image?

**Comment by sbillard** [comment]
I have examined the metadata for the image you provided. The metadata is missing a description closure tag.

Your image metadata:
`<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.5.0"> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:exif="http://ns.adobe.com/exif/1.0/" xmp:CreatorTool="Zoner Photo Studio 18" exif:GPSLongitude="16,28.702419E" exif:GPSLatitude="50,5.164600N" exif:GPSAltitude="407000/1000" exif:GPSAltitudeRef="0"/> </rdf:RDF> </x:xmpmeta>                          `

A correct image metadata:

`<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.5.0">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:exif="http://ns.adobe.com/exif/1.0/"
            xmlns:xmp="http://ns.adobe.com/xap/1.0/">
         <exif:GPSLongitude>16,27.857071E</exif:GPSLongitude>
         <exif:GPSLatitude>50,4.623970N</exif:GPSLatitude>
         <xmp:CreatorTool>Zoner Photo Studio 18</xmp:CreatorTool>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
             '

The `</rdf:Description>` tag is missing from your image. Also interesting, but should not matter, is that the items are separated by newline characters in the correct image metadata..

**Comment by sbillard** [comment]
Turns out the newline characters did make a difference. Caused different behavior on a preg_match() pattern matching.

Fix is in the development release. https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by Mates-K1** [comment]
Fix does not work work for me.

I downloaded older webp from gallery (where nPG show GPS, but not camera etc.) and uploaded it again -> nPG doesnt recognize GPS nor another EXIF information (camera etc).

Sended image was create by Nikon D3200, edited in Zoner Photo Studio 18, GPS added in Zoner Studio X and converted by XnConvert (https://www.xnview.com/en/xnconvert/).

Older images were edited in Zoner Photo Studio 18, GPS were added in GeoSetter and converted by XnConvert.

Removing altitude data from JPG + edit and convert doesnt help.

Image converted from WEBP back to JPG by XnConverter has all information and nPG show them.

**Comment by Mates-K1** [comment]
When I enable XMP plugin, GPSs show.

But there is a difference how much information is displayed for different file types (I had all of them displayed) - ( I use another image)

**JPG**

![jpg](https://user-images.githubusercontent.com/7648991/213660702-3021f612-bc58-4251-a6c5-857d2151408a.jpg)

**PNG**
![png](https://user-images.githubusercontent.com/7648991/213660733-49ec802f-53f1-4e59-8782-236b656ef2eb.png)

**WEBP**
![webp](https://user-images.githubusercontent.com/7648991/213660792-0ac728cd-d69c-4861-a36e-ae4a5650dd88.png)

**Comment by sbillard** [comment]
Yes, you MUST use xmpMetadata for these images since the image data is in xmp format. Perhaps there is a conflict between xmpMetadata ane the image having exif metadata. I will look into that.

**Comment by sbillard** [comment]
None of the PHP exif handlers work with webp images. So, only XMP image data is possible. I did notice that some webp images have not properly tagged items, for instance tiff:make instead of tiff:Make. I have a change in the development releases to make these tags case insensitive.

As to the data displayed. Be sure that the item in the options/image metadata is set enabled and set to display. XMP data is different from exif data.

In the particular case of the 001.pdf webp image those items above are all that are stored in the XMP metadata section of the image.

If you have other image examples you can zip them and attach the zip. Capturing the pdf and converting it turned out to be a challenge.
