### ISSUE TITLE
PHP 8.2 - exceptions on image page

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1470]
![Screenshot 2023-01-20 at 09-42-59 011 (Oddílová schůzka skautek a světlušek - 9  9  2022) -](https://user-images.githubusercontent.com/7648991/213665482-f959c88a-a53f-453f-879c-dc83dfbc6955.png)

![Screenshot 2023-01-20 at 09-44-37 Oddílová schůzka skautek a světlušek - 9  9  2022 -](https://user-images.githubusercontent.com/7648991/213665486-5162522f-5cff-4991-9192-c4407606cbc0.png)

![Screenshot 2023-01-20 at 09-41-32 Oddílová schůzka skautek a světlušek - 9  9  2022 -](https://user-images.githubusercontent.com/7648991/213665488-e74ea2b7-9913-4579-9f6f-74a8ba67f106.png)

**Comment by sbillard** [comment]
Thanks. The first one is actually a typo error. So the PHP 8.2 deprecation was actually useful. The others were just things that are no longer allowed. Fix will be in the DEV release shortly.
