### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1473]
Hi  Stephen, 

1) I cant translate "Convert Explicit site URLs to portable URLs." (description of tagURLs plugin).

2) And I translated this sentence, but in gallery is still in english.
"Optional. Used only if the Google extension is checked. Must be an absolute URL address of the form: "

![Beze jména](https://user-images.githubusercontent.com/7648991/213915283-87f05e04-cc42-48f0-8880-62361146c5c8.jpg)

3) A little bit off topic but I found this while translating. Description of uploader_jQuery says: "jQuery uploader works with PHP 5.3 through PHP 7." Is this true? I use PHP 8.1 and plugin is crossed out.

**Comment by sbillard** [comment]
Yes, Jquery Uploader javascript code has problems with PHP 8 and its author had abandoned the implementation.

I will have to investigate the translation issues.

**Comment by Mates-K1** [comment]
> Yes, Jquery Uploader javascript code has problems with PHP 8 and its author had abandoned the implementation.
👍 

> I will have to investigate the translation issues.
🥇 Many thanks.

**Comment by Mates-K1** [comment]
Ad 1) I don't know if it's related, but I found two other plugins that are the same - I can't translate their description (exampleMacros, galleryToken).  The common characteristic is that when I click on **"I"** for more information, the window is completely blank.

![obrazek](https://user-images.githubusercontent.com/7648991/213943524-27bd55bb-accc-45cb-b3b9-5bcb76201ba0.png)

**Comment by sbillard** [comment]
Are you getting any errors from these? ecampleMacros works for me. I don't have a "galleryToken" plugin.

**Comment by Mates-K1** [comment]
Huh... 
![obrazek](https://user-images.githubusercontent.com/7648991/214118675-f721ab2a-3f04-43b8-a195-7a22c6c42f6b.png)
Ok, I moved it out.


I think I have no related errors.
Just many exif and openstreetmap exceptions like

```
EXCEPTION (8192): "Creation of dynamic property openStreetMap::$layerscontrolpos is deprecated" in /data/web/virtuals/172972/virtual/www/npgCore/extensions/openstreetmap.php on line 560
URI:/1_oddil_skautek/schuzky/2022_09_09_oddilovka/011.webp.htm....
Vzhled:basic
openStreetMap->__construct called from printOpenStreetMap (openstreetmap.php [1057])
 from simpleMap::printMap (template-functions.php [4946])
from include (image.php [134])
from include (index.php [169])
from index.php [90] 
```
```
 EXCEPTION (8192): "Creation of dynamic property Image::$albumanmealbum is deprecated" in /data/web/virtuals/172972/virtual/www/npgCore/lib-controller.php on line 409
URI:/1_oddil_skautek/schuzky/2022_09_09_oddilovka/011.webp.htm
...
Controller::load_image called from Controller::load_request (lib-controller.php [525])
from require_once (controller.php [15])
from include (index.php [61])
from index.php [90] 
```
```
 EXCEPTION (8192): "Implicit conversion from float 8.832 to int loses precision" in /data/web/virtuals/172972/virtual/www/npgCore/exif/exif.php on line 168
URI:/rs_rg/vypravy/
....
Vzhled:bootstrap__kopie_29_12_2022
intel2Moto called from formatOlympusData (olympus.php [76])
from parseOlympus (olympus.php [204])
from read_entry (exif.php [1064])
from read_exif_data_raw (exif.php [1341])
from read_exif_data_protected (functions.php [2471])
from Image->updateMetaData (class-image.php [478])
from Image->__construct (class-image.php [138])
from newImage (class-image.php [46])
from AlbumBase->getAlbumThumbImage (class-album.php [519])
from getCustomAlbumThumb (template-functions.php [1735])
from printCustomAlbumThumbImage (template-functions.php [1845])
from include (inc_print_album_thumb.php [5])
from include (album_standard.php [24])
from include (album.php [11])
from include (index.php [169])
from index.php [90] 
```
```
WARNING: "exif_read_data(21.jpg): Illegal IFD size" in /data/web/virtuals/172972/virtual/www/npgCore/lib-image.php on line 612
URI:/npgCore/i.php?a=rs_rg/vypravy/vyprava_2007_03_02_hostinne/mates&i=21.jpg&s=220&w=220&h=220&cw=0&ch=0&q=85&c=1&t=1&wmk=!&ipcheck=c4468f66ffb33dc960b157be25b1f18d0b06936f&cached=1506676662
IP `185.242.6.204`
exif_read_data called from imageProcessing::getRotation (lib-image.php [612])
from imageProcessing::cache (lib-image.php [225])
from i.php [187] 
```

**Comment by sbillard** [comment]
tagURLs has also been dropped from the distribution. 

The missing info when you click on "I" is from a mal-formed DocBlock. You will note that the category of the plugin is "Missing DocBlock". The opening comment should be "/**" instead of "/*". Of course plugins that are not part of the distribution will not have had these opening comment indicators fixed.

The two dynamic property issues are fixed.

for the "Implicit conversion" can you provide some more information? The error message makes no sense to me. The item should be being treated as a string. What version of PHP was this on? Can you attach the image so I can look further?

"exif_read_data(21.jpg): Illegal IFD size" says there is a problem with the image file. If this is the same image that gives the "Implicit conversion" maybe that is the source of the problem. If not add this image to the ones you attach.

Finally, the "Google - URL to image license" description is because the description text inserted the site URL CONSTANT directly into the text. So the string that was translated would never match the string at runtime.

**Comment by sbillard** [comment]
I am going to close this. I think all the issues in this ticket have been addressed. If not then please open a new ticket.
