### ISSUE TITLE
Rating plugin - redundant "I" with tooltip

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1475]
In the Rating plugin settings there is a redundant letter **"I"** with tooltip at the bottom.

![Screenshot 2023-01-22 at 23-43-46 Admin Options-Plugin](https://user-images.githubusercontent.com/7648991/213944472-a5bd5703-ff0d-4abc-aac8-e8fe63e17ad6.png)

**Comment by sbillard** [comment]
I am not seeing this now. might have been fixed by f931c61d39ddec8cd705b2f520621cdb6e5cae5a

**Comment by Mates-K1** [comment]
👍 Yes, it solved it, thanks.
