### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1477]
Does nPG support the AVIF image format? Alternatively, is it possible to add support?

I am considering migrating to another hosting that can handle AVIF. I got an answer from them about this format: "We have added support to PHP 8.2 on the hosting. But support is not yet in ImageMagick. We will also probably add it to PHP 8.1."

**Comment by sbillard** [comment]
If the PHP  image processing software supports AVIF then nPG can support it. Image metadata data support would require it be in XMP format. AVIF will need to be added to the `$_imagick_format_whitelist` array.

**Comment by sbillard** [comment]
I have added AVIF to the ImageMagick support script. This should be all that is needed to make those images available to nPG. I do not have access to ImageMagick, so please let me know if this solves the issue.
