### ISSUE TITLE
Latest items not working

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1487]
Somehow the latest added images (For instance in theme Ardoise) are only displayed in the archive and latest images when you upload something with FTP. I have an admin user that manually adds images and these are not displayed in the archive or in the latest images.  The images are published.

**Comment by sbillard** [comment]
Please detail the process by which these images are uploaded, etc. so that I can try to reproduce the issue. Also I am not sure exactly what you are saying. Are the images displayed in the album but not in the archive? Also I am not sure I understand what you mean by "latest images."

Images uploaded via FTP will not show up until they are "discovered." That typically happens when the album is visited either on the admin pages or from the theme.

**Comment by Elinth** [comment]
The images were uploaded by the standard upload facility "upload here", not via the elfinder plugin or ftp. They were uploaded in a folder in February. The images are displayed in the album but when looking in the Archive in February they do not appear. Also on the front page I have a latest images section. They were not displayed in there at the time.

**Comment by Elinth** [comment]
The images were uploaded by the standard upload facility "upload here", not via the elfinder plugin or ftp. They were uploaded in a folder in February. The images are displayed in the album but when looking in the Archive in February they do not appear. Also on the front page I have a latest images section. They were not displayed in there at the time.

**Comment by Elinth** [comment]
The images were uploaded by the standard upload facility "upload here", not via the elfinder plugin or ftp. They were uploaded in a folder in February. The images are displayed in the album but when looking in the Archive in February they do not appear. Also on the front page I have a latest images section. They were not displayed in there at the time.

**Comment by sbillard** [comment]
(I deleted the duplicate postings.)

Both the archive view and the image_object_statistics use the image timestamp (date and time image was taken) for the "date" of the image. This may not be in the same month as the image was uploaded. For instance if uploading old objects. So the images will be in the archive based on when the photograph was taken, not necessarily when it was uploaded.

The printLatestImages() function has the ability to sort by the file timestamp. Use "latest-mtime" as the option. But be aware that this may not be what you want either;. The file timestamp will change when almost anything is done to the file--for instance changing its file permissions.

**Comment by Elinth** [comment]
Thanks for the explanation, there is no way to do the archive via upload date? Possibly by adding something in the functions.php? It seems logic for an archive to behave as a upload archive, don't you think?

**Comment by sbillard** [comment]
There actually is no "upload date" recorded. What you could do is edit the image metadata with a metadata editor and change the date to whatever you want. Date taken seems more reasonable for the archive order. After all, date uploaded is pretty arbitrary. Anyway, one would expect that the images will normally be uploaded shortly after being taken.

If the image metadata has no date taken fields set then the "date" used will be the file mtime date when the image was "discovered." For the process you describe that would be the same as the upload date. For images uploaded via FTP it would be the date the images was first noticed by netPhotoGraphics. This latter is not a predictable date. Any addition to netPhotoGraphics to record an "upload date" would behave the same.

**Comment by Elinth** [comment]
Thanks for your quick response, you might be right. It seems more logic in hindsight. One question though, I somehow seem to still miss a bunch of images in the archive..

**Comment by sbillard** [comment]
If the images show up in the albums then they must be somewhere in the archive. They will not show up if not published or the album not published. But you as the site administrator should see them as you can view unpublished items. 

I suggest you look into the database entry for the ones you do not see. Check what the 'date' column value is. That is where the image should appear.

**Comment by Elinth** [comment]
Cool, I will do that. Thanks for your support!
