### ISSUE TITLE
AVIF support #2

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1498]
I moved to hosting which support AVIF in GD library.
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/57f3ab2b-0b94-45db-ae56-410c66eea76e)

And I am not using Imagick
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/ba47da60-d318-4001-9522-cee825f078ef)

But nPG cant recognize that AVIF image.

4 files on server
![11](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/82075877-a45d-401b-8ba6-96de800e755d)

3 files in nPG
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/df02d0d4-ee0c-4696-954f-9096bd021ccc)

Can you help please?

**Comment by Mates-K1** [comment]
Many thanks, that works. 👍 

The last thing that doesn't work with AVIF is Colorbox. :( Is it also possible to make it work for AVIF?

**Comment by sbillard** [comment]
Colorbox is working for me on the development build: https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.18.02.01.zip

There are some changes which might possibly have fixed things. I have made it so that if the GD library adds any more image types they will be automatically supported with default behavior. I don't see how that could have effected colorbox, but please try that build and see it things work.

**Comment by Mates-K1** [comment]
Sorry, it does not work for me. :(

It's probably not related, but when I installed it I got a message that my graphics library doesn't support WEBP format, but the reality is different. This is the first time I've seen this message.

Message in instalation:
![Screenshot 2023-06-02 at 19-31-25 https __skautskagalerie cz](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/78b52533-3206-4532-8469-60cce567a93d)

Info in gallery:
![Screenshot 2023-06-02 at 19-33-13 Administrace Přehled-Instalační informace](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/a7fb55b9-e843-4d8d-a506-c79ace5b30ce)

**Comment by Mates-K1** [comment]
Hmmm... it works in:
Paradigma

It does not work in:
Enlighten
Effervescence+
Bootstrap
Basic

**Comment by sbillard** [comment]
That error is indeed a false one. A but in the GD image support discovery implementation I am working on. It would not impact the ColorBox support. You can just ignore it for now. Fix is in the development stream.

How are you using ColorBox? My test was to set the "full image protection" option to "protected view" and click on the image in the front end. As said, that works for me on my test system. Unfortunately my Host has not moved to PHP 8 yet, so I cannot host a test case  for you to try. AVIF is not available until PHP 8.1. (Given my Hosting providers slowness to implement new versions of PHP it may be years until it has PHP 8.1!) What exactly are your symptoms?

**Comment by Mates-K1** [comment]
My standard setting is:
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/1abc0180-110c-4a08-b6e0-06c008851889)

I use Bootstrap theme.
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/2b8ab14a-3ec4-474d-830f-25d3d5bc0beb)

When I click on thumb, I get:
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/fcacd97c-d200-4710-962f-8649e9f04b40)

If you could use my help, I can provide you with my FTP and gallery credentials.

**Comment by sbillard** [comment]
Works for me in all but Bootstrap. Looking at the page HTML for Bootstrap, there is no full image link href. Bootstrap does not appear to support full image links.

**Comment by sbillard** [comment]
Can you try Basic theme clicking on the image page image to view the full image? Also what are your Bootstrap theme options?

**Comment by Mates-K1** [comment]
But.... It works fot JPG and WEBP, but not for AVIF.

![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/10c0ee42-b5a5-46f4-b7ee-ceb1c7169598)

**Comment by sbillard** [comment]
The error image you show looks like a javascript error occurred. Maybe a javascript conflict. Can you show me the Bootstrap theme options you use? Also check your browser console for javascript errors. (Or give me the link to the failing album page.)

**Comment by Mates-K1** [comment]
There is the link to AVIF album:
https://skautskagalerie.cz/rs_rg/vypravy/vyprava_2004_08_07_amerika/

**Comment by sbillard** [comment]
There is nothing obvious in the console log. Did you try the Basic theme full image display?

I've setup my Bootstrap theme as best as I can guess to be like yours
![image](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/2474007/570268d5-4279-4194-bc9d-9ac7d7ede0df)
and all works for me.

**Comment by Mates-K1** [comment]
Not works in basic theme (JPG ok, AVIF not)
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/a5bfbd67-c639-4611-b002-e0434208df5b)

**Comment by Mates-K1** [comment]
It is image problem. One image is ok (from XnConverter), another not (from Zoner Photo Studio X).

**Comment by sbillard** [comment]
Thanks for the update. I doubt I would have any way to correct this. Maybe a colorbox issue or maybe a corrupt image. Colorbox has not been updated since the version nPG uses. But I don't see any image type specific code in the plugin.

**Comment by Mates-K1** [comment]
I've tried dozens of AVIF file variations from Zoner Photo Studio X and they all don't work with Colorbox. I've also tried five online converters and one other Windows program (called XnConvert) and all AVIFs are displaying correctly.

So the problem is probably with Zoner Photo Studio X - I have already written to their support.

**Comment by sbillard** [comment]
Thanks for the research. I will then close this ticket. There is a new DEV build with some more things fixed https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.18.02.03.zip including the setup error message.

**Comment by sbillard** [comment]
Not a netPhotoGraphics caused problem
