### ISSUE TITLE
"Refresh album metadata" refresh all images in gallery

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1501]
The Refresh album metadata button (on the album page) will refresh all images in the entire gallery. 

But I would expect it to only restore metadata for images in that album.
![Screenshot 2023-06-03 at 01-02-38 Admin Albums-Album](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/6107d613-e104-4183-8265-9302cbdd5208)

**Comment by sbillard** [comment]
It would appear this happens only when there are enough images in the album to cause an automatic page refresh.

**Comment by sbillard** [comment]
fix is in https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by Mates-K1** [comment]
It works, many thanks. 👍
