### ISSUE TITLE
Undefined array key 3 in extensions/class-video/getid3/module.audio-video.quicktime.php

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1502]
netPhotoGraphics version 2.00.18.02.03

Themes

- Enlighten
- Masonry
- minimal

have this problem now:

```
UPOZORNĚNÍ: "Undefined array key 3" in /pub/kroulmwa/skautskagalerie.cz/web/www/npgCore/extensions/class-video/getid3/module.audio-video.quicktime.php on line 1638

URI:/page/login

Vzhled:minimal

getid3_quicktime->QuicktimeParseAtom called from getid3_quicktime->QuicktimeParseContainerAtom (module.audio-video.quicktime.php [2169])

from getid3_quicktime->QuicktimeParseAtom (module.audio-video.quicktime.php [283])

from getid3_quicktime->QuicktimeParseContainerAtom (module.audio-video.quicktime.php [2169])

from getid3_quicktime->QuicktimeParseAtom (module.audio-video.quicktime.php [283])

from getid3_quicktime->Analyze (module.audio-video.quicktime.php [93])

from getID3->analyze (getid3.php [781])

from Video->getMetaDataID3 (class-video.php [393])

from Video->updateMetaData (class-video.php [423])

from Video->__construct (class-video.php [129])

from newImage (class-image.php [46])

from getItemByID (functions.php [2521])

from filterImageQueryList (template-functions.php [3312])

from getRandomImages (template-functions.php [3375])

from printRandomImages (template-functions.php [3507])

from include (password.php [10])

from include (index.php [169])

from index.php [90]
```

**Comment by sbillard** [comment]
It looks as if the video you are accessing does not have the GPS altitude data. The codeat class-video/getid3/module.audio-video.quicktime.php on line 1638 tries to suppress errors: 
`@list($all, $latitude, $longitude, $altitude) = $matches;` 
but I guess PHP 8 has decided to ignore the '@' error suppressor operator.

This can probably be fixed by changing the code to:
`$matches = array_merge($matches, array(NULL,NULL,NULL);
list($all, $latitude, $longitude, $altitude) = $matches;`

As I do not have a video which exhibits this failure could you please try the fix and report back.

**Comment by Mates-K1** [comment]
I have:

`EXCEPTION (0): "syntax error, unexpected token ";", expecting ")"" in /pub/kroulmwa/skautskagalerie.cz/web/www/npgCore/extensions/class-video/getid3/module.audio-video.quicktime.php on line 1638`

**Comment by sbillard** [comment]
Sorry, That was a typo on my part. should be `$matches = array_merge($matches, array(NULL,NULL,NULL));`

**Comment by Mates-K1** [comment]
It works if I am log in. When I am guest, I get Internal Server Error

![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/b1b1fa54-25e2-4ab7-ad0a-88f7d515a55d)


In nPG logs is nothing. In my Bootstrap theme all works fine (without internal server error too).

**Comment by sbillard** [comment]
That change can't possibly be subject to being logged in or not, so the server error must be something else. The Apache error or access logs should have some entry for this failure. Perhaps that will give us a clue.

You say that Bootstrap does not give the internal server error when not logged in?

**Comment by Mates-K1** [comment]
Unfortunately I don't have access to logs outside nPG now.

Well, it's embarrassing and strange... The error is no longer displayed today and everything works as it should. It was probably a caching problem on my side. Sorry for the complication.

**Comment by sbillard** [comment]
Gl;ad the problem has gone away.

Internal Server errors are often file permissions errors. Or at least file access errors. Anyway, such errors mean that the PHP script did not load successfully. So netPhotoGraphics has no opportunity to field and log the errors. To debug you would have to contact your hosting provider to get the server's logs.
