### ISSUE TITLE
Login form - better styling

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1503]
In loginForm.css please change

```
#logon_box fieldset {
	width: 310px;
	text-align: left;
}
```
to 322 px.

Before:
![001](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/a3b6cf9b-5776-454f-bdde-8fe51b41097e)

After:
![002](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/5b7cd989-de80-41a5-b5fa-5729b8c680e5)

**Comment by sbillard** [comment]
I guess fonts render differently on your system than  mine. I don't get the same rendition. But no problem, I will make the change.

**Comment by Mates-K1** [comment]
Hmm.... I use Windows 11 vith Firefox 113 and Edge 114 and in both of them it looks just like the picture.

**Comment by sbillard** [comment]
please try https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.0%2B/setup-GIT-2.00.18.02.05.zip as for me this is a better fix.
![image](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/2474007/4a4f6c4a-2f9a-4b3e-a3d7-b091444f2345)

**Comment by Mates-K1** [comment]
Yes, that's how it looks for me now. 

But this is what it looks like when I click in the locked part of the gallery in my Bootstrap theme (not only in this theme), the login form looks like this. (I'll shorten the text on the button.)
![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/25ba2aa0-0e53-4cf0-b9aa-642d88a8c1e6)

Even on mobile, the login form looks better (flowed into the side much more).
