### ISSUE TITLE
Faulty Image count on jQuery Colorbox Slideshow

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1506]
The image count that appears above a jQuery Colorbox Slideshow is always exactly twice as many as the actual number of images in the directory.  ie: in mid show the line directly above the currently displayed slide is something like "Image 2 of 100" where there are actually only 50 photos in the folder.  When it gets to the last one (number 50) the slideshow loops back to the start OK but the display now reads Image 52 of 100.  It's probably a simple bug of an unwanted 2 somewhere (and also fairly trivial, it has no effect on function) but…

Thanks

NK

**Comment by sbillard** [comment]
I guess I will need some more details. I have tried slideshow on several themes and do not see this behavior. All image counts are correct.

**Comment by nerdykit** [comment]
Ah, you gave me the clue.  I'd forgotten that I was using a custom version of Basic Theme.  Slideshow in the default version of Basic theme works as it should so the problem lies in my customization and that's my bad.  Will close this"issue" now and go looking at what I've done wrong.  Thanks.

**Comment by nerdykit** [comment]
I figured it out (sort of), I had wanted the "View Slideshow" link to appear higher on the image page and so created a version of it placed after the photo title. If the link appears above the actual display of a photo then it shows as twice as many photos as are in the directory, doesn't matter where the link is located, just before the actual image for that page is displayed.  Double.

The link below the image, is correct and shows the correct count.  Weird that placement of the slideshow link (just copied the same php line as is used for the below image link) appearing in the top of the page (above the image) gives double the number of items actually in the directory.

NK

**Comment by sbillard** [comment]
Did you leave in the original printSlideShowLink function call? I get the right count if I move the link. With both function calls the count is double. The function places some JS and a set of image references on the page. I am guessing that the slideshow JS collects these links via the rel="slideshow" attribute. So if you print the link twice you get twice the number of images. Since the sequence repeats you may not have noticed that the image number keeps increasing past the number of actual images.

There might be a way to have multiple slideshows on a page. I would have to research the plugin to see if there is such an option.

**Comment by nerdykit** [comment]
Ah that's the explanation.  What I wanted was two links to the same slideshow, one to appear above the image where it can more easily be found and one below the image in its "traditional" location (Basic Theme).  That may not be possible, I can settle on just once instance of the call to the slideshow and that will do.

**Comment by sbillard** [comment]
Turn out it is possible and not too difficult to implement. The non-colorbox slideshow already dealt with multiple instances. Just had to adapt the colorbox one to the same concept. Fix will be in the dev build shortly.

**Comment by sbillard** [comment]
fix is incorporated in the dev release: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Comment by nerdykit** [comment]
Yes!  That works just fine. Thanks.
