### ISSUE TITLE
Open Street Map plugin - is it usable?

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1515]
Just got curious about this plugin and attempted to enable it, I get a warning when I ask for information (blue i icon)

EXCEPTION (0): "Call to undefined function renameOption()" in /***removedpath******/npgCore/extensions/openstreetmap.php on line 33

I'm using php 8.2

Thanks

NK

**Comment by sbillard** [comment]
That error is unique to the Info display. renameOption() is defined by setup and the info utility did not load the setup functions. So it will have no impact on regular use of openStreetMap.
