### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1527]
Somehow it looks as if all my cache specifications are gone.  If I go to "cache  album images" I cannot select any of the themes using the checkboxes before their names and for all of the themes when I expose the cache settings for any theme all I see is one or more sets of "Invalid Cache Set" and none of those checkboxes can be selected and they are all empty.

I did attempt to create a new cache set for a theme (using add) and that was successful but when I tried to actually cache for an album using that theme with that as the only cache instruction established (all the others are "Invalid" and are empty, I get

EXCEPTION (0): "round(): Argument #1 ($num) must be of type int|float, string given" in **** removed path*****/npgCore/functions-basic.php on line 1256

How can I restore all of the former cache settings that appear to have been lost and is there a PHP 8 error lurking in there?

Thanks

NK

**Comment by sbillard** [comment]
I think the issue involves saving cache sizes in the cachmanager options. It looks like all the built-in cache sizes are being corrupted but custom sizes seem to stick. You can restore the built in options by running setup. That does not seem to kill the custom cache settings.

I have not found the source of the corruption yet, though. Stay tuned. Also have not looked into the EXCEPTION yet. But I can reproduce it. Though not corrupting the sizes was fist priority.

**Comment by nerdykit** [comment]
There's a longer entry in the debug log I'll put it here in case it helps

EXCEPTION (0): "round(): Argument #1 ($num) must be of type int|float, string given" in ******************/npgCore/functions-basic.php on line 1256
URI:/*****/npg/extensions/cacheManager/cacheImages.html?tab=images&action=select&album=travel/danube-black-sea-2023/novi-sad-serbia
IP `**********`
user:*******
round called from getImageParameters (functions-basic.php [1256])
from loadAlbum (cacheImages.php [91])
from include (cacheImages.php [394])
from index.php [49]

**Comment by nerdykit** [comment]
For what it's worth I don't think I was getting that error before the last upgrade so it may be an introduced error as part of your php 8 adjustments.  I have refreshed the cache relatively recently and was successful.  It's only failing now.

**Comment by nerdykit** [comment]
Running setup did properly restore the cache settings but I can't do a cache for any recently uploaded albums which is something I like to do rather than cache on the fly.

**Comment by sbillard** [comment]
The error is an artifact of PHP 8 something. The fix is to change the lines at 1256 to
`	if (is_numeric($cx)) {
		$cx = (int) round($cx);
	}
	if (is_numeric($cy)) {
		$cy = (int) round($cy);
	}`

That is replace `!is_nuull` with `is_numeric`

The saving thing is being obstinate. Somehow hidden inputs are not being posted on the save.

**Comment by sbillard** [comment]
I have solved the "save" problem. I did have to remove all the "standard" cache sizes from the options list. They weren't changeable anyway, so no loss.
