### ISSUE TITLE
Album thumbs cropping setting - any changes?

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1533]
Have there been any changes to the thumbnail cropping recently?
Because after updating to the latest nPG I have all the thumbnails set wrong. In all themes. :(

![obrazek](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/b1dcf528-f208-4a18-bdc7-d41c27c11b69)

**Comment by Mates-K1** [comment]
The thumbnail is set as 100% size from the top left corner.

**Comment by sbillard** [comment]
I found the cause. It was a fix to another problem. Hopefully I can find a fix that deals with both issues. But for now, revert to the previous release and it should work.
