### ISSUE TITLE
nPg has crashed - blank screen

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1535]
My installation seems to have crashed completely.  All I'm getting is a blank screen after a long delay when I try to access my nPg installation either as a viewer or for admin purposes.  I can verify that the apache2 server and mysql is running properly from other parts of the site that are working.  It's just the npg installation that has gone south.

I'm not sure what is the best thing to do from this point.

**Comment by sbillard** [comment]
First thing is to check the error logs. Apache and PHP logs for sure. Perhaps also the nPG debug log which is stored in the data folder.

If those show nothing useful then you would need to instrument the software to see how far it gets. nPG first loads from the root index.php script. That script decides whether to load the normal front end (npgCore/index.php) or the admin pages (npgCore/admin.php) Put in echo statements at various points to see if you reach them before the failure.

What does the URL look like once the blank page appears? The long delay sounds like maybe a rewrite loop. You can try a direct (not rewritten) link to the admin pages to see if that loads. `.../npgCore/admin.php` . (The front end npgCore index.php does not allow direct linking, it requires being loaded by the root index.php script.) You might also rename the text files in the setup folder to `.php` and run setup with a direct link and see if it cleans up anything.

The other common cause of blank pages is file permissions denying loading a script file. That should show up in the access logs.

**Comment by nerdykit** [comment]
Thanks, running setup manually after renaming the setup files resolved the problem immediately.  Have protected the setup files again.  Will close this issue.
