### ISSUE TITLE
efFinder plugin won't remain enabled

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1559]
I use elFinder plugin regularly for my uploads.  Currently using 2.01.00.03 (Production) and I'm finding that every few days I have to re-enable elFinder plugin and it remains enabled for a few days and multiple admin logins and then it's gone again, re-enable it, same result after another few days.  This has been going on since latest update.  elFinder itself works OK once it is re-enabled.

Thanks

**Comment by sbillard** [comment]
Plugins can get disabled if they throw an error. (This is to prevent error log flooding.) Any error logs?

**Comment by nerdykit** [comment]
There's a lot of these in the Debug log…     

{51980:Fri, 26 Apr 2024 18:01:53 GMT}	

    WARNING: "chmod(): No such file or directory" in /<<removed>>/public_html/gallery/npgCore/functions.php on line 2932

    URI:/gallery/npg/admin-tabs/edit.html?page=edit&action=save&album=travel/mexico-2024/san-miguel

    IP `<<my ip>>`

    user:<<my admin user>>

    chmod called from npgFunctions::removeDir (functions.php [2932])

    from Gallery::clearCache (class-gallery.php [846])

    from require_once (image_save.php [98])

    from include (edit.php [374])

    from index.php [49]

**Comment by sbillard** [comment]
I am away from my computer for a couple of days. I'll look at this error when I can access my development system. but since there is no elFinder in the execution stack I doubt this is the cause of the disable.

**Comment by nerdykit** [comment]
Not a problem.  Will monitor my use of elFinder and check the logs as soon as I can see it become disabled again.

Thanks

**Comment by sbillard** [comment]
I have looked at the disable plugin code. This will happen only on a a"fatal" error, so not on things like invalid index. I have also looked at all my test sites. Not all had elFinder enabled, but it is likely that it never was. On my main site and on the netPhotoGraphics site the plugin is enabled. Who knows for how long.

So hopefully there will be an error log entry around the time you next see the plugin disabled.

**Comment by nerdykit** [comment]
It just happened…

 {84259:Mon, 29 Apr 2024 21:11:48 GMT}	

DEPRECATED: "Decrement on empty string is deprecated as non-numeric" in <<path removed>>/public_html/gallery/npgCore/extensions/elFinder/php/elFinder.class.php on line 4490

URI:/gallery/npg/extensions/elFinder/php/connector_npg.html

IP `<<my ip removed>>`

user:<<my admin user removed>>

npgShutDownFunction called from unknown

**Comment by nerdykit** [comment]
Thanks.  I have installed the Dev release…(I got a lot of messages about missing files during the Setup process…seemed to be all of the themes and many from core) but it all seems to work OK and I've just enabled elFinder plugin and used it successfully.  Will close this issue for now and re-open it if elFinder gets shut down again.

**Comment by nerdykit** [comment]
Just tried running Setup again to see if I could get the list of affected files again but no joy there.  It all seems to work OK so I think it must have just been a case of file mtimes not matching since I was updating from the latest production version to a DEV release.
