### ISSUE TITLE
New Installation fails

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1560]
Trying a completely new netphotographics installation from scratch just for testing and it fails…

EXCEPTION (0): "Failed opening required 'npgCore/netPhotoGraphics_cfg.txt' (include_path='.:/usr/share/php')" in ==pathremoved==/public_html/testgallery/npgCore/initialize-basic.php on line 59 

All I did was download setup-master-2.01.00.03.zip via wget into the target directory, unzip it, rename extract.php.bin to extract.php and attempt to visit the extract.php file via web browser as directed in readme file   I did the linux portion of all of these steps as sudo  ie   sudo wget … but cannot do a fresh install (I'm running php8.3.6)  I get the above error message when I attempt to visit extract.php using Firefox.

Thanks

NK

**Comment by sbillard** [comment]
please modify initialize-basic line 59 to read `require (CORE_SERVERPATH . '/netPhotoGraphics_cfg.txt');`

**Comment by nerdykit** [comment]
That seems to have worked.  Still testing but I've got a working new installation.  Will close.
