### ISSUE TITLE
Image Title not appearing

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1562]
I routinely add Titles to images by setting the Headline field in the IPTC core section of metadata to the desired value.

I do this using Adobe Bridge and it's been part of my workflow for many years of sorting images in Bridge and then viewing the finished product on the web server with nPg.

After the latest update I'm finding that this seems to be broken.  Headlines are not being automatically set as the Title for the occasional image that has one.  Images with no special title still appear as normal in my theme (Basic) with the image filename appearing in the Title space above the image.  But where an image had a headline, the title space disappears and nothing appears.  This is recent.  Older image groups work as always, the default title is the filename, any headline metadata replaces that and becomes the title.

Now there's nothing.  The title space above the image just disappears, the image moves up slightly and there's nothing BUT images with no IPTC headline still show their default title (the filename) normally.  If I click on Image info below the image I can see the Headline as part of the EXIF display but the process where image titles are created from Headline IPTC seems broken.  So the Headline is there, with the image, that is confirmed.  But when the database discovers and parses new images to get any image titles (via IPTC Headline), that doesn't seem to be happening.

Titles typed directly into the admin image pages DO appear.  It's just the automatic parsing of IPTC titles that seems to be broken.

**Comment by sbillard** [comment]
fix is in 
https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.1%2B/setup-GIT-2.01.00.04.02.zip

**Comment by nerdykit** [comment]
Thanks.

NK

**Comment by nerdykit** [comment]
Just did another batch and it's clearly working correctly now, both Headlines and Description are appearing when they are read from the photometadata.  Thanks for the fix.

NK

**Comment by sbillard** [comment]
Thanks for t conformation
