### ISSUE TITLE
Upgrade issue?  Database Server Error

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1572]
Just did upgrade to Production version 2.01.00.08 and got Database Server error message
MySQLi Error 1060: Duplicate column name 'EXIFImageHeight'

![Screen Shot 2024-05-20 at 4 49 31 PM](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/3220548/65a7c9af-2d9d-4031-9670-33ec02953743)

**Comment by sbillard** [comment]
There was a bug in the older versions of nPG where fields marked as do not process were not removed from the database. 

Please try the following:
Run setup and see if the error has gone away.

If it persists Set your image metadata items to "default" on the image options page and run setup.

**Comment by nerdykit** [comment]
Problem was not present after running Setup

Thanks.  Will close.
