### ISSUE TITLE
Preg_Match (null) warning

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1582]
I'm seeing a php warning (passing null) in the logs on this…

 {389792:Sun, 09 Jun 2024 06:43:59 GMT}	

DEPRECATED: "preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated" in ==url removed==/gallery/npgCore/class-image.php on line 450

URI:/gallery/travel/east-africa-2013/show/110-TLMw-62-IMG_7846.jpg.html
IP `119.13.100.168`
theme:basic_for_kit
preg_match called from Image::evalFraction (class-image.php [450])
from Image::read_exif (class-image.php [477])
from Image->updateMetaData (class-image.php [560])
from Image->__construct (class-image.php [138])
from newImage (class-image.php [46])
from printSlideShowLink (slideshow.php [616])
from include (image.php [151])
from include (index.php [169])
from index.php [72]

**Comment by sbillard** [comment]
Thanks. Another of the PHP 8.x deprecations. Unfortunately these are hard to find ahead of time. Also apparently all my images have numbers in these fields. Perhaps you could provide me with the image that caused this failure?

Anyway, fix is on the way. It will be in the DEV release shortly. If you get more of these please report.

**Comment by nerdykit** [comment]
This is one of the images that triggered the response…
![110-TLMw-62-IMG_7846](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/3220548/9701bc99-0359-4d87-870f-9929b2dc8e5d)

**Comment by sbillard** [comment]
I do not get the failure with this image. I dumped out the EXIF data and saw nothing that should have triggered the error. I was just curious as to what the data was that caused the fault. But it does not really matter, the fix will work no matter what.
