### ISSUE TITLE
Video poster image doesn't display correctly in Mobile theme

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1595]
I use Mobile plugin and theme Mobile for users connecting via a phone.

It works OK but there's one issue that may be a bug in the Mobile theme css or else I haven't got something configured correctly.  Everything displays correctly (normal image files) except for the poster image for a video.  The video is properly displayed and played when the poster is clicked but the video's poster image is not properly downsized for the phone screen, regular images are fine, it's just the poster image for videos that is still at full size and thus the overlaid 'click on the arrow' image for playing the video is somewhere off screen.  Maybe video poster images are a different category from conventional images and I just need to add a definition for them into the cacheing.  Any ideas of how to fix this?

**Comment by sbillard** [comment]
I don't really know how the Mobile theme operates. But in general, there should be a "controls poster=..." bit of html that describes the height/width of the poster image. I couldn't find a video with a poster in my test images. Probably have one, but really don't know where to find it. So I simulated having one and things looked as I expected. But of course this was only a simulation. The html I got was:

`<video   class="video-cv" alt="will-ferrell-robert-goulet-sings" width="470" height="370" 
controls
poster="/dev/cache/sound%27s/npg_extensions_class-video_mp4Default_w470_h370_cw470_ch370_thumb_watermark.jpg?cached=1731540368"  
preload="none" >
<source src="/dev/albums/sound%27s/will-ferrell-robert-goulet-sings.mp4" type="video/mp4">
						Your browser does not support the video tag
</video>`

Maybe you can provide me a video to make a proper test.

**Comment by nerdykit** [comment]
Here's a video (silent) and a poster image file for that video.  As far as I can see, poster images don't actually get cached.  Normal behavior (desktop or tablet screen) is to overlay an arrow in the middle of the poster image and when viewer clicks anywhere on the poster image, the video is loaded and begins to play.

https://github.com/user-attachments/assets/1b689869-98eb-4826-b2e1-46093f10540b

![skating-at-jacks2](https://github.com/user-attachments/assets/f797f704-ca18-4983-b055-32c1cbaeb5df)

I'm just using the class-video plugin with a specified width of 960

The film is about 70 years old so I consider myself lucky to have it and many others.

**Comment by sbillard** [comment]
Have you tried viewing the page with a computer browser? My local test site is not accessible from my mobile devices so I tried your video on my computer and it looks correct.

![Screenshot 2024-11-15 143822](https://github.com/user-attachments/assets/e32f6e88-cf5c-4f6e-bc6f-0ef23fd5aafd)

Mobil theme does not specify height and width, so the height and width of the video are used. 

Can you inspect the HTML on your mobile? the poster element for me is pointing to an image in the cache.

**Comment by nerdykit** [comment]
Here’s the code from my mobile. I think the problem is the height and width specifications aren’t correct for a phone. They’re right for a large screen but not for a phone<br/>skating-at-jacks2				</h2>
			</div>
			
			<div id="image">
									<strong>
						
					<video   class="video-cv" alt="skating-at-jacks2" width="960" height="750" controls poster="/gallery/cache/family/doan-family-movies/skating-at-jacks2_w960_h750_cw960_ch750_thumb.jpg?cached=1731707569" preload="none" >
						<source src="/gallery/albums/family/doan-family-movies/skating-at-jacks2.mp4" type="video/mp4">
						Your browser does not support the video tag
					</video>
					</strong>
								</div>Sent from our iPhoneOn Nov 15, 2024, at 2:57 PM, Stephen ***@***.***> wrote:﻿
Have you tried viewing the page with a computer browser? My local test site is not accessible from my mobile devices so I tried your video on my computer and it looks correct.
Screenshot.2024-11-15.143822.png (view on web)
Mobil theme does not specify height and width, so the height and width of the video are used.
Can you inspect the HTML on your mobile? the poster element for me is pointing to an image in the cache.

**Comment by sbillard** [comment]
Everything in that HTML thinks the image size is 960 x750 pixels. So if something is shrinking the image for the mobile device that code must not be aware of the poster element and is not shrinking it. This is a pretty old theme, maybe from before HTML had the poster tag.

**Comment by nerdykit** [comment]
Yes, I think that theme goes all the way back to the old zenPhoto days.  Everything else works fine in Mobile I think it's probably just better to live with this relatively minor problem.  It really only matters when Mobile is actually used on a phone and is more noticeable when the phone is in "portrait" orientation vs landscape.  The movie itself scales down and displays just fine, it's just a problem with the scaling of the poster image.  Not worth the time to try to fix that old theme.  I will close this issue but I appreciate you looking into it.
