### ISSUE TITLE
Video not centered with VideoJS plugin

### ISSUE THREAD

**Issue by sbillard** [netPhotoGraphics/netPhotoGraphics#909]
The video is left justified when using VideoJS as the video handler. With all the other handlers, the video is centered in the frame. Depending on the theme, this can look quite ugly.

**Comment by JimBrown** [comment]
I'm aware of that. Next on my to do list after going through the 
album.php files. (Works fine in zenFluid. ;-) ).

...jim

**Comment by sbillard** [comment]
I decided to look into this since I was bored. But now things look just fine. Perhaps I have got rid of the themes that didn't present the video well. At any rate, I am closing the issue. (But I did find another problem while investigating. See issue #1083.)
