### ISSUE TITLE
Add a NetPhotographics payment module

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/netPhotoGraphics#989]
It would be interesting to add a payment module to sell images on netphotographics website. users can set the price of photos from the administartion.
For this we can add this module at first and improve it in a second time. We can attract a lot of users because can photo cms offer this.

ZenPayPal : https://github.com/hucste/ZenPayPal    ( we can call it NetPay or NGPaypal)

**Comment by sbillard** [comment]
Have you tried this plugin?

Please note that "being interesting" is insufficient justification. You should ask yourself who the feature is targeted to. There have been no requests for it, so either this plugin satisfies the need or there is no such need.

**Comment by netPhotoGraphics** [comment]
Yes I tested the plugin does not work at all it needs an update to NPG 1.9.0. Personally I need this module for my photo gallery. 
Then, the cms can be used by professional photographers who may need to sell their photos via NPG.

**Comment by sbillard** [comment]
You can do some research on this. You need to find a PPP script that provides the functionality you want. Also there needs to be a testing plan. I do not  have (and will not create) a payment account. Such an account is needed to test the implementation.

**Comment by By-oussef** [comment]
Ok I just created a Paypal account I can test the plugin.

**Comment by sbillard** [comment]
Good, now just find a PHP payments script that you like.

**Comment by By-oussef** [comment]
After seeing several payment scripts I found a complete payment script based on symfony

https://packagist.org/packages/jms/payment-paypal-bundle

Documentation : https://jmspaymentcorebundle.readthedocs.io/en/stable/setup.html

**Comment by sbillard** [comment]
I think that there is too much baggage with this solution. Maybe it is best, but certainly adapting it as a plugin would be quite expensive and maybe have compatibility issues. It would be better if there were a stand-alone script.

Anyway, it seems that much work will probably be needed. I have no particular interest in such a capability nor have any others expressed a need. So if you want to go forward with this and need my help it will have to be a custom development. My fee for custom work is $80 an hour. This project might take 100 hours or so.

**Comment by sbillard** [comment]
Guess that the value of this plugin does not meet the cost of providing it.
